### ISSUE TITLE
Chrome Autofill not forcing shipping updates

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce#11813]
## EXPLANATION OF THE ISSUE

Chrome v. 52.0.2743.116
WordPress v. 4.6
WooCommerce v. 2.6.4

When checking out, if the shipping method has defaulted to "There are no shipping methods available....", then using Chrome's Autofill on Billing Details will not cause the 'Shipping' field to update.

This results in a page with shipping information that qualifies for shipping but says 
"There are no shipping methods available. Please check your address or contact us if you need any help."

If you manually adjust any of the Billing Details fields, the "Shipping" field will update with the appropriate options.

Video: http://cld.wthms.co/HJ67/61VyPBy0
## STEPS TO REPRODUCE THE ISSUE

Set up a shipping zone that is restricted to a certain area, eg.  Ontario
Set your Default Customer Location to "Geolocate"
As a new customer add an item to your cart and checkout
On the checkout page use Chrome's Autofill to populate and address that would qualify for shipping (in this example somewhere in Ontario, Canada)

Expect result is that the shipping would update after the autofill
Actual result is that the shipping does not update until you manually edit any of the address fields
## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://fullysupported.mystagingwebsite.com
Site URL: https://fullysupported.mystagingwebsite.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.10
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.50.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (6) ###

Akismet: by Automattic – 3.1.11
Jetpack by WordPress.com: by Automattic – 4.2.2
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 4.0.3
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.4
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #104 - /shop/
Cart: #105 - /cart/
Checkout: #106 - /checkout/
My Account: #107 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Customer/Order CSV Export ###

Order Export Format: default
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

```

**Comment by mikejolley** [comment]
Didn't happen for me. I set it up slightly different to work with my autofill.

- US base
- Default address base
- Default ship to shipping country
- No zones except UK

Autofilled UK address and the shipping updated correctly.

**Comment by nhadsall** [comment]
@mikejolley Our customers have this same issue multiple times a month. I think there is a real bug here.

**Comment by mikejolley** [comment]
@nhadsall if you can replicate with a default theme please share.

**Comment by ilchybaby** [comment]
Is this issue resolved?  Our store receives about 30 orders a day, and I get around 5 calls a day from people using chrome saying they have the same issue... not good.

**Comment by mikejolley** [comment]
@claudiulodro @claudiosanches Any luck reproducing this? Still cannot my side. 

https://woothemes.zendesk.com/agent/tickets/534248

**Comment by claudiulodro** [comment]
@mikejolley I haven't really been able to reproduce it with multiple different setups (It may mostly happen in Chrome on Windows or something else like that). Going by the symptoms, it's most likely that the 'change' event listeners aren't consistently getting fired on Autofill (https://github.com/tbosch/autofill-event/blob/master/src/autofill-event.js#L16) and this is why the shipping isn't getting updated. 

We could use the autofill-event polyfill I just linked, or just take the good ideas from that and implement it ourselves if we don't want more dependencies: On 'blur' manually check if the input has changed since last and fire a 'change' event if it has.

**Comment by mikejolley** [comment]
Same, no luck. Even on the clients site, autofill works for me as it should.

I notice we do have some semi-related issues fixed in 2.7 - using BLUR so autofill works when partially typing into a field, and updating to select2 v4 which has better support for autofill. I'm hoping these will help. The polyfill seems to use blur, and a few other posts about this seem to indicate that blur works across browsers. Since 2.7 uses blur I think it may solve it for most.

Let's revisit this after the release of 2.7 if reported again, and when it gets reported again, make sure we know which browser etc is being used. I don't think all are affected.

**Comment by cbejensen** [comment]
This happens to me on a client's website I am working on.

**Browser:** Chrome 60.0.3112.113
**OS:** Windows 10
**WP:** WordPress 4.8.1
**WooCommerce:** 3.1.2

**Plugins**
- FedEx Shipping
- UPS Shipping
- USPS Shipping

The USPS flat rates appear right away (since they're flat rates). FedEx shipping rates do not appear until a full address is entered, but an autofill (even though it does insert a full address) does not trigger this. I have to edit one of the address fields in order to see FedEx rates.

**Comment by MajkieS** [comment]
Reopening this issue. This still happens.

Some customers see wrong shipping prices after filling in the ZIP code, it gets recalculated properly. But as noted above, when customer logs in, it is not every time. Happens rarely, but sometimes does. It doesn't force the checkout to recalculate.

**Comment by bulgaru** [comment]
For all those experiencing the issue, i recommend looking into the classes for the address fields. I noticed the issue when i've rewritten the fields, e.g.:
`$address_fields['state']['class'] = array('uk-width-1-2 uk-width-medium-1-3');`

When doing so, the class **address-field** is removed and is the one that serves as hook for jQuery to catch the change in the field. If you're rewriting the classes, make sure you include it as well, like in the example above:
`$address_fields['state']['class'] = array('address-field uk-width-1-2 uk-width-medium-1-3');`
