### ISSUE TITLE
woocommerce_new_order doesn't seem to fire when creating orders in admin

### ISSUE THREAD

**Issue by indextwo** [woocommerce/woocommerce#11967]
## EXPLANATION OF THE ISSUE

Running WC 2.6.4 under WP 4.6.1, I hooked into `woocommerce_new_order` to update some post_meta when an order is created. This works when a customer makes an order on the front end of the site, but not when staff create a new order in the admin area. The same goes for the `woocommerce_resume_order` hook, which also doesn't seem to be fired.

Is there another hook I should be using for admin-created orders?

## STEPS TO REPRODUCE THE ISSUE

Use the following code to create custom order numbers; they also need these custom order numbers to be searchable, so they're being saved to the post meta. Functions are included in a custom plugin. As mentioned, these work for front-end orders, but not backend/admin-created orders.

	function vnmWooExtend_orderNumberFilter($oldnumber, $order) {
		$orderAccumulator = 1000000;
		$orderNum = (int)$order->id + (int)$orderAccumulator;
		
		return $orderNum;
	}
	
	add_filter('woocommerce_order_number', 'vnmWooExtend_orderNumberFilter', 10, 2);
	
	function vnmWooExtend_storeCustomOrderNumber($orderID) {
		$order = new WC_Order($orderID);
		
		$customOrderID = $order->get_order_number();
		$currentCustomOrderNum = get_post_meta($orderID, '_order_number', true);
		
		if ($customOrderID != $currentCustomOrderNum) {
			update_post_meta($orderID, '_order_number', $customOrderID);
		}
		
		//	Throw in some nonsense meta, just to see if this works without the conditional
		
		update_post_meta($orderID, '_frangle_pangle', 'wolfmama' . $orderID);
	}
	
	add_action('woocommerce_new_order', 'vnmWooExtend_storeCustomOrderNumber', 11, 1);

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://localhost/sharkv4
Site URL: http://localhost/sharkv4
WC Version: 2.6.4
Log Directory Writable: ?
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ?
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8
PHP Version: 7.0.8
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.49.1
OpenSSL/1.0.2e

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ?
fsockopen/cURL: ?
SoapClient: ?
DOMDocument: ?
GZip: ?
Multibyte String: ?
Remote Post: ?
Remote Get: ?

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ?
woocommerce_api_keys: ?
woocommerce_attribute_taxonomies: ?
woocommerce_downloadable_product_permissions: ?
woocommerce_order_items: ?
woocommerce_order_itemmeta: ?
woocommerce_tax_rates: ?
woocommerce_tax_rate_locations: ?
woocommerce_shipping_zones: ?
woocommerce_shipping_zone_locations: ?
woocommerce_shipping_zone_methods: ?
woocommerce_payment_tokens: ?
woocommerce_payment_tokenmeta: ?
MaxMind GeoIP Database: ?

### Active Plugins (3) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.4.5
VNM WooCommerce Extend: by Lawrie Malen – 0.1
WooCommerce: by WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ?

### WC Pages ###

Shop Base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Shark v4
Version: – 0 is available
Author URL: http://www.pixelpudding.com/
Child Theme: ? – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ?

### Templates ###

Overrides: shark/woocommerce/archive-product.php
shark/woocommerce/cart\cart-empty.php
shark/woocommerce/cart\cart-item-data.php
shark/woocommerce/cart\cart-shipping.php
shark/woocommerce/cart\cart-totals.php
shark/woocommerce/cart\cart.php
shark/woocommerce/cart\cross-sells.php
shark/woocommerce/cart\mini-cart.php
shark/woocommerce/cart\proceed-to-checkout-button.php
shark/woocommerce/checkout\form-billing.php
shark/woocommerce/checkout\form-checkout.php
shark/woocommerce/checkout\form-coupon.php
shark/woocommerce/checkout\form-login.php
shark/woocommerce/checkout\form-pay.php
shark/woocommerce/checkout\form-shipping.php
shark/woocommerce/checkout\payment-method.php
shark/woocommerce/checkout\payment.php
shark/woocommerce/checkout\review-order.php
shark/woocommerce/checkout\terms.php
shark/woocommerce/checkout\thankyou.php
shark/woocommerce/content-product.php
shark/woocommerce/content-single-product.php
shark/woocommerce/emails\customer-processing-order.php
shark/woocommerce/emails\email-footer.php
shark/woocommerce/emails\email-header.php
shark/woocommerce/emails\email-order-details.php
shark/woocommerce/emails\email-order-items.php
shark/woocommerce/emails\email-styles.php
shark/woocommerce/emails\plain\admin-cancelled-order.php
shark/woocommerce/emails\plain\admin-failed-order.php
shark/woocommerce/emails\plain\admin-new-order.php
shark/woocommerce/emails\plain\customer-completed-order.php
shark/woocommerce/emails\plain\customer-invoice.php
shark/woocommerce/emails\plain\customer-new-account.php
shark/woocommerce/emails\plain\customer-note.php
shark/woocommerce/emails\plain\customer-processing-order.php
shark/woocommerce/emails\plain\customer-refunded-order.php
shark/woocommerce/emails\plain\customer-reset-password.php
shark/woocommerce/emails\plain\email-addresses.php
shark/woocommerce/emails\plain\email-customer-details.php
shark/woocommerce/emails\plain\email-order-details.php
shark/woocommerce/emails\plain\email-order-items.php
shark/woocommerce/global\breadcrumb.php
shark/woocommerce/global\form-login.php
shark/woocommerce/global\quantity-input.php
shark/woocommerce/global\sidebar.php
shark/woocommerce/global\wrapper-end.php
shark/woocommerce/global\wrapper-start.php
shark/woocommerce/loop\loop-start.php
shark/woocommerce/loop\price.php
shark/woocommerce/loop\sale-flash.php
shark/woocommerce/myaccount\dashboard.php
shark/woocommerce/myaccount\form-edit-account.php
shark/woocommerce/myaccount\form-edit-address.php
shark/woocommerce/myaccount\form-login.php
shark/woocommerce/myaccount\form-lost-password.php
shark/woocommerce/myaccount\form-reset-password.php
shark/woocommerce/myaccount\lost-password-confirmation.php
shark/woocommerce/myaccount\my-account.php
shark/woocommerce/myaccount\my-address.php
shark/woocommerce/myaccount\navigation.php
shark/woocommerce/myaccount\orders.php
shark/woocommerce/myaccount\view-order.php
shark/woocommerce/order\form-tracking.php
shark/woocommerce/order\order-again.php
shark/woocommerce/order\order-details-customer.php
shark/woocommerce/order\order-details-item.php
shark/woocommerce/order\order-details.php
shark/woocommerce/order\tracking.php
shark/woocommerce/single-product\add-to-cart\simple.php
shark/woocommerce/single-product\meta.php
shark/woocommerce/single-product\price.php
shark/woocommerce/single-product\product-image.php
shark/woocommerce/single-product\product-thumbnails.php
shark/woocommerce/single-product\related.php
shark/woocommerce/single-product\sale-flash.php
shark/woocommerce/single-product\share.php
shark/woocommerce/single-product\short-description.php
shark/woocommerce/single-product\tabs\tabs.php
shark/woocommerce/single-product\title.php
shark/woocommerce/single-product\up-sells.php
shark/woocommerce/single-product.php
shark/woocommerce/taxonomy-product_cat.php
shark/woocommerce/taxonomy-product_tag.php
`

**Comment by indextwo** [comment]
I was able to address this by hooking into `woocommerce_process_shop_order_meta` instead (with a single parameter): 

`add_action('woocommerce_process_shop_order_meta', 'vnmWooExtend_storeCustomOrderNumber', 10, 1);`

As far as I can determine, `woocommerce_new_order` is only fired when an order is processed through the checkout. In a lot of instances, staff were creating orders in the wp-admin and assigning them straight to `processing` or `completed`, which meant that hook wasn't doing what I thought it would. Using `woocommerce_process_shop_order_meta` solved it.

**Comment by Dartui** [comment]
You could also try by hooking to `wp_insert_post` hook or `save_post_{$post->post_type}` which should be `save_post_shop_order` for shop orders.

**Comment by indextwo** [comment]
@Dartui I did consider this, but using `woocommerce_process_shop_order_meta` was a one-liner I could add to my code without having to make any other considerations or additional functions.

It was more that it seems a little ambiguous that the `woocommerce_new_order` isn't _actually_ triggered whenever you create a new order; only when someone goes through the checkout.

**Comment by claudiosmweb** [comment]
`woocommerce_new_order` works only on Checkout, but this is already fixed for 2.7.

**Comment by Spreeuw** [comment]
@claudiosanches in 3.1 `woocommerce_new_order` is still not triggered when creating a backend order. As far as I can see the only reliable way to check when an order is created for the first time (hence `woocommerce_new_order`) accross the board (checkout, api, backend) is using `wp_insert_post`, but with CRUD in place I'd rather use something else.
For the record, I also looked at `woocommerce_order_status_changed` and `woocommerce_order_status_pending`, but neither are triggered when an order is created and the status is not actually changed.

**Comment by Spreeuw** [comment]
Looking further into this, it appears that if you create a backend order without explicitly setting the order status, it is set to `draft` (even when it says 'pending' in the UI). If you then save again, it is correctly set to `wc-pending`).

**Comment by Spreeuw** [comment]
@claudiosanches can you look into this?

**Comment by claudiosanches** [comment]
It's created a blank order when you just click in "Create order" button.
That's why created as `draft`.

**Comment by Spreeuw** [comment]
@claudiosanches that's just part of the issue though, but apart from this status, the `woocommerce_new_order` action is simply not triggered at all when creating a backend order (see my [post above](https://github.com/woocommerce/woocommerce/issues/11967#issuecomment-313358318) the one you commented on)

**Comment by Pro777** [comment]
I am having trouble figuring this out too. I have created an action which isn't getting triggered when an admin order is created.

`add_action( 'save_post_shop_order', 'processOfflineOrder', 10, 3 );`

**Comment by nicoladj77** [comment]
@Spreeuw have you found a fix for this? I still don't see the action `woocommerce_new_order` fired when creating an order from the admin. `woocommerce_update_order` is fired but it doesn't have data fro the customer

**Comment by nicoladj77** [comment]
Also, it looks like `woocommerce_new_order` is triggered when I trash a post from the admin.

**Comment by Pro777** [comment]
@nicoladj77 I got this to work when creating an order via the backend `woocommerce_before_order_object_save` This was also triggering for me via a frontend order, so my event handler uses this code:

`if ( ! is_admin() {
			return;
		}` as well.

**Comment by marek-larin** [comment]
The mess of these hooks and the lack of documentation is a joke.

**Comment by AkihitoNarihisago** [comment]
still not firing
