### ISSUE TITLE
highest number not visible in slider

### ISSUE THREAD

**Issue by zegenrijk** [woocommerce/woocommerce#12545]
## EXPLANATION OF THE ISSUE

See this post, it explains the issue: https://wordpress.org/support/topic/highest-number-not-visible/
The developer of that plugin said it's in the core of Woocommerce they are using.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://www.thehighlandpipers.nl
Site URL: http://www.thehighlandpipers.nl
WC Version: 2.6.6
Log Directory Writable: ?
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ?
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.5.35 mod_python/3.5.0- Python/2.7.5
PHP Version: 5.6.26
PHP Post Max Size: 30 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.29.0
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 30 MB
Default Timezone is UTC: ?
fsockopen/cURL: ?
SoapClient: ?
DOMDocument: ?
GZip: ?
Multibyte String: ?
Remote Post: ?
Remote Get: ?

### Database ###

WC Database Version: 2.6.6
: 
woocommerce_sessions: ?
woocommerce_api_keys: ?
woocommerce_attribute_taxonomies: ?
woocommerce_downloadable_product_permissions: ?
woocommerce_order_items: ?
woocommerce_order_itemmeta: ?
woocommerce_tax_rates: ?
woocommerce_tax_rate_locations: ?
woocommerce_shipping_zones: ?
woocommerce_shipping_zone_locations: ?
woocommerce_shipping_zone_methods: ?
woocommerce_payment_tokens: ?
woocommerce_payment_tokenmeta: ?
MaxMind GeoIP Database: ?

### Active Plugins (25) ###

404page - your smart custom 404 error page: door Peter's Plugins
smartware.cc – 2.2

Ultimate Addons for Visual Composer: door Brainstorm Force – 3.16.6
Admin Menu Editor Pro: door Janis Elsts – 2.4.2
Akeeba Backup for WordPress: door Akeeba Ltd – 2.0.3
ALO EasyMail Newsletter: door Alessandro Massasso – 2.9.3
iThemes Security: door iThemes – 5.7.0
Contact Form 7: door Takayuki Miyoshi – 4.5.1
Duplicate Page: door mndpsingh287 – 2.1
Essential Grid: door ThemePunch – 2.1.0.1
Import users from CSV with meta: door codection – 1.9.9.5
Insert Headers and Footers: door WPBeginner – 1.3.3
iThemes Sync: door iThemes – 1.9.0
WPBakery Visual Composer: door Michael M - WPBakery.com – 4.12
MailPoet: door MailPoet – 3.0.0-beta.4
Slider Revolution: door ThemePunch – 5.2.6
WooCommerce Table Rate Shipping by Mangohour: door mangohour – 1.2.1
Ultimate WooCommerce Brands: door MagniumThemes – 1.1.2
Advanced AJAX Product Filters for WooCommerce: door BeRocket – 1.1.6
WOOF - WooCommerce Products Filter: door realmag777 – 1.1.6.1
WooCommerce: door WooThemes – 2.6.6
Yoast SEO: door Team Yoast – 3.8
WordPress Toolbar Editor: door Janis Elsts – 1.2.1
MailPoet Newsletters Premium: door MailPoet – 2.7.2
MailPoet Newsletters: door MailPoet – 2.7.5
YITH WooCommerce Wishlist: door YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ?

### WC Pages ###

Winkelbasis: #23329 - /assortiment/
Winkelmand: #23336 - /winkelmand/
Afrekenen: #23356 - /afrekenen/
Mijn account: ? Pagina niet ingesteld

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: ROYAL - 8theme WordPress theme
Version: 2.7.3
Author URL: http://themeforest.net/user/8theme
Child Theme: ? – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een subthema aan. Zie: Hoe maak je een subthema

WooCommerce Support: ?

### Templates ###

Overrides: royal/woocommerce/archive-product.php
royal/woocommerce/cart/cart-empty.php
royal/woocommerce/cart/cart.php
royal/woocommerce/cart/cross-sells.php
royal/woocommerce/cart/mini-cart.php
royal/woocommerce/checkout/form-billing.php
royal/woocommerce/checkout/form-checkout.php
royal/woocommerce/checkout/form-shipping.php
royal/woocommerce/content-product.php
royal/woocommerce/content-product_cat.php
royal/woocommerce/content-single-product.php
royal/woocommerce/content-widget-product.php
royal/woocommerce/global/breadcrumb.php
royal/woocommerce/global/form-login.php
royal/woocommerce/global/quantity-input.php
royal/woocommerce/global/wrapper-end.php
royal/woocommerce/global/wrapper-start.php
royal/woocommerce/loop/add-to-cart.php
royal/woocommerce/loop/loop-end.php
royal/woocommerce/loop/loop-start.php
royal/woocommerce/loop/no-products-found.php
royal/woocommerce/loop/pagination.php
royal/woocommerce/loop/sale-flash.php
royal/woocommerce/myaccount/form-edit-address.php
royal/woocommerce/myaccount/form-login.php
royal/woocommerce/myaccount/my-address.php
royal/woocommerce/single-product/add-to-cart/simple.php
royal/woocommerce/single-product/product-image.php
royal/woocommerce/single-product/product-thumbnails.php
royal/woocommerce/single-product/related.php
royal/woocommerce/single-product/sale-flash.php
royal/woocommerce/single-product/short-description.php
royal/woocommerce/single-product/tabs/tabs.php
royal/woocommerce/single-product/up-sells.php
royal/woocommerce/single-product-reviews.php
royal/woocommerce/single-product.php

**Comment by mikejolley** [comment]
You're not on the latest stable release.

**Comment by zegenrijk** [comment]
Hello,

I corrected this, see new statusreport:
`
### WordPress Environment ###

Home URL: http://www.thehighlandpipers.nl
Site URL: http://www.thehighlandpipers.nl
WC Version: 2.6.9
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.5.35 mod_python/3.5.0- Python/2.7.5
PHP Version: 5.6.26
PHP Post Max Size: 30 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.29.0
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.9
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (25) ###

404page - your smart custom 404 error page: door Peter's Plugins
smartware.cc – 2.3

Ultimate Addons for Visual Composer: door Brainstorm Force – 3.16.6
Admin Menu Editor Pro: door Janis Elsts – 2.4.2
Akeeba Backup for WordPress: door Akeeba Ltd – 2.0.3
ALO EasyMail Newsletter: door Alessandro Massasso – 2.9.3
iThemes Security: door iThemes – 5.8.1
Contact Form 7: door Takayuki Miyoshi – 4.6
Duplicate Page: door mndpsingh287 – 2.1
Essential Grid: door ThemePunch – 2.1.0.1
Import users from CSV with meta: door codection – 1.9.9.5
Insert Headers and Footers: door WPBeginner – 1.3.3
iThemes Sync: door iThemes – 1.9.0
WPBakery Visual Composer: door Michael M - WPBakery.com – 4.12
MailPoet: door MailPoet – 3.0.0-beta.7.1
Slider Revolution: door ThemePunch – 5.2.6
WooCommerce Table Rate Shipping by Mangohour: door mangohour – 1.2.1
Ultimate WooCommerce Brands: door MagniumThemes – 1.1.2
Advanced AJAX Product Filters for WooCommerce: door BeRocket – 1.1.6
WOOF - WooCommerce Products Filter: door realmag777 – 1.1.6.1
WooCommerce: door WooThemes – 2.6.9
Yoast SEO: door Team Yoast – 3.9
WordPress Toolbar Editor: door Janis Elsts – 1.2.1
MailPoet Newsletters Premium: door MailPoet – 2.7.2
MailPoet Newsletters: door MailPoet – 2.7.5
YITH WooCommerce Wishlist: door YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Winkelbasis: #23329 - /assortiment/
Winkelmand: #23336 - /winkelmand/
Afrekenen: #23356 - /afrekenen/
Mijn account: ❌ Pagina niet ingesteld

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: ROYAL - 8theme WordPress theme
Version: 2.7.3
Author URL: http://themeforest.net/user/8theme
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een subthema aan. Zie: Hoe maak je een subthema

WooCommerce Support: ✔

### Templates ###

Overrides: royal/woocommerce/archive-product.php
royal/woocommerce/cart/cart-empty.php
royal/woocommerce/cart/cart.php
royal/woocommerce/cart/cross-sells.php
royal/woocommerce/cart/mini-cart.php
royal/woocommerce/checkout/form-billing.php
royal/woocommerce/checkout/form-checkout.php
royal/woocommerce/checkout/form-shipping.php
royal/woocommerce/content-product.php
royal/woocommerce/content-product_cat.php
royal/woocommerce/content-single-product.php
royal/woocommerce/content-widget-product.php
royal/woocommerce/global/breadcrumb.php
royal/woocommerce/global/form-login.php
royal/woocommerce/global/quantity-input.php
royal/woocommerce/global/wrapper-end.php
royal/woocommerce/global/wrapper-start.php
royal/woocommerce/loop/add-to-cart.php
royal/woocommerce/loop/loop-end.php
royal/woocommerce/loop/loop-start.php
royal/woocommerce/loop/no-products-found.php
royal/woocommerce/loop/pagination.php
royal/woocommerce/loop/sale-flash.php
royal/woocommerce/myaccount/form-edit-address.php
royal/woocommerce/myaccount/form-login.php
royal/woocommerce/myaccount/my-address.php
royal/woocommerce/single-product/add-to-cart/simple.php
royal/woocommerce/single-product/product-image.php
royal/woocommerce/single-product/product-thumbnails.php
royal/woocommerce/single-product/related.php
royal/woocommerce/single-product/sale-flash.php
royal/woocommerce/single-product/short-description.php
royal/woocommerce/single-product/tabs/tabs.php
royal/woocommerce/single-product/up-sells.php
royal/woocommerce/single-product-reviews.php
royal/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
Well it's fixed in 2.6.9 to my knowledge :)

**Comment by zegenrijk** [comment]
It's not fixed, i just removed my hack and it's show 217 as highest number (at this moment i enabled my hack again to show 218).

Without hack, see attachment:
![knipsel](https://cloud.githubusercontent.com/assets/22585572/21009520/5d2f857e-bd47-11e6-925f-ae5ae755aa78.JPG)

**Comment by mikejolley** [comment]
We round up using CEIL. Maybe you have more hacks in place affecting it :)?
