### ISSUE TITLE
[2.7] Wrong image in gallery zoom with product variations

### ISSUE THREAD

**Issue by dennyf** [woocommerce/woocommerce#13302]
## EXPLANATION OF THE ISSUE

With variable products, when a variation with an image that doesn't exist in the product gallery is selected, the zoom of that image is the one of the main product image.

## STEPS TO REPRODUCE THE ISSUE

1. Create a variable product with a gallery
![img1](https://cloud.githubusercontent.com/assets/901213/23245721/db114b94-f9e2-11e6-8a0d-f392d13fcef1.jpg)
2. Create a variation with an image that doesn't exist in the product gallery. In my example, I have created a variation of color "black" with a black t-shirt
3. Select this variation on the product page
![img2](https://cloud.githubusercontent.com/assets/901213/23245764/2d6dcd36-f9e3-11e6-9e0b-46ff812e5da3.jpg)
4. Zoom the image - the main product image appears in the zoom, instead of the selected one:
![img3](https://cloud.githubusercontent.com/assets/901213/23245772/3e45d4a0-f9e3-11e6-9d29-f5c438939dd8.jpg)

I'm using WooCommerce 2.7 beta 3 with the TwentySixteen theme.

**Comment by mikejolley** [comment]
This was fixed in https://github.com/woocommerce/woocommerce/commit/a06f83ac503c68c5ffa0e72cbcaf93374257b4a5 before beta 3. Maybe you're seeing a cached script since it's patched already.

**Comment by dennyf** [comment]
@mikejolley  I'm still experiencing this issue with the RC - none of the scripts are cached.
