### ISSUE TITLE
Endless loop in WC27 + Subscriptions

### ISSUE THREAD

**Issue by tivnet** [woocommerce/woocommerce#13547]
Got this after pulling WC from the master branch today:

	Fatal error:  Maximum function nesting level of '256' reached, aborting! in wp\wp-includes\functions.php on line 5075
	Stack trace:
	1. {main}() wp\wp-admin\edit.php:0
	2. require_once() wp\wp-admin\edit.php:303
	3. do_action() wp\wp-admin\admin-header.php:97
	4. WP_Hook->do_action() wp\wp-includes\plugin.php:453
	5. WP_Hook->apply_filters() wp\wp-includes\class-wp-hook.php:323
	6. WC_Admin_Assets->admin_scripts() wp\wp-includes\class-wp-hook.php:298
	7. wc_get_order() app\plugins\woocommerce\includes\admin\class-wc-admin-assets.php:235

	8. WC_Order_Factory::get_order() app\plugins\woocommerce\includes\wc-order-functions.php:100
	9. WC_Abstract_Order->__construct() app\plugins\woocommerce\includes\class-wc-order-factory.php:51
	10. WC_Data_Store->read() app\plugins\woocommerce\includes\abstracts\abstract-wc-order.php:109
	11. Abstract_WC_Order_Data_Store_CPT->read() app\plugins\woocommerce\includes\class-wc-data-store.php:119
	12. WC_Data->set_props() app\plugins\woocommerce\includes\data-stores\abstract-wc-order-data-store-cpt.php:94
	13. WC_Order->set_status() app\plugins\woocommerce\includes\abstracts\abstract-wc-data.php:504
	14. WC_Order->maybe_set_date_paid() app\plugins\woocommerce\includes\class-wc-order.php:237
	15. apply_filters() app\plugins\woocommerce\includes\class-wc-order.php:258
	16. WP_Hook->apply_filters() wp\wp-includes\plugin.php:203
	17. WC_Subscriptions_Order::maybe_autocomplete_order() wp\wp-includes\class-wp-hook.php:298
	18. wc_get_order() app\plugins\woocommerce-subscriptions\includes\class-wc-subscriptions-order.php:1035

	19. WC_Order_Factory::get_order() app\plugins\woocommerce\includes\wc-order-functions.php:100
	20. WC_Abstract_Order->__construct() app\plugins\woocommerce\includes\class-wc-order-factory.php:51
	21. WC_Data_Store->read() app\plugins\woocommerce\includes\abstracts\abstract-wc-order.php:109
	22. Abstract_WC_Order_Data_Store_CPT->read() app\plugins\woocommerce\includes\class-wc-data-store.php:119
	23. WC_Data->set_props() app\plugins\woocommerce\includes\data-stores\abstract-wc-order-data-store-cpt.php:94
	24. WC_Order->set_status() app\plugins\woocommerce\includes\abstracts\abstract-wc-data.php:504
	25. WC_Order->maybe_set_date_paid() app\plugins\woocommerce\includes\class-wc-order.php:237
	26. apply_filters() app\plugins\woocommerce\includes\class-wc-order.php:258
	27. WP_Hook->apply_filters() wp\wp-includes\plugin.php:203
	28. WC_Subscriptions_Order::maybe_autocomplete_order() wp\wp-includes\class-wp-hook.php:298
	29. wc_get_order() app\plugins\woocommerce-subscriptions\includes\class-wc-subscriptions-order.php:1035

.. and so on.

Happens when clicked on "Orders" or "Subscriptions" in admin.

Commented out the hook:

    add_filter( 'woocommerce_payment_complete_order_status', __CLASS__ . '::maybe_autocomplete_order', 10, 2 );

to avoid this fatal error...

**Comment by claudiulodro** [comment]
This was issue #13496, and should have been fixed within the last few hours. Can you try pulling master again?

**Comment by tivnet** [comment]
That's my current status, and the issue is not resolved.

    $ git branch -v
    * master 3b9f753 Merge pull request #13545 from kouratoras/patch-1

**Comment by claudiosanches** [comment]
@tivnet can you please try this last Pull Request #13550 ?

**Comment by tivnet** [comment]
@claudiosanches 

`fix-13547` works


    $ git branch -v
    * fix-13547 ff4b79a Status transition hooks should never run when objects are read regardless of status being set.
     master    38afff0 Merge pull request #13516 from woocommerce/fix-13505

**Comment by claudiosanches** [comment]
@tivnet thanks for confirm.
