### ISSUE TITLE
product gallery image size and alignment issues

### ISSUE THREAD

**Issue by HollyKnott** [woocommerce/woocommerce#14380]
I’m posting this here as the last WooCommerce update email indicated new bugs should be posted here, but the GitHub site (which I’m new to) says this forum is not for bugs, so I hope I am posting in the right place…

I build all of my sites with Genesis and Dynamik. Running the newest Woo (3.0.3), and in 3.0, 3.0.1 and 3.0.2, I am experiencing issues with the product gallery image sizes and spacing. One of my customers mistakenly updated Woo on her live site and she's seeing the same issue as described below.

See screenshot here - this is how the product gallery images look using Dynamik and the older (2.x) version of WooCommerce. 3 columns, nicely spaced apart.

http://hollyknottdesign.com/leigh/product-gallery-1.jpg

When I cloned that site as a test site and upgraded WooCommerce to 3.0.1, this is how they appeared - 4 columns instead of 3, all touching each other and too small:

http://hollyknottdesign.com/leigh/product-gallery-2.jpg

Using the code inspector on my customer's live site (still running Woo 2.x), it displays that product gallery as attachment-shop-thumbnail inside a div called thumbnails columns-3.

http://hollyknottdesign.com/leigh/product-gallery-3.jpg

Using the code inspector on my test site, running Woo 3.0.1, it shows it as img.attachment-shop_single.size-shop_single. If I hover the cursor over the main product image above, I get that same reading. It's as if it isn't differentiating between the main image and product gallery images.

http://hollyknottdesign.com/leigh/product-gallery-4.jpg

If I switch the theme to Storefront, running Woo 3.0.1, it shows entirely differently as woocommerce-product-gallery, and with 4 columns.

http://hollyknottdesign.com/leigh/product-gallery-5.jpg

I even removed all custom Woo code (CSS and Functions) and the problem persists.

Also please note that last night someone on the WordPress/Woo forum posted this identical problem. See this link for his screenshots.
https://wordpress.org/support/topic/thumbnail-images-on-single-product-pages-using-browser-scaled-full-size-image/#post-9028815

**Comment by mikejolley** [comment]
As you may have read, 3.0 has a new gallery (which I don't think is enable in your theme) and part of that update involved changing gallery markup. It looks like all that is needed here is a tweak to the existing gallery styling in your theme.

I'm not sure if this is a WooCommerce compatible theme or not (?) but if it is, the author should address it and choose to support the new gallery is desired (https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0).

Otherwise CSS can simply be applied (padding, borders, widths).

**Comment by HollyKnott** [comment]
Thanks for the reply, Mike. I did add that gallery code you linked to above and while it brought back the lightbox functionality, it had no effect on the product gallery thumbnails beneath it. Using code inspector tools, I cannot "see" what CSS applies to them as it seems to differ depending on which theme I use. Sometimes the CSS shows as "img.attachment-shop_single.size-shop_single" which, if I alter it, affects the individual main product image above it.  If I switch the theme to Storefront, the code inspector tells me the CSS is woocommerce-product-gallery, and with 4 columns and I can't figure out how to tell it to display 3 columns. I don't mind altering CSS but it seems like I can't really "see" what the CSS is for those detail images, if this makes sense.

**Comment by mikejolley** [comment]
Gallery columns is filterable, but I don't know if that will fix your spacing issue.

https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-image.php#L24

```
add_filter( 'woocommerce_product_thumbnails_columns', 'custom_woocommerce_product_thumbnails_columns' );

function custom_woocommerce_product_thumbnails_columns() {
return 3;
}
```

**Comment by HollyKnott** [comment]
Thanks very much - will check that out.

**Comment by HollyKnott** [comment]
The columns code didn't work (strange) but I finally did find this CSS and I added some padding and the spacing seems better now:  

`.woocommerce div.product div.images .woocommerce-product-gallery__image:nth-child(n+2) {
    display: inline-block;
    width: 25%;
	padding-right: 25px;
	padding-bottom: 20px;
}
`

**Comment by mikejolley** [comment]
Does your theme maybe have it's own single-product/product-image.php? If so it probably does not have our filter or markup.

**Comment by HollyKnott** [comment]
Not sure, but I'm guessing it doesn't as it's not a Woo theme, per se. It's Dynamik by Cobalt Apps that supports Woo but isn't a shop template.

**Comment by mikejolley** [comment]
The system status report will say - WC > System Status

**Comment by HollyKnott** [comment]
Not seeing anything listed under System Status for single-product/product-image.php. Just the usual Woo pages:  WC pages
Shop base:		#377 - /shop/
Cart:		#378 - /cart/
Checkout:		#379 - /checkout/
My account:		#380 - /my-account/

**Comment by mikejolley** [comment]
Hmm must just be CSS then. The filter only appends a class to the markup; CSS may just not be present for it.

**Comment by mikejolley** [comment]
Closing as this was resolved with CSS

**Comment by stevygee** [comment]
It seems this is actually still an issue. I have Product Thumbnils set to 194x194 with hard crop enabled. WooCommerce loads the full size images in the gallery. Checked and the thumbnail sized image files exist. Tried with another theme, tried deactivating all other plugins, tried regenerating all thumbnails... Nothing.

The only thing that helped was to set in theme functions.php:
```
add_theme_support( 'wc-product-gallery-slider' );
```
Now the proper thumbnail image size gets used. So the problem is restricted to the 'old' gallery.
