### ISSUE TITLE
Attributes not functioning anymore after update.

### ISSUE THREAD

**Issue by jdbaluch** [woocommerce/woocommerce#14824]
### EXPLANATION OF THE ISSUE

The variations no longer show up with the correct attribute names in the product edit page.  They still show up correctly in the store but when you try to add the item to your cart it will throw an error.

### STEPS TO REPRODUCE THE ISSUE

http://yazbeck.com/shop/yazbeck-carbone-wetsuits/
Choose any thickness/lining/size.
add to cart.
ERROR= Invalid value posted for Thickness displays on screen.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://yazbeck.com
Site URL: http://yazbeck.com
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.16 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 512 MB
PHP Time Limit: 500
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.15.4

SUHOSIN Installed: –
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: ugAd5YM5q_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (27) ###

BackupBuddy: by iThemes – 7.1.5.1
AfterShip - WooCommerce Tracking: by AfterShip – 1.6.8
Boxzilla: by ibericode – 3.1.12
Converge Gateway for WooCommerce: by Jacob Davidson – 2.0.0
Comet Cache: by WebSharks
Inc. – 170220

Contact Form 7: by Takayuki Miyoshi – 4.7
Easy Testimonials: by Gold Plugins – 2.2.5
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Google Doc Embedder: by Kevin Davis
Dan Lester – 2.6.2

Groups: by itthinx – 2.1.1
Hide Admin Bar From Non-admins: by Stranger Studios – 1.0
Instagram Feed: by Smash Balloon – 1.4.8
iThemes Sync: by iThemes – 1.174.0
Loco Translate: by Tim Whitlock – 2.0.13
MailChimp for WordPress: by ibericode – 4.1.1
MailChimp for WordPress - Top Bar: by ibericode – 1.2.16
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Ninja Forms reCAPTCHA: by Aman Saini – 1.2.5
Ninja Forms: by The WP Ninjas – 3.0.34.1
Q and A Focus Plus FAQ: by Lanexatek Creations – 1.3.9.7
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Stop Spammers Spam Control: by Keith P. Graham – 6.15
Taxonomy Metadata: by mitcho (Michael Yoshitaka Erlewine)
sirzooro – 0.5

Ultimate Member: by Ultimate Member – 1.3.84
WooCommerce: by Automattic – 3.0.5
Custom Product Tabs for WooCommerce: by YIKES
Inc – 1.5.13

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2659 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.4
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`
</details>

**Comment by peixotorms** [comment]
After 3.0.5 it happens the same to me on multiple sites.
There's also: https://wordpress.org/support/topic/invalid-value-posted-for-size/

**Comment by crabattack** [comment]
I've been having this exact problem since updating too. Waiting for theme updates didn't help either, just had to end up rolling everything back to 3.0.4. Not sure what else to do in the meantime except wait for further updates.

On thing I noticed was that only variable products with custom attributes (attributes created within the listing) were affected. Most, if not all, of my variable products that worked from a set of saved attributes seemed to be fine.

If anyone has any solutions, I'd be all ears.

**Comment by aaronmagnus** [comment]
Also facing this issue. I have a few thousand SKU's so couldn't possible add all the attributes again. I've noticed this only happens on the products with two or more variable attributes for me. Products with a single variable attribute for example, colour, do not face this issue.

**Comment by andersoncreative** [comment]
Also experiencing this issue. Over 500 products affected. Also disabled all plugins and tested with 2017 theme. This has rendered our site useless for days. Any solutions yet?

**Comment by bodyment** [comment]
I am very disappointed to also comment that this issue has affected my businesses dramatically.
When will this be repaired woocommerce?

**Comment by neko** [comment]
I've also had this issue. Quite unlucky tbh.

**Comment by claudiosanches** [comment]
I'm unable to reproduce this issue, can anyone give steps for me try reproduce it?

**Comment by aaronmagnus** [comment]
Claudio, in my case this is how the issue came about:

1. Updated from the last 2.6.X version of Woocommerce straight to 3.0.5 via WP admin. 

2. Go to a product page with > 1 variable attribute. Products with a single variable attribute such as 'Colour' are working as normal. 

3. Select the variation from the two drop-downs, for example - Colour and Frame Finish. Click add to basket. 

4. Message appears "Invalid value posted for Frame Finish"

5. If you click 'Edit Product' and go to the variations tab you can see that the second attribute on all variations has been set to 'Any Frame Finish'. 

See attached screenshots. 

![invalid-value](https://cloud.githubusercontent.com/assets/5787421/25673846/b3307080-3030-11e7-8836-329fd8cec5e7.png)
 
![missing-attributes](https://cloud.githubusercontent.com/assets/5787421/25673860/c3a4670a-3030-11e7-8229-a76b044c011c.png)

**Comment by franticpsyx** [comment]
@claudiosanches I saw this happen earlier today on a dev site updated to 3.0.5 from 3.0.4. Got a warning when I attempted to hit Save in the Attributes tab - I am on the road and won't have access to log files until tomorrow.

In my case the product had 3 attributes, all custom and named Attribute A/B and C. All would appear under the Attributes tab, but the values of Attribute A were not showing up in the created Variations. Saving didn't fix this.

**Comment by jdbaluch** [comment]
Guys the easiest work-around that I've found as of now is to rename the current /woocommerce directory and then do a fresh plugin install of 3.0.4.  Refresh the page and all is well -- at least for me.

**Comment by claudiosanches** [comment]
@aaronmagnus @franticpsyx so the issue is with product custom attribute? Not with global attributes?

**Comment by claudiulodro** [comment]
We've identified the cause of the errors. This issue happens when you have a custom attribute with the same name as a global attribute. We're working on a fix now.

**Comment by claudiosanches** [comment]
Can someone test if is fixed now?
Need to test using: https://github.com/woocommerce/woocommerce/archive/release/3.0.zip

**Comment by mukk85** [comment]
I have applied the patch to my version and am still getting the error. For me, it seems to happen with products with single variation attributes as well.

**Comment by claudiosanches** [comment]
@mukk85 how you applied?
Can you give more details about it?

**Comment by mukk85** [comment]
@claudiosanches I edited the files in the commit and added the code. The line numbers didn't quite match up, but I found where it was supposed to go. There must be some other changes coming to those files as well?

**Comment by claudiosanches** [comment]
@mukk85 please download the package I showed and try with it, so we can be sure if is working or not, thanks.

**Comment by mukk85** [comment]
Ok, but I think you are having a different problem than me. I do not have any global attributes, however my attribute names are probably quite common. Mainly "Size" is the problem but also some products have "Colour".

**Comment by claudiosanches** [comment]
@mukk85 can you help me please?

**Comment by mukk85** [comment]
@claudiosanches I am installing that package now, will let you know results in a few minutes.

**Comment by claudiosanches** [comment]
@mukk85 thank you.

**Comment by mukk85** [comment]
@claudiosanches This did not solve it for me. I am still getting the same error. When I look at the data submitted, I see that the variation_id and product_id being sent is correct.

Using this product: https://musicheals.ca/product/mh-t-shirt-3/

Payload from chrome:
------WebKitFormBoundaryBbcg9cvBNIOFrrg3
Content-Disposition: form-data; name="attribute_size"

Medium
------WebKitFormBoundaryBbcg9cvBNIOFrrg3
Content-Disposition: form-data; name="quantity"

1
------WebKitFormBoundaryBbcg9cvBNIOFrrg3
Content-Disposition: form-data; name="add-to-cart"

119
------WebKitFormBoundaryBbcg9cvBNIOFrrg3
Content-Disposition: form-data; name="product_id"

119
------WebKitFormBoundaryBbcg9cvBNIOFrrg3
Content-Disposition: form-data; name="variation_id"

121
------WebKitFormBoundaryBbcg9cvBNIOFrrg3--

**Comment by claudiosanches** [comment]
@mukk85 this could be related to the plugin you are using to change the attributes display.
Could you please test without that plugin?

**Comment by mukk85** [comment]
@claudiosan Yes, it seems I must use a select element as well now. I have adjusted my code to print the select in a hidden div and modify it with JavaScript when I choose an option. This seems to have fixed that issue.

**Comment by claudiosanches** [comment]
@mukk85 so it was not a plugin? Was it a custom implementation?
Maybe we can check what are it and fix too, so will not have this kind of problem.

**Comment by mukk85** [comment]
No, it wasn't a plugin. This was part of my theme templates. I am using radio buttons instead of a select box. It would be great if it could listen to change events on everything with the data attribute instead of specifically a select box on line 37 of assets/js/frontend/add-to-cart-variation.js

**Comment by claudiosanches** [comment]
Yeah, we could include some support for other elements too, but maybe for 3.1 or 3.2.

**Comment by nathanstiteler** [comment]
I applied and all is working for me

**Comment by claudiosanches** [comment]
@nathanstiteler thank for your feedback.

**Comment by kevin25** [comment]
That is what i told you guys before. I couldn't import products correctly because I had custom attributes. Once i renamed those custom attributes, it worked. Now i applied those patches and it worked again. Great Job, @claudiosanches. Thanks

**Comment by claudiosanches** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/14858

**Comment by crabattack** [comment]
I tried the update via the linked package and am still experiencing the issue, even with all other plugins off and 2017 theme...

**Comment by silicondales** [comment]
@claudiosanches got a client on WooCommerce Bookings who updated themselves to WC 3.0.5 and this raised there for all booking dates, rendering them "not selectable" in single product when add to cart. Investigating at present. Feels like same issue. Will test your update and confirm.

**Comment by silicondales** [comment]
example of how this presents...

![image](https://cloud.githubusercontent.com/assets/17259256/25743283/7652cb2a-318b-11e7-8882-3b5819391d50.png)

**Comment by crabattack** [comment]
My issue is the same as @silicondales posted above.  And as mentioned, it seems that only some variation attributes are affected - those that conflict with existing global attributes.

I suppose I could go through and re-configure all of my attributes to a fixed set of global ones, but that would require a significant amount of time, which is unfortunately in short supply at the moment..

**Comment by silicondales** [comment]
@crabattack there's a fix for this posted above. I'm testing this in staging for this client. The fix on your live site is (probably) revert to WC 3.0.4. I always recommend testing updates in a staging site first. This client has seen why at first hand, unfortunately.

**Comment by crabattack** [comment]
@silicondales yeah, the package above didn't change anything for me, so for now it's 3.0.4. You're absolutely right though, this is why a staging site is key! I let the update move onto the live site too quickly the first time and a customer pointed out the error initially, which was a bit awkward.

**Comment by silicondales** [comment]
yeah I think if yours is on WC bookings and uses the select box, then its the same thing... I will post back here after testing.

**Comment by claudiosanches** [comment]
Let's check what is happening with Bookings.

**Comment by mikejolley** [comment]
@claudiosanches That doesn't look like our Bookings extension. The error is specifically from `add_to_cart_handler_variable` so it's not a bookable product.

It could be related to https://github.com/woocommerce/woocommerce/pull/14938 but I'd think it's much more likely to be an error in the rendering of the select box (passing values which do not match those stored to attributes). Without seeing the code that plugin uses it's impossible to know for sure. The actual validation ran in `add_to_cart_handler_variable` did not change in 3.0.5

**Comment by fjkuypers** [comment]
I am at WC 3.0.6 and have exactly the same problem and behaviour. When I deactivate WPML variations show up again at the backend.

Then I did : Go to WooCommerce > WooCommerce Multilingual Page > Attributes tab > Click “Synchronize attributes and update product variations” at the bottom of the page

No improvement unfortunately.... WMPL still seems to be causing the problem I am afraid...

Some of you may want to look around there if you are running WMPL....

**Comment by ymatt** [comment]
@claudiosanches 
I have updated woo commerce 2.6.x to 3.0.5 and now 3.0.6, but still have the same problem.
And also I tried to add new global variation named test and selected custom variation for global variation test, but the problem still observed. 
I am using wooCommerce for Japan and WP Multibyte Patch plugins in order to support multibyte code. 
I am wondering, if the problem may be related to the Multibyte handling as fjkuypers mentioned. 
Could you check the possibility of the cause.

**Comment by lynn219** [comment]
I cant even get the Variations page to load.

**Comment by fjkuypers** [comment]
@ymatt , can you urn off the WP Multibyte Patch plugin? and see if you then seen the variables back, at the backend?

**Comment by ymatt** [comment]
@fjkuypers , I disabled Multibyte patch plugin  and observed that the variables could not be displayed as you can see it with attached file.  and the attribute was displayed but could not be saved.
![scrshot](https://cloud.githubusercontent.com/assets/4453839/26030420/3ed6c16a-388e-11e7-8c60-ddc3aea470bd.png)

**Comment by fjkuypers** [comment]
@ymatt. Sorry to see no change/fix.  Here stops my knowledge As I got it to work again by stoppoing WPML plugin.Weird is that you can not save yr settings either. Dbase ok?

**Comment by paxjah** [comment]
3.0.6 does not fix the variation/attribute issue. We are still getting it. All plugins up-to-date. No customisations.

Attributes and variation are gone within edit product screen, including both global and non-global attributes.

However all variations are still in database, they just don't seem to be linking. Please see parent and variation exports, as well as system report here - https://drive.google.com/drive/folders/0Bx22mhyUGaBOaFA5V3ZUN3ZObE0?usp=sharing

We tried reverting to 3.0.4, disabling plugin both in .6 and .4, and the usual debug tricks, but these did not fix the issue. I can provide full access to the site, please PM or email me.

**Comment by mikejolley** [comment]
@paxjah If you're talking about endless loading like in that screenshot above your comment it's a plugin conflict or https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x 

3.0.x cannot fix these type of conflicts.

The issue in the original post of this thread was a `3.0.5` only issue and resolved in 3.0.6.

**Comment by paxjah** [comment]
No. I do not have an endless load screen, They are not loading at all, as though I've just set up the product and haven't added any in. However they are still in the database.

Please can you help?

**Comment by mikejolley** [comment]
Can you show a screenshot?

**Comment by paxjah** [comment]
I can indeed! - http://www.awesomescreenshot.com/image/2496331/2223d3822169b66fc60f961c77560ac5

Google drive for details provided before - https://drive.google.com/drive/folders/0Bx22mhyUGaBOaFA5V3ZUN3ZObE0?usp=sharing

**Comment by mikejolley** [comment]
@paxjah Can you do the same for variations tab, and link to a frontend affected product?

**Comment by paxjah** [comment]
Absolutely - https://drive.google.com/file/d/0Bx22mhyUGaBOdjJzZXpFeDlOdzg/view

**Comment by mikejolley** [comment]
I do see the variations in the page source e.g. ID 6841 so those are not missing. Must simply be attributes.

> Attributes and variation are gone within edit product screen, including both global and non-global attributes.

Are the attributes still listed under Products > Attributes?

And are these products syncing anywhere, or being imported? I saw WP-Lister Pro - does this import TO woocommerce, or just away from?

The attributes linked to products are stored as serialised meta data for the most part and the format is quite specific. I'm wondering if these have been corrupted somehow after an import of sorts.

**Comment by SwissAdmin** [comment]
Dear Wordpress & WooCommerce community; we have a problem 😭

First thing first, please excuse my poor english; i am from Switzerland :/

We are already searching for hours for a solution.
Today afternoon we have discovered the exact same problem as described by **"paxjah"**.
I can say with definite that the problem did not exist before the 13.05.2017
So the problem must have occurred in the time span between.

At the moment i don't have any clue on solving the problem but i have noticed some similarities to "paxjah".
We have also installed WP-Lister (eBay) in fact the Lite version (**WP-Lister Lite for eBay Version 2.0.20 (after update)**)
But the Plugin was deactivated since weeks, because we did not have set it up yet.
I do not remember for sure when there was an update released but i have installed it yesterday afternoon. The update process was confirmed always successful but if i remember right somehow the plugin was not removed instantly from the available plugin update list after the update. So even it was now showing the correct version i tried to update twice again but now effect. Strangely some hours later the plugin left by itself the available plugin update list.

**I am not saying that the problem was caused by the update of the (WP-Lister Lite for eBay) but probably it could be.** I don't want to lead you on a false way so investigating in other directions may also lead to the source of this problem.

**I also want to add that the problem does not only affect variable products instead every product with entered attributes. All attributes are now gone @ the product edit page!** 

**But the attributes listed in the wp-backend/products/attributes are still all showing and more confusingly they are also still showing the count of the linked products.**

We are and i am personally in very deep trouble right now.
There are no stored backup available for us because we are currently moving from a shared host to a managed server.

Currently we have in total about 600 very complex electrical products with 5 to 20 attributes each.
We are building our store already since 9 months and it seems all for nothing.
And what will our customers think when they see the messed up store.

**@MikeJolley we would extremely appreciate any help or a solution :)
thank you very much**

**Comment by mikejolley** [comment]
If Lister or any other plugin for that matter has deleted the meta data responsible for attributes, you cannot get it back without a backup... I suggest you see if it's set in the database first. 

Look at the wp_postmeta table in the database, match the post_id to an affected product, and find a row with meta_key `_product_attributes`. See if the value is empty or looks valid. You can post it here once you have an example.

**Comment by SwissAdmin** [comment]
WOW MikeJolley you are very quick responding :)
okey i will try and hope the best please give me some minutes

**Comment by SwissAdmin** [comment]
Hey MikeJolley what do you think about these screenshots?
Do the attributes relating to the product_id 6444 look corrupted to you?
Is it normal that only one line is showed as search result even we had multiple attributes set?
I can not tell by me because i have not very good database knowledge.

https://ibb.co/gBeXLk
https://ibb.co/cCEz0k
https://ibb.co/dNSxmQ

**Comment by SwissAdmin** [comment]
Are these screenshots helpful to you?

Farbe=farbe 

where does the "pa_" come from?

https://ibb.co/jDx2Lk
https://ibb.co/d4C2Lk
https://ibb.co/b1Wwfk

i appreciate your help so much MikeJolley

**Comment by mikejolley** [comment]
My email is on my profile. If you send a login + ftp access I'll look into this in the morning. I'm not certain this is upgrade related yet.

**Comment by SwissAdmin** [comment]
Thanks very much, i have just send you an email.

**Comment by paxjah** [comment]
Good morning @mikejolley !

The global attributes still exist within Products > Attributes.

Both Lister plugin only push to Amazon/ebay, they do not pull.

Could I also please give you access?

**Comment by mikejolley** [comment]
Yes please, email on profile. I'll need to do some debugging to see if the data is there or not.

**Comment by paxjah** [comment]
Thank you so much! I will email you now and warn the client!

**Comment by mikejolley** [comment]
If you have this issue it may be that your attributes are double-serialized (possibly due to bad import).

Running this tool will correct them in bulk https://gist.github.com/mikejolley/3498250299c7cf7b24e973cbbce7a80c Install and go to WC > System Status > Tools > Fix double-serialized attributes

**Comment by SwissAdmin** [comment]
Dear Mr Jolley

I finally have arrived at the office an will be there until today evening 01:00 in the night.
Unfortunately my boss did not accept my request to share the admin credentials.
But as i wrote yesterday i can give you supervised access via TeamViewer; i am ready waiting for you any time. :)

I thankfully have received your last email with the BULK CORRECT TOOL. :)
But i don’t know for sure how i can execute the Tool.
Do i need to paste this code inside a snipped or somehow execute it via phpMyAdmin?
Do i need to execute i once and remove it afterwords or keep it activated for ever?

Furthermore we did not perform any import in the first place.
So it is still not clear to me how this could happen and what the cause was.

kind regards

sincerely
Pascal Steinauer, WEB-DEV

WallboxStore • Bleichestrasse 65 • 8750 Glarus • Switzerland 🇨🇭
Mo. - Fr. 08:00 - 12:00 / 13:00 - 17:00
🚗 info@wallboxstore.ch
🔋 https://wallboxstore.ch/
🔌 +41 55 645 50 50

**Comment by SwissAdmin** [comment]
**Fantastic your plugin (link below) has worked and fixed all the attributes in no time!**
https://gist.github.com/mikejolley/3498250299c7cf7b24e973cbbce7a80c

What is still not clear to me is how this could happen in the first place.
Could you please explain me what plugin or workflow caused this problem?

MikeJolley we are extremely thankful for your excellent help.
Please provide me your PayPal email so we can send you a small donation:)

**Comment by mikejolley** [comment]
@SwissAdmin I'm not certain but I think it could have been an importer? Something double serialising attributes.

**Comment by ymatt** [comment]
@mikejolley I checked the meta_key _product_attributes and it contained multibyte datas the you can see in the following screenshot. when I clicked the meta_value to check its value  then "error in processing request  error code :404  error text : not found" message popped up.
I am not sure what this symptom means.
Could you advise me the way to solve my problem.

![2017-05-17 14 26 38](https://cloud.githubusercontent.com/assets/4453839/26139755/dd71fa66-3b0d-11e7-8369-1128de1f1081.png)

**Comment by mikejolley** [comment]
@ymatt that meta looks fine I think - does not appear double serialised. Make sure you actually have the same issue as OP and not just something about 'attributes'... I'm not sure if multibyte could affect this - possibly if the DB/serialisation cannot handle it.

**Comment by ymatt** [comment]
@mikejolley  Thank you for your advice. Can you reproduce the problem in your environment? Is there any thing that I can help to solve this issue?

**Comment by BrentOzar** [comment]
Same problem here. Tried the double serialized plugin, didn't work either. Redoing all my attributes/variations from scratch. Not a happy camper.

**Comment by mikejolley** [comment]
Why not identify what is the issue before redoing? Just because this issue mentions 'attributes' does not mean it's serialisation. It could quite easy be just a conflict with a plugin, in which case you're wasting your time remaking things.

**Comment by BrentOzar** [comment]
Because my shop has been unusable for a week and I had no idea. I'd been on an overseas trip, came back to find a total lack of sales, and I gotta fix that before I get on a plane again this afternoon.

**Comment by mikejolley** [comment]
Can you pull a value from the DB like they did above? ^

**Comment by BrentOzar** [comment]
No, but if you want a backup of the site before & after the issue for troubleshooting, email me at brento@brentozar.com and I can give you links. (It took me two hours this morning just to troubleshoot the root cause, find this Github issue, try the serialisation plugin, try other fixes, etc) and I just had to cut bait to get back to work.

As big as this is (completely taking down variation sales), this is something that should be a big known issue that customers are alerted about on the 3.0.x series. If there's an open issue this big, we really need a heads up. This cost me real money.

**Comment by mikejolley** [comment]
Core itself does not cause double-serialisation from where I can see, so a warning is not required. We cannot alert folks to issues caused by outside plugins changing data simply because there is no way to know if this occurs, and any non-standard data change would break something..

My email is on my profile; just getting the meta_value of an affected product would help because I can unserialise it myself to see if it's that or not.

**Comment by ymatt** [comment]
@mikejolley  Fix for double-serialized attributes did not work for me as you mentioned.My shop has been shut down since upgrade to 3.0.x.  I am wondering whether I should rebuild all attributes and variations. However am afraid that it isn't  possible to rebuild the attributes because writing attribute did not suceeed. Do you think that someone is working on the fix for our problem?  Otherwise I should rebuild all my shop from scratch.

**Comment by mikejolley** [comment]
I need a txt file or paste of that multibyte value.

**Comment by ymatt** [comment]
@mikejolley  I can't past the multibyte  value for meta_value with  meta_key having _product_attributes.
myphpadmin does not show up meta_value because of error I told you before.
Multibyte may not be the cause of problem.  I could make attributes and variation using multibyte data on my test site that site did not have attributes and variation when updating woo commerce 2.6.x to  3.0.6. So it might be happened on the attribute and variation when version up.
I can email my ftp account and myphpadmin account, if you needed.

**Comment by mikejolley** [comment]
Ill take a look.

**Comment by perkar** [comment]
I have the same issue. All product attributes are still there, somewhere, but they are not visible from the Edit product page. The users can still select and filter on attributes from the front-end.

I have tried to reinstall Woocommerce and ran the double-serialized-plugin, with no success.
I will be happy to provide mor info and/or access to anyone who can help me out here.. Rebuild everything from scratch would take me several weeks.

https://borthittad.se

BR Per

**Comment by mikejolley** [comment]
Not the same issue then is it.

**Comment by perkar** [comment]
Well, I am not sure.. What Paxjah describes is exactly what I am experiencingon my site too:

> Attributes and variation are gone within edit product screen, including both global and non-global attributes.
However all variations are still in database, they just don't seem to be linking. Please see parent and variation exports, as well as system report here - https://drive.google.com/drive/folders/0Bx22mhyUGaBOaFA5V3ZUN3ZObE0?usp=sharing

**Comment by mikejolley** [comment]
If they work on the frontend product forms/pages, it's not an issue with the data AFAIK.

**Comment by perkar** [comment]
Then why is the data gone from the Edit product's page? There seems to be no link between the product and its attributes. But there IS a link, since the user still can filter from the frontend..

**Comment by perkar** [comment]
And now, I am in the situation having to recreate the whole thing (250 products, all with at least 7 attributes/product, for which I don't have a backup) just to get them connected again. That is my real problem. And it came after the latest Woocommerce update.

**Comment by perkar** [comment]
(I am using a plugin called WooCommerce Show Attributes that displays the different attributes/product. That is not working now, of course, since the product lost their attributes)
I'm selling golf balls and every ball have different properties, such as color, hcp, swing speed and so on..

**Comment by mikejolley** [comment]
Can you do what I asked the other user then? Give me the serialised value from the DB so I can see if it's been corrupted.

**Comment by perkar** [comment]
Here is the entire db. Appreciate all help, and is willing to pay if you can help!

[database.zip](https://github.com/woocommerce/woocommerce/files/1022396/database.zip)

**Comment by mikejolley** [comment]
@perkar I cannot import it due to error reading UTF8. Maybe your issue is related to @ymatt  - see if you're running a plugin which would save multibyte chars.

**Comment by ymatt** [comment]
@mikejolley 
I could find plugin that caused the error based on your suggestion.
 https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
I have reported the problem to a plugin developer.

I stopped the plugin and now site is working fine.
Thank you very much.

**Comment by mikejolley** [comment]
Thanks. I'm closing this now because the issues are documented.
