### ISSUE TITLE
Importing category with comma in its name causes woocommerce to create multiple categories

### ISSUE THREAD

**Issue by KrisKorrel** [woocommerce/woocommerce#16192]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add category with a comma in its name. For example 'Chairs, stools and sofas'
2. Assign at least on product to this category
3. Export the products using Woocommerce's import/export feature
4. Import the products again using the same feature

## Expected behavior and actual behavior

When I follow those steps, I see that the following new categories are automatically addded: 'Chairs' and 'stools and sofas'

I was expecting the import functionality to import the products with the category: 'Chairs, stools and sofas'

## Environment

<details>
```
### WordPress Environment ###

Home URL: -
Site URL: -
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.18
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ De MaxMind GeoIP Database bestaat niet
Geolocation zal niet werken. Je kunt het handmatig downloaden en installeren vanaf http://dev.maxmind.com/geoip/legacy/geolite/ naar het pad: . Scrol naar beneden naar "Downloads" en download het bestand "Binary / gzip" naast "GeoLite Country". Vergeet GeoIP.dat.gz niet te decomprimeren en alleen het GeoIP.dat-bestand te uploaden.


### Security ###

Secure connection (HTTPS): ❌Jouw winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Hide errors from visitors: ✔

### Active Plugins (8) ###

Contact Form 7: door Takayuki Miyoshi – 4.8
Nextend Facebook Connect: door Nextendweb – 2.0.2
Nextend Google Connect: door Roland Soos
Jamie Bainbridge – 1.6.1

Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
WooCommerce Remove All Products: door Gabriel Reguly – 1.0.4
WooCommerce: door Automattic – 3.1.1
WooSidebars: door WooThemes – 1.4.3
YITH WooCommerce Wishlist: door YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #64 - /
Winkelmand: #63 - /cart/
Afrekenen: #62 - /checkout/
Mijn account: #61 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.7
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
This is resolved in master and will be supported in 3.2 where you can wrap names in quotes.

**Comment by igama** [comment]
I have WooCommerce Version 3.3.4 and this is still happening. Is it a new bug?

**Comment by mikejolley** [comment]
> you can wrap names in quotes

**Comment by igama** [comment]
Yeah, it was in quotes, just realised I also need to escape the comma with \, to the category field would be "some \,thing\, other" to create a category "some, thing, other"
