### ISSUE TITLE
WooCommerce Variable Product Price not showing!

### ISSUE THREAD

**Issue by RonRahat** [woocommerce/woocommerce#16859]
I have set a price for different variations, if I select a variation, then I don't see any price on my product page or anywhere. 
 My all themes and plugins are updated and I have disabled the theme, all plugins one by one and reactive it. 
If I add something "add to cart" after then its show price again. But if new visitor visitor on my website then they don't see any price.
I'm using WooCommerce free version. 
Please check what new visitor see: https://www.dropbox.com/s/v0fo7dlnvumomie/error.png?dl=0
I have loss many sells for it.
Any solution?

**Comment by mikejolley** [comment]
The price is shown below the title as it does with simple products.

The bottommost price is only shown when variations could have a different price. Example:

<img width="393" alt="2017-09-20 at 13 07" src="https://user-images.githubusercontent.com/90977/30642919-a3c7e08c-9e04-11e7-97b5-7d0f64047f7e.png">

If you're missing the top price, its the theme.

**Comment by RonRahat** [comment]
not that, I have solved the problem, Its javascript minify problem on my theme and i have fixed it.

**Comment by HolgerHahn** [comment]
I have the same problem... i de-activated most  plugins but the  problem persists.
The different variation pictures show up correctly but the prices (eg.10.- 20.- or 30.-do not change...
any help  is well appreciated
![screenshot_2](https://user-images.githubusercontent.com/38418997/38794506-ab697c66-4155-11e8-952a-cdf7f3688da1.jpg)
![screenshot_3](https://user-images.githubusercontent.com/38418997/38794507-ab865804-4155-11e8-95d2-b13e3714c1a0.jpg)

**Comment by bazabi** [comment]
Not sure if anyone can help. I have an issue where on products with several variations at the same price (£4). If I then make one of those variations at a sale price on the product page it then displays as in the screen shot with the sale price displaying as main and the price of all the other variations being struck through (in bottom screenshot). Can anyone help?
![Screenshot from 2020-03-05 16-41-32](https://user-images.githubusercontent.com/53539805/76003686-4e81f580-5f00-11ea-8fa9-e1c8de10c2ab.png)

![Screenshot from 2020-03-05 16-42-08](https://user-images.githubusercontent.com/53539805/76003681-4de95f00-5f00-11ea-9cfa-df5b881d14cb.png)

**Comment by kenhit** [comment]
@HolgerHahn 
It was just a plug in conflict for me... specially with Booster for WooCommerce plug in.
I just disabled it an the issue is resolved.
