### ISSUE TITLE
The cart subtotal is wrong sometimes for inclusive tax. (If tax includes a half penny it is rounded up twice.)

### ISSUE THREAD

**Issue by dantabel** [woocommerce/woocommerce#17158]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. In Settings > Tax > Prices entered with tax : Select **Yes**
2. Set the tax rate to 20% (UK VAT rate) 
3. Create a product with the price £9.99
4. Add the product to cart and visit the cart

## Expected/actual behavior

When I follow those steps, I see...
The sub-total price as £10.00

I was expecting to see...
The sub-total price as £9.99

The tax break down shows the item to be £8.33 + £1.67. I believe that both the tax and the price exclusive of tax are both rounded up after subtraction which creates an extra penny as 0.5 is rounded up for both.
**price input:** 9.99
**tax:** 1.665 rounded to 1.67
**price ex. tax:** 8.325 rounded to 8.33

**Possible Solution:**
Only the tax should be rounded up and the price input minus the tax should be done after rounding.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://dvdclub-wp.dev
Site URL: http://dvdclub-wp.dev/wp
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.1.9-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 4000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.12MB
Database Data Size: 3.10MB
Database Index Size: 1.02MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.06MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.08MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.03MB + Index: 0.02MB
wp_postmeta: Data: 0.31MB + Index: 0.22MB
wp_posts: Data: 0.20MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 29
customize_changeset: 7
nav_menu_item: 12
page: 7
post: 3
product: 21
product_variation: 3
revision: 31
scheduled-action: 38
shop_order: 18
shop_subscription: 12

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
superbook_episode (superbook_episode)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by dantabel** [comment]
I have implementer a quick fix and I'm posting it here in case it helps.

I have added the following to the bottom of `calculate_item_totals()` and something similar to `calculate_item_subtotals()` in `class-wc-cart-total.php`

```
$total_sum = array_sum( array_values( wp_list_pluck( $this->items, 'total' ) ) );
if($total_sum - floor($total_sum) === 0.5):
    $total_sum = floor($total_sum);
endif;
$this->set_total( 'items_total', $total_sum );
```

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/17161

**Comment by dantabel** [comment]
Cool, I can confirm this fixes it for me. Thanks :)

**Comment by lampi87** [comment]
Unfortunately this issue is not fixed for me.
In my scenario I have 3 products, prices are given including 20% VAT:
449,00€, 269,00€ and 149,00€
If I select "Calculate tax on subtotal" the subtotal is 867,01€ including 144,50€ VAT (VAT is correct, subtotal is 1cent above expected)
If I deselect it: Subtotal is 867,00€ including 144,49€ VAT (Subtotal is correct but VAT is wrong)

The fix mentioned by dantabel works for me!

**Comment by janrenn** [comment]
i think that setting the option `woocommerce_tax_round_at_subtotal` on causes discrepancy in `WC_Cart_Totals` class because subtotal without tax is rounded on every item despite setting above, see lines 704+705 of the class:

`
$this->set_total( 'items_subtotal', array_sum( array_map( 'round', array_values( wp_list_pluck( $this->items, 'subtotal' ) ) ) ) );
$this->set_total( 'items_subtotal_tax', array_sum( array_values( wp_list_pluck( $this->items, 'subtotal_tax' ) ) ) );
`
