### ISSUE TITLE
Change variation, hover zoom image is always the default one

### ISSUE THREAD

**Issue by cvmh** [woocommerce/woocommerce#17403]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

The problem is reproducible in any variable product with different images for each variation.
Change variation product, pass cursor hover the product image

## Expected/actual behavior

When I follow those steps, I see the default image

I was expecting to see the variation image

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://preprod.webcom-lesite.com
Site URL: http://preprod.webcom-lesite.com
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.58 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wpcvmh_
MaxMind GeoIP Database: ✔
Total Database Size: 169.32MB
Database Data Size: 125.39MB
Database Index Size: 43.93MB
wpcvmh_woocommerce_sessions: Data: 8.02MB + Index: 0.13MB
wpcvmh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpcvmh_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpcvmh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpcvmh_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpcvmh_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpcvmh_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpcvmh_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpcvmh_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpcvmh_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpcvmh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpcvmh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpcvmh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpcvmh_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpcvmh_aws_index: Data: 8.52MB + Index: 0.00MB
wpcvmh_commentmeta: Data: 0.02MB + Index: 0.03MB
wpcvmh_comments: Data: 0.02MB + Index: 0.09MB
wpcvmh_ewwwio_images: Data: 1.52MB + Index: 1.75MB
wpcvmh_facetwp_index: Data: 2.52MB + Index: 3.03MB
wpcvmh_links: Data: 0.02MB + Index: 0.02MB
wpcvmh_options: Data: 7.13MB + Index: 1.23MB
wpcvmh_postmeta: Data: 70.59MB + Index: 26.34MB
wpcvmh_posts: Data: 16.25MB + Index: 4.95MB
wpcvmh_redirect_produit: Data: 2.10MB + Index: 1.76MB
wpcvmh_termmeta: Data: 0.14MB + Index: 0.17MB
wpcvmh_terms: Data: 0.11MB + Index: 0.13MB
wpcvmh_term_relationships: Data: 7.36MB + Index: 3.50MB
wpcvmh_term_taxonomy: Data: 0.17MB + Index: 0.14MB
wpcvmh_usermeta: Data: 0.05MB + Index: 0.03MB
wpcvmh_users: Data: 0.02MB + Index: 0.05MB
wpcvmh_yarpp_related_cache: Data: 0.09MB + Index: 0.13MB
wpcvmh_yoast_seo_links: Data: 0.39MB + Index: 0.11MB
wpcvmh_yoast_seo_meta: Data: 0.09MB + Index: 0.00MB

### Post Type Counts ###

acf: 8
attachment: 11679
customize_changeset: 6
custom_css: 1
cvmh_slideshow: 3
et_pb_layout: 47
flamingo_contact: 5
flamingo_inbound: 21
kwlogos: 9
logocarousel: 4
nav_menu_item: 119
page: 19
post: 80
product: 1945
product_variation: 6156
project: 8
revision: 752
shop_order: 11
testimony: 10
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ❌Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (29) ###

Advanced Custom Fields: Repeater Field: par Elliot Condon – 2.0.1
Advanced Custom Fields: par Elliot Condon – 4.4.12
Advanced Woo Search - !!! Modifié !!!: par ILLID – 1.25 – Not tested with the active version of WooCommerce
Contact Form 7 Conditional Fields: par Jules Colle – 1.3.4
Contact Form 7: par Takayuki Miyoshi – 4.9
Cookie Notice: par dFactory – 1.2.39
Simple Slideshow: par CVMH solutions – 1.2.14
Easy SwipeBox: par Leonardo Giacone – 1.1.0
FacetWP - Facet Stack: par David Cramer – 1.1
FacetWP: par FacetWP
LLC – 2.9.3

Flamingo: par Takayuki Miyoshi – 1.7
Logo Carousel: par Sleepless Developers – 1.7.4
Loco Translate: par Tim Whitlock – 2.0.16
Monarch Plugin: par Elegant Themes – 1.3.22
Regenerate Thumbnails: par Alex Mills (Viper007Bond) – 2.3.1
Widget Options: par Phpbits Creative Studio – 3.4
Woocommerce Bulk Attribute Manager: par Varun Sridharan – 2.2.1 – Not tested with the active version of WooCommerce
Woocommerce CSV import attributes: par Allaerd Mensonides – 3.2.3 – Not tested with the active version of WooCommerce
Woocommerce CSV import custom fields: par Allaerd Mensonides – 3.0.1 – Not tested with the active version of WooCommerce
Woocommerce CSV import variable products: par Allaerd Mensonides – 3.1.5 – Not tested with the active version of WooCommerce
Woocommerce CSV Import: par Allaerd Mensonides – 3.3.6 – Not tested with the active version of WooCommerce
WooCommerce: par Automattic – 3.2.1
Yoast SEO: par L’équipe Yoast – 5.7
WP-PageNavi: par Lester 'GaMerZ' Chan – 2.92
WP Rocket: par WP Media – 2.10.7
Search Keyword Redirect: par Nick Pelton – 1.0
WP Sitemap Page: par Tony Archambeau – 1.6
YARPP - Yet Another Related Posts Plugin: par Adknowledge – 4.4
YITH Woocommerce Request A Quote Premium: par YITHEMES – 1.7.7 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base boutique: #210 - /notre-catalogue/
Panier: #177 - /panier/
Commande: #178 - /commande/
Mon compte: #179 - /mon-compte/
Terms and conditions: ❌ Page non définie

### Theme ###

Name: Webcom
Version: 1.0
Author URL: https://www.agence-web-cvmh.fr/
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.84
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/archive-product.php
Divi-child/woocommerce/content-product.php
Divi-child/woocommerce/loop/loop-end.php
Divi-child/woocommerce/loop/loop-start.php
Divi-child/woocommerce/single-product/product-image.php
Divi-child/single-product.php

`
</details>

**Comment by cvmh** [comment]
I fixed it in assets/js/frontend/add-to-cart-variation.js with:
line 555: + $product_img_zoom  = $product_img_wrap.find( '.zoomImg' );  
line 577: + $product_img_zoom.wc_set_variation_attr( 'src', variation.image.full_src );
line 594: + $product_img_zoom.wc_reset_variation_attr( 'src' );

**Comment by mikejolley** [comment]
This is also fixed in master/3.2.2

**Comment by sushiguru** [comment]
I've tried adding the 3 lines above but this fix isn't working for me, neither can I see master/3.2.2 to download the whole branch for testing - can you advise how this can be fixed?

**Comment by DarrenJamieson** [comment]
This hasn't been fixed. I'm using 3.2.2 here and the error is still happening - http://oilstore.engageweb.co.uk/product/mobil-dte-22-2/

When you select the product variation it still shows the original image on the rollover.

**Comment by mikejolley** [comment]
Can you rule out the theme? I'm looking at the dummy content locally with the same setup and no bugs.

**Comment by mikejolley** [comment]
Ah I see it. The dummy content has a 'gallery' of the same images. Looks like the logic is different when there is no gallery.

**Comment by cvmh** [comment]
@sushiguru you must reminify the javascript file too.
Sorry for the patch I can't find how and where suggest one

**Comment by DarrenJamieson** [comment]
Thanks for looking at this Mike - shall I leave it with you?

**Comment by mikejolley** [comment]
Fix is here https://github.com/woocommerce/woocommerce/pull/17520

**Comment by gthompson-sl** [comment]
Thanks @cvmh and @mikejolley - confirm fix works for me now I've added the minified js. Ace.
