### ISSUE TITLE
Coupon Discount Free Shipping Error

### ISSUE THREAD

**Issue by SarahJee** [woocommerce/woocommerce#17462]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a free shipping option for order over $150
2. Create a coupon for 50% off
3. Use coupon so order is under $150 (thus should not qualify for free shipping)
4. Not that free shipping still applies. 

## Expected/actual behavior

When I follow those steps, I see...
Shipping is still free despite Final order value being under min purchase required for Free Shipping 

I was expecting to see...
Standard (not free) shipping should be applied after coupon brings final order value under $150

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://andthestore.com.au
Site URL: https://andthestore.com.au
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 15.95MB
Database Data Size: 9.77MB
Database Index Size: 6.18MB
wp_woocommerce_sessions: Data: 1.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.14MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.08MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.08MB + Index: 0.20MB
wp_postmeta: Data: 4.42MB + Index: 4.56MB
wp_posts: Data: 1.13MB + Index: 0.39MB
wp_social_users: Data: 0.02MB + Index: 0.02MB
wp_termmeta: Data: 0.06MB + Index: 0.06MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 0.20MB + Index: 0.13MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 0.13MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 929
blocks: 38
featured_item: 8
nav_menu_item: 33
page: 12
post: 25
product: 241
product_variation: 765
revision: 12
shop_coupon: 8
shop_order: 63
shop_order_refund: 1
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (12) ###

ManageWP - Worker: by ManageWP – 4.2.25
Contact Form 7: by Takayuki Miyoshi – 4.9
Instagram Feed: by Smash Balloon – 1.5
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1
WooSidebars: by WooThemes – 1.4.3
WordPress Importer: by wordpressdotorg – 0.6.3
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: #3563 - /terms-conditions/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.9
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php version 3.0.0 is out of date. The core version is 3.2.0
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.2.0
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php version 2.6.0 is out of date. The core version is 3.2.0
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.2.0
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
```
</details>

**Comment by willgorham** [comment]
Should be fixed in #17364 coming out with WC 3.2.2

**Comment by mikejolley** [comment]
^

**Comment by torrelasley** [comment]
We are running v3.2.6 and this is still an issue. The steps to reproduce provided by @SarahJee are still valid to recreate the error, or you can also take the following steps:

1. Configure WooCommerce to offer free shipping with "a valid free shipping coupon".
2. Create a "freeship" coupon that offers free shipping for orders over $200
3. Create a "100off" coupon that offers a $100 fixed cart discount.
4. Add $250 worth of products to the cart.
5. Apply the "100off" coupon to discount the cart down to $150
6. Apply the "freeship" coupon.

Free Shipping is allowed even though the order is under the $200 minimum. The order in which you apply the coupons doesn't matter either, so you could swap steps 5 and 6 and it would still allow for free shipping.

<img width="452" alt="screen shot 2018-01-22 at 10 40 01 am" src="https://user-images.githubusercontent.com/521586/35229162-b5264324-ff60-11e7-99b4-78b9e18c5bbd.png">
