### ISSUE TITLE
Variation attributes disappear when WP is upgraded to 4.9

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#17775]
Originally reported on [trac](https://core.trac.wordpress.org/ticket/42593).

When upgrading to WP 4.9, if a product's variations have attributes of a certain format the attributes get unset.

To reproduce:
1. Start on [WP 4.8.3](https://wordpress.org/download/release-archive/)
2. Create a variable product
3. Add a custom attribute to the product named `Size/Style` with `1" | 2" | 3"` for the values field. Use the attribute for variations.
<img width="839" alt="screen shot 2017-11-17 at 11 43 59 am" src="https://user-images.githubusercontent.com/7317227/32965970-2dd68e44-cb8d-11e7-924e-9e8d07f187d0.png">

4. Create variations 
<img width="844" alt="screen shot 2017-11-17 at 11 44 17 am" src="https://user-images.githubusercontent.com/7317227/32965976-31cfb570-cb8d-11e7-863f-680c4191e48a.png">

5. Upgrade WP to 4.9
6. Observe variations are unset
<img width="843" alt="screen shot 2017-11-17 at 11 44 49 am" src="https://user-images.githubusercontent.com/7317227/32965984-35a02586-cb8d-11e7-9a16-3128a32a3895.png">

7. Downgrade WP to 4.8
8. Observe variations are set again

This only seems to happen when the attribute has a `/` in the name and the values have `"` in them. It does not happen for term-based attributes.

**Comment by mikejolley** [comment]
This is due to some changes in `sanitize_title_with_dashes`. See https://github.com/WordPress/WordPress/commit/98995d46d1059a54b49136ea56e7d8d9c6d11ee1

Before, the attribute's meta key would have been:

`attribute_sizestyle`

As of 4.9, this is sanitized to:

`attribute_size-style`

**Comment by claudiulodro** [comment]
Option 2 can just be a copy+paste of `sanitize_title_with_dashes` from pre-4.9 can't it?

**Comment by ajgw** [comment]
Hi Claudio, hi Mike, this affects not only attributes with dashes. I found just on my site were I had this as attributes:

- 30x60 cm
- 40x80

and tried to add a 30x30 cm to it. I was not able to save this as variation as Claudio describes. I am on 4.9 too.

**Comment by BrentOzar** [comment]
Affected us with these attributes:

February 14-16, 2018 Online | May 1-3, 2018 Online | August 1-3, 2018 Online | November 20-22, 2018 Online

**Comment by mikejolley** [comment]
@ajgw it's the attribute name, not the attributes themselves that breaks.

**Comment by ajgw** [comment]
No Mike,
I had created a variable product earlier with few variations. I my case after upgrading to WP 4.9, I am not able to add another variation to that product. I can save a attribute, but be not able to submit that attribute to a new variation. 

![bildschirmfoto 2017-11-18 um 13 59 08](https://user-images.githubusercontent.com/3390880/32980547-b9731b44-cc68-11e7-92bc-5b1c334acd6c.png)

![bildschirmfoto 2017-11-18 um 14 00 10](https://user-images.githubusercontent.com/3390880/32980559-dc5eb5e6-cc68-11e7-8687-7b4c56c0aa9f.png)

In case of saving with this variation setting (any printsize), product can not be purchased by customer.

**Comment by mikejolley** [comment]
I can't tell what you're doing there. Does that new variation have a price etc? As it's 'any' it will take priority over all others.

Not sure this is the same issue.

**Comment by ajgw** [comment]
OK, lets explain it a bit more:

1. have a variable product created with WP 4.8 in past
2. edit product and add a attribute for use as variation - this step is optional and does not affect step 3
3. add variation, select _any_ attribute, input price and other settings and save
4. attribute is not saved to new variation?!

Product is purchasable but at price of new created variation – all other prices ignored (this was my fault in previous postm because I had no price saved – sorry).

Well, it seems that this is another bug and not related to what Nicola wrote. Creating a new attribute name/term is not the reason, why variations do not save attributes with them. Sorry.

**Comment by ajgw** [comment]
Beside, creating a new variable product with custom attributes is not affected by this bug.

**Comment by mikejolley** [comment]
Got it; the attribute has somehow become uppercase. Looking - this seems related to 4.9 also.

**Comment by ajgw** [comment]
Creating new variations with "Create variations from all attributess" script instead works fine. All new variations are saved in this case.

**Comment by mikejolley** [comment]
Ok, may want to hold off making new ones because a fix for this may invalidate the new ones. Something is making the meta key `attribute_Printsize` instead of `attribute_printsize`

**Comment by ajgw** [comment]
OK

**Comment by mikejolley** [comment]
@ajgw that one is for your issue ^ Not the same as the main issue in this thread.

**Comment by ajgw** [comment]
You are right – I saw it. Thanks.

**Comment by mensmaximus** [comment]
@mikejolley Imho your suggestion No.3 'We code an update routine of some sort. Not sure how large this would be.' is the best. Because the change in WP 4.9 is likely to stay forever transforming the affected attributes has to be done only once. No template modifications necessary and no parallel sanitazing needed. New attributes will follow the WP 4.9  naming and don't need any additional attention.

**Comment by mikejolley** [comment]
Fix for the main issue is here https://github.com/woocommerce/woocommerce/pull/17784

**Comment by mensmaximus** [comment]
Don't we need to deal with attribute terms as well? Think about an attribute named 'Capacity/Scope' with terms 1/2', '1/4' and '3/4'. Prior to WP 4.9 the term slugs would be 12, 14 and 34. Starting with WP 4.9 the slugs become 1-2, 1-4 and 3-4. The fix cares about the attribute 'Capacity/Scope' but not the terms. Doesn't it?

**Comment by mikejolley** [comment]
That wasn't in the report but probably, I'll check.

**Comment by mikejolley** [comment]
The terms are good; we don't sanitise.

**Comment by claudiulodro** [comment]
@mensmaximus this bug doesn't happen with term-based attributes, so they don't need fixing. The slug for a term doesn't change once it's saved, so we're not going to get a mismatch.

**Comment by scrobbleme** [comment]
We got the problem with &
![image](https://user-images.githubusercontent.com/504835/33129313-c7a7c9ba-cf8f-11e7-82db-5f846bfb10c4.png)

**Comment by whatevs-already** [comment]
WC support on chat told me this issue would be fixed in WC 3.2.5 but I just updated and issue is still there. If I correctly set the variation to the correct Design & Color and hit "save" it goes back to "any design" and "any color" the issue that started after WP 4.9 update. Am I missing something I should be doing different? Thanks.

![screenshot_1566](https://user-images.githubusercontent.com/33436555/33150293-a1847b82-cf87-11e7-9688-564f113fcfad.jpg)

**Comment by whatevs-already** [comment]
Wait... hold the drama... the issue IS fixed. I just need to delete the faulty variation then re-add... and the issue is solved. Apologies, ignore above, feel free to delete or ask me to.

**Comment by Roedtan** [comment]
Hi Guys,
I am still experiencing this same issue with WP version 4.9.4 . Any idea how to resolve it?
