### ISSUE TITLE
Setup wizard: broken link / formatting in Payment step description

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce#17854]
The "Additional payment methods" link "admin.php?page=wc-addons&view=payment-gateways" just falls back to "admin.php?page=wc-addons" because that view doesn't exist — should be "payment_gateways".

Also, after https://github.com/woocommerce/woocommerce/pull/17609, the HTML is actually escaped (screenshot from https://github.com/woocommerce/woocommerce/pull/17738):

![](https://user-images.githubusercontent.com/11487924/32900366-4b97a22e-cabb-11e7-87bc-a183b57456a4.png)

(Not sure if this would be in scope for changes to this page underway in https://github.com/woocommerce/woocommerce/pull/17738, or if it warrants a separate PR.)

**Comment by claudiulodro** [comment]
I think it should be fixed in #17738 because we shouldn't merge the PR if there are known bugs in the changes.

cc @v18

**Comment by mikejolley** [comment]
This is already fixed in master, that PR is just not in sync.

**Comment by dechov** [comment]
👍 The URL is still incorrect but I think we'll take care of it in https://github.com/woocommerce/woocommerce/pull/17738.
