### ISSUE TITLE
'Used for variations' not ticked automatically when importing variable products and attributes.

### ISSUE THREAD

**Issue by andykeith** [woocommerce/woocommerce#19645]
Possibly fixed in #19414. 

Steps to reproduce:

1. Download the CSV file from here: https://www.dropbox.com/s/ed7tfolnydac9g2/csv_import_bug.csv?dl=0
2. Run the WooCommerce Product Importer, select this file.
3. Import products.
4. Edit the imported variable product 'Leather Boot'

Under Attributes, 'Used for variations' is unticked and under Variations, none are listed.

When I tick 'Used for variations', then re-save, the variations appear.

Documentation indicates it will be set automatically when importing attributes:
https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#general-csv-guidelines

Tested in blank WordPress 4.9.5 install using WC 3.3.4. Storefront theme, no other plugins active.

**Comment by kloon** [comment]
Does not look like you have a attribute_data:ATTRIBUTE NAME column on the parent product, in that column it takes a pipe separated value which represents the following values `position | visible | variation` the third option should contain a `1` to make it enable variations on the attribute.

See https://docs.woocommerce.com/document/product-csv-import-suite-column-header-reference/#section-3 for more details.

Best is to setup your products in your store and then do an export and then use that file as a reference to make changes on before importing.

**Comment by andykeith** [comment]
Hi, I’m not using the Product CSV Suite extension, I’m using the default WooCommerce product importer. I did ser that documentation but assumed it wasn’t relevant as it was for the premium add-on.

**Comment by claudiosanches** [comment]
@andykeith this should be fixed in https://github.com/woocommerce/woocommerce/pull/19414 already.

**Comment by andykeith** [comment]
Yes, seems to be fixed now. Thanks.

**Comment by ivanovevgeny** [comment]
Looks like bug not fixed yet.

I try to import variative products, as a result, the option "Used for variations" is not set for the attribute.
![image](https://user-images.githubusercontent.com/8840414/39883851-74d9ec08-54a1-11e8-9ab4-92c16d65e446.png)

The list of variations is empty. 
![image](https://user-images.githubusercontent.com/8840414/39883756-3953b42a-54a1-11e8-830b-de854b19f16f.png)

If i set an option "Used for variations" in the attribute, then go to the variations, then variations exists, but the options values are not selected.
![image](https://user-images.githubusercontent.com/8840414/39883952-b8520e2a-54a1-11e8-81d5-2f2c6ff5e3c3.png)

But variations create with right attributes
![image](https://user-images.githubusercontent.com/8840414/39884010-ea5b889c-54a1-11e8-8c4f-915d74d8823e.png)

I also tried to create an attribute first, then manually create a product with variations with this attribute, and then perform the import, but is the same result.

I use the built-in import, version 3.3.5.
![image](https://user-images.githubusercontent.com/8840414/39884059-0c19d948-54a2-11e8-9fbf-4ba914b8d3a5.png)

**Comment by ivanovevgeny** [comment]
@kloon can you check/reopen this issue?

**Comment by kloon** [comment]
Did you test this with the new Release Candidate version of WooCommerce 3.4? it was confirmed fixed by the person who opened the issue there.

**Comment by ivanovevgeny** [comment]
@kloon can you check/reopen this issue?

**Comment by mikejolley** [comment]
The issue with this CSV is that the parent has a global attribute called SIZE and the variations have a local attribute called SIZE. Missing values in the global column.

**Comment by mikejolley** [comment]
No, in the CSV from the original poster there was a mixture. Nothing has to be pre-made.

**Comment by Slatty84** [comment]
I know this is closed but what was the solution for @ivanovevgeny ? I am having the same issue but I have Woo 3.5.4 and WordPress 5.0.3 . I am also not understanding what is wrong with his CSV file.

**Comment by sheikhrehman** [comment]
Have you found a solution for CSV import suite?

**Comment by josemiMontredo** [comment]
Solution?

**Comment by magluca** [comment]
Also looking for a solution here. I experience that same as @ivanovevgeny.

**Comment by Slatty84** [comment]
I finally got mine to work by using the "|" symbol to separate my options, instead of the "," that was used in "41,42". A  CSV is a file that is supposed to be separated by commas so it makes sense that something else should be used instead for an item in the same cell, however I am sure I noticed documentation somewhere that said it should work for either commas or pipe "|". Doing this resolved my issue hopefully this helps.

**Comment by lu-ka** [comment]
Stumbled upon this issue whilst trying to auto-classify product variations with images. The edit product screen showed correct variations and images, yet in the selections in the shop loaded the base image.

Figured my import was improperly formatted so I tried various approaches until I realized the attributes weren't used for variations.

Considering this issue I went another route: traced the option in the code to the point where woocommerce decides whether to mark an attribute as variation or not
https://github.com/woocommerce/woocommerce/blob/3ea8162cff36bcb2cf46afbe150d55d9e9878bfa/includes/import/abstract-wc-product-importer.php#L515

When I disable (comment out) the parent attribute's variation status check it seemingly works fine, except it clones the attributes for every subsequent import.

I'll trace this further, later on, to confirm the above being true.

**Comment by Camzilla** [comment]
The documentation about which columns is required to get _variations_ to work properly feels somewhat lacking..

Had this issue too. After experimenting and manually setting the right values in wordpress, then exporting variations you kinda get some clues.

I only got the variation csv import working properly when the the following columns all exist with values:
```
Attribute 1 name
Attribute 1 value(s)
Attribute 1 visible
Attribute 1 global
```
If you check @ivanovevgeny excel you have omitted a "1" on variation for `Attribute 1 visible`. Which in my theory would have fixed the issue if set to "1". If you're still having issues make sure to delete all variations and re-import them (also, on a side note: updating variations dont seem to work very well.. You're better off deleting all variations and re-importing them with the updated values).

![image](https://user-images.githubusercontent.com/7138189/64565651-dbfdd780-d319-11e9-9ce7-4e2892045b8e.png)

Hope that helps someone!

**Comment by thomasmalley** [comment]
Agreed @Camzilla 

The [Documentation](https://docs.woocommerce.com/document/product-csv-import-suite-importing-product-variations/) ist somewhat lacking & misleading. 

The [provided Sample file](https://docs.woocommerce.com/wp-content/uploads/2017/09/woocommerce-sample-products.csv) contains only these columns: 
```
attribute:Color
attribute_data:Color
attribute:Size
attribute_data:Size
```

But for Importing these Columns are definitly needed to properly assign the Values: 

```
Attribute 1 name
Attribute 1 value(s)
Attribute 1 visible
Attribute 1 global
```

The [Column Header Reference](https://docs.woocommerce.com/document/product-csv-import-suite-column-header-reference/#section-3)  is useless for importing these values since it just doesn't work properly.

**Comment by appoll** [comment]
Issue still present 10.02.2020. Can someone please point out to a working csv sample? @kloon @mikejolley

**Comment by kloon** [comment]
A working CSV can be found [here](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv)

**Comment by pumka** [comment]
We had the same problem and the fix from [#19414](https://github.com/woocommerce/woocommerce/pull/19414) didn't work for us. We found it was so because we have multiple attributes with the same label ("Color"), so the search for attribute by label returned a wrong one, which then couldn't be matched to the existing attribute of the product.
Our fix was using the attribute slug instead of label in the CSV as the code is actually searching by both the label and the slug. Though I believe WooCommerce code could be improved for handling such situation by searching attributes by label among product's existing attributes only.

**Comment by Camzilla** [comment]
@pumka I also noticed I had an inconsequent in my cvs that was messing with my imports. I had one attribute named "Color" while in the variables it was name "Available color".. Your comment helped me find the issue! Thanks! :joy: Double check your attribute names ppl!

**Comment by vilm725** [comment]
Hi everyone 👋🏼

Sorry but I've the sam problem ... The list of variations is empty and "Used for variations" is not set for the attribute 😡🔥 I have filled in the right attributes with the right values :

![img](https://user-images.githubusercontent.com/64069744/81070553-ae3a5400-8ee3-11ea-84e3-b9771fe61cc5.png)

Blue : variable product
White : variation product

Please, have you solved this problem ? If someone has found a solution, can they contact me?

**Comment by aficiomaquinas** [comment]
I'm stuck with the same situation. I spent weeks to get my CSV ready, even made a script to populate the parent attributes automatically from the child products, but for some reason the variations are not associated with the variable (parent) products when I import the CSV. All my attributes are global.

**Comment by vilm725** [comment]
Hi 👋🏼 I've succesfuly import my CSV with 150 products. I'm going to post a solution to show how I did it : [https://github.com/woocommerce/woocommerce/issues/26380](https://github.com/woocommerce/woocommerce/issues/26380)

By any chance, what script are you using to auto-complet your CSV ? A python script ?

**Comment by aficiomaquinas** [comment]
Hello @vilm725, I ended up using the [CSV Import Suite](https://woocommerce.com/products/product-csv-import-suite/).

I could not make the regular import work. After a lot of days my conclusion is that there must be a WooCommerce bug somewhere, because sometimes my imports work and sometimes they don't using exactly the same CSV. If I import all my variable products, then the variations and the simple products at the end everything works, but if i import my variable products, then the simple and at the end the variations it doesn't.

Although I understand WooCommerce staff about their automated testing, I'm afraid there must be something in their tests that is not being covered.

[I wrote a node script](https://github.com/aficiomaquinas/ttamayo-lista-attributes-csv) to transform the columns with the regular import format to the Product CSV Import Suite format, populate the default product with the cheapest variation, automatically fill the variable product possible variations from all the variations in the CSV if the current attribute is used for variations, change the columns name with the attribute's name and remove all columns with a header name that are not part of the import schema.

**Comment by vilm725** [comment]
> Hello @vilm725, I ended up using the [CSV Import Suite](https://woocommerce.com/products/product-csv-import-suite/).
> 
> I could not make the regular import work. After a lot of days my conclusion is that there must be a WooCommerce bug somewhere, because sometimes my imports work and sometimes they don't using exactly the same CSV. If I import all my variable products, then the variations and the simple products at the end everything works, but if i import my variable products, then the simple and at the end the variations it doesn't.
> 
> Although I understand WooCommerce staff about their automated testing, I'm afraid there must be something in their tests that is not being covered.
> 
> [I wrote a node script](https://github.com/aficiomaquinas/ttamayo-lista-attributes-csv) to transform the columns with the regular import format to the Product CSV Import Suite format, populate the default product with the cheapest variation, automatically fill the variable product possible variations from all the variations in the CSV if the current attribute is used for variations, change the columns name with the attribute's name and remove all columns with a header name that are not part of the import schema.

Hi 👋

Can you share me your CSV in private or public ?

**Comment by aficiomaquinas** [comment]
I've updated [the repository](https://github.com/aficiomaquinas/ttamayo-lista-attributes-csv) with a working CSV input example.

**Comment by andyefth** [comment]
Hi all,

I hope everyone is well & healthy.

I am facing the same issue, followed the suggestions above, but still cannot resolve.

The steps I follow:

1. I export a csv file with existing variable products, from e-Shop #A (see worksheet **_[Exported from e-Shop #A](https://docs.google.com/spreadsheets/d/1A__5kaTusBLtwddg8qpEtXnDUqGSo30oyINshGUulAw/edit#gid=1372965291)_**) 
2. I use this exported csv file to change **only** the **SKU** (col C), **Name** (col D) and **Parent** (col AF); I delete the **ID** (col A) to avoid duplicate product entry (see worksheet **_[Imported to e-Shop #A](https://docs.google.com/spreadsheets/d/1A__5kaTusBLtwddg8qpEtXnDUqGSo30oyINshGUulAw/edit#gid=0)_**) 
3. I save the csv file with a new name, and then import it back to e-Shop #A
4. Since no changes have been made on the csv file (other than the above-mentioned), I would expect to see the newly imported variable products with the _"Used for variations"_ box ticked; however, it is not (see attached screenshots).

Am I missing something?
I would greatly appreciate your support on this.

Thank you in advance for your valuable time.

![Screenshot 1](https://user-images.githubusercontent.com/3518148/95028214-55940080-06a7-11eb-8013-a9bd67e969fc.png)
![Screenshot 2](https://user-images.githubusercontent.com/3518148/95028217-588ef100-06a7-11eb-82a5-c555ac72f1a3.png)

**Comment by ivanovevgeny** [comment]
I did it!

1. In your csv price rename variation attributes to use only **latin** symbols.
For example, 'Размер' -> 'Size'.
2. If issue still exists, check '_Stock_' column. 
I put '_20_' for variable and '_parent_' for variation.

![image](https://user-images.githubusercontent.com/8840414/95323167-29e76500-08b7-11eb-8732-c9b2561521e6.png)

**Comment by zachary** [comment]
How to resolve this with csv?

**Comment by Genovia35** [comment]
I found the solution. https://docs.woocommerce.com/document/product-csv-importer-exporter/#prettyPhoto

**Comment by rand0meizer** [comment]
> I found the solution. https://docs.woocommerce.com/document/product-csv-importer-exporter/#prettyPhoto

It does not help. This only indicates the reason, which is already known. But it does not explain how to automatically check the box "Used for variations".
The question is different, why this checkbox is not automatically checked and how to set it automatically when importing goods.
When you have 10 variable products, you can set it manually. When you have more than 300 variable products, and each has 4 attributes? You will have to spend a lot of time on putting the checkboxes.

The question of how to automatically put down the "Used for variations" tabs has not been resolved.

**Comment by ivanalvarezt** [comment]
The solution is here -> https://stackoverflow.com/a/48997108

copy&paste:

_In the parent product import (the one that has type "variable")
set the Attribute 1 global column to 1

In the child product import (the one that has type "variant")
set the Attribute 1 name column to the name of the attribute

It will not use it for variants.

**For people who want their import to be a variant**

In the parent product import (the one that has type "variable") set the Attribute 1 global column to 1

In the child product import (the one that has type "variant") set the Attribute 1 name column to the name of the attribute with pa_ in front of it for example size should be "pa_size"_


It works for me! Batch upload with 2400 products and everything went well with this configuration.

**Comment by rwkyyy** [comment]
I have checked the solution in documentation:
https://woocommerce.com/document/product-csv-importer-exporter/#converting-existing-simple-product-to-variable-product

Reimport, without the parents (just import variations) and still does not work.

I had to update the variations for existing products and surprise, now all my products have no variations now (as selections for buying) 🤦‍♂️

**Comment by whywilson** [comment]
## How to import variable products by CSV in WooCommerce?
1. Import variable and variation products to **create products**.
2. Re-import only variation product to **connect variation id to variation product**.
### Notice
1. Variable row has attributes that are imploding the attributes of the variable products by a comma.
2. Do not check **Update Existing Products**.
3. First importing will create the variable product and variation product without the id connected in the Variations tab.
4. Second importing will solve the issues in the First import.

**Comment by rwkyyy** [comment]
@whywilson the 2nd point on the notice section is a big brainfart... 😵‍💫

**Comment by nisiwi** [comment]
I'm also struggling with this issue.

Is this still the only reliable solution to this problem ?

> ## How to import variable products by CSV in WooCommerce?
> 1. Import variable and variation products to **create products**.
> 2. Re-import only variation product to **connect variation id to variation product**.
> 
> ### Notice
> 1. Variable row has attributes that are imploding the attributes of the variable products by a comma.
> 2. Do not check **Update Existing Products**.
> 3. First importing will create the variable product and variation product without the id connected in the Variations tab.
> 4. Second importing will solve the issues in the First import.

**Comment by rrennick** [comment]
> Is this still the only reliable solution to this problem ?

If you are importing new products, add the variable product SKU to the variation `parent` field to import in one upload. 

If your variable products don't have skus then import just the variable products first. Then add the variable product ID to the variation `parent` in the second upload file. You do not need to have the variable product in the upload file when uploading new variations.

**Comment by nisiwi** [comment]
Thanks for the reply rrennick

> If you are importing new products, add the variable product SKU to the variation `parent` field to import in one upload.

I always do this, however this does not solve the problem.

> If your variable products don't have skus then import just the variable products first. Then add the variable product ID to the variation `parent` in the second upload file. You do not need to have the variable product in the upload file when uploading new variations.

They always have SKU's.

From what I can tell I have 3 options, one of which you mention.

1) Upload the parent only and trigger the variant generation from the specified attributes - however I have limited control over the variant title, content etc. that may be unique to that variant but I can control the attribute settings.

2) Upload the parent and variant together and accept that any attributes will be variants that will always be visible on the front end.

3) Upload parent and variant independently

**Comment by nisiwi** [comment]
This does work as a single upload.  In my case I needed to rework the logic generating the product and attribution data for import and remove a couple of custom field conflicts.  As previously mentioned esure you have your global attribute and value mapped.  Then if its not used for variants ensure you have the correct logic set for that (at both the parent and variant) and only present data for the attribute value for each variant when its used for variants, otherwise only present at the parent product level.

**Comment by ogodoabiola** [comment]
Can the Woo team fix this, its obvious a ton of customers are affected

**Comment by d-hamon** [comment]
5 years later and this shit is still not fixed

Whether you choose 0 or 1 for the "Attribute 1 visible" or "Attribute 1 global", it makes no difference and all variations are deactivated and you need to fix thousands of products manually

**Comment by gobica** [comment]
After adding "position" attribute to variations it worked for me.

**Comment by Juanfrozo** [comment]
After trying a bunch of different things it worked for me with this format (screenshot). In my case, I was trying to update the products, so the variations were created before. It only worked for me when I added the "parent_id" column to the variations. Hope this work for you all as well

<img width="586" alt="image" src="https://github.com/woocommerce/woocommerce/assets/173816895/e607a092-9c07-40bf-9800-e4b5df0f52cf">

**Comment by andrej-ilievski** [comment]
I can confirm in 2025 still not fixed. Tried with "pa_" prefix to variations attribute name, tried with re-uploading variations only, tried with adding "Position" column. Nothing works.

**Comment by aficiomaquinas** [comment]
I made a workaround for my specific use case, in case it works for someone:
https://github.com/aficiomaquinas/ttamayo-lista-attributes-csv

**Comment by nanincv** [comment]
2026 still not fixed
