### ISSUE TITLE
Product gallery zoom does not work after changing thumbnail

### ISSUE THREAD

**Issue by sayful1** [woocommerce/woocommerce#21959]
Product gallery zoom does not work if you take mouse cursor instantly on product image after changing thumbnail. When you change product thumbnail, it send request to server for large image. If you take your mouse cursor on product main image before image download fully from server, product zoom does not work even after completing request. And zoom does not work untill you take your mouse cursor outside of product main image and bring it back on it again.

**Steps to reproduce the behavior:**
1. Go to product single page that has four or more gallery thumbnail images.
2. Click (Ctrl + F5) on Windows/Linux and (Cmd + Shift + R) to reload page and refresh cache.
3. Click on second or third gallery thumbnail and instantly take your mouse cursor on product main image.

**Expected behavior**
Zoom should work after loading image from server without taking mouse cursor outside of product image and come back again.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP Version: 5.0-beta5-43907
WC Version: 3.5.1
PHP Version: 7.0.32
Storefront theme version: 2.3.5

**Comment by kloon** [comment]
Thanks for the report, tested and confirm it happens but only if you are very quick to move over the image while it is still in the process of transitioning. Not sure if we can do much about this but we will take a look. If you move the mouse away from the image and back over the image the zoom will work again.

**Comment by mikejolley** [comment]
https://github.com/jackmoore/zoom/issues/59

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22784

**Comment by pixelicous** [comment]
@mikejolley any chance this issue resurfaced? I'm having it on the latest version of woocommerce, the exact same symptoms

**Comment by pixelicous** [comment]
@kloon @mikejolley I noticed this is still happening, if the image isn't loaded yet, and you hover your mouse on the image there will be no zoom, and it wont zoom after loading, unless you stop hovering and move back the mouse
