### ISSUE TITLE
Unable to change order of billing fields

### ISSUE THREAD

**Issue by traed** [woocommerce/woocommerce#23729]
It seems the JS that sorts form fields aren't respecting the priority data attribute if it has been changed by for example the woocommerce_address_to_edit hook.

1. Hook into woocommerce_address_to_edit and change priority of the billing postcode field.
In functions.php:
````
function modify_billing_fields_order($fields) {
	$fields['billing_postcode']['priority'] = 45;
	return $fields;
}
add_filter('woocommerce_address_to_edit', 'modify_billing_fields_order');
````
2. Go to My account -> Addresses -> Edit billing addresses
3. The postcode field will be sorted by the original value, not the one set in step 1.

Changing the sorting in address-i18n.js (lines 129 and 130) to use attr instead of data seems to fix this.

**Expected behavior**
The postcode field should use the priority set in the woocommerce_address_to_edit hook.

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost:8080
Site address (URL): http://localhost:8080
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.8
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.8-MariaDB-1:10.3.8+maria~bionic
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 3.07MB
Database Data Size: 2.13MB
Database Index Size: 0.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.50MB + Index: 0.02MB
wp_postmeta: Data: 0.06MB + Index: 0.03MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 8
post: 2
product: 12
revision: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.2

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: SEK (kr)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by claudiosanches** [comment]
This filter runs too late, there's also custom priority for postcodes that relies in each country configuration.
If you like to change this order, probably better prefer `woocommerce_default_address_fields` filter.

This should fix this issue for you, and also apply to checkout and so on:

```php
function modify_fields_order( $fields ) {
	$fields['postcode']['priority'] = 45;
	return $fields;
}
add_filter( 'woocommerce_default_address_fields', 'modify_fields_order' );
```

**Comment by traed** [comment]
To late? I can inspect the page and see the correct values but the sorting still doesn't work. Is it possible to override this "custom priority"?

**Comment by claudiosanches** [comment]
@traed using `woocommerce_default_address_fields` will allow you to change this priority as I pointed out in my last comment. Have you tried?

**Comment by traed** [comment]
Yes, the JS still overrides the data attribute when you change country from a country without the state field to a country with it.

**Comment by claudiosanches** [comment]
@traed yes, because this depends on the country settings too, see: 

https://github.com/woocommerce/woocommerce/blob/df7d82f744c72bee1487de30bc41bff6c1d43961/includes/class-wc-countries.php#L731-L1272

`woocommerce_default_address_fields` will set the values by default, but `get_country_locale()` may change it based in the country configuration.
