### ISSUE TITLE
Notice: jetpack_tracks_get_identity deprecated since version jetpack-7.5

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#24067]
**Describe the bug**

```
( ! ) Notice: jetpack_tracks_get_identity is <strong>deprecated</strong> since version jetpack-7.5! Use Automattic\Jetpack\Tracking->tracks_get_identity instead. in /home/allendav/public_html/wp-includes/functions.php on line 4451
```

**To Reproduce**
1. Install and activate Jetpack 7.5
2. Go to /wp-admin/admin.php?page=wc-addons

**Screenshots**

<img width="1434" alt="Screen Shot 2019-07-03 at 12 41 30 PM" src="https://user-images.githubusercontent.com/1595739/60620388-ecc92480-9d8f-11e9-822a-17a1885dbe58.png">

**Expected behavior**

No notices.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by htdat** [comment]
Seems this was fixed here https://github.com/woocommerce/woocommerce/pull/24050

I am closing this one :)

**Comment by adampatterson** [comment]
When will the fix be released? I have everything up to date and still have the error.

**Comment by davemoz** [comment]
Same. My shipping calculator hasn't seemed to work(and therefore any sales) since this bug popped up. Need the fix released.

**Comment by htdat** [comment]
From https://github.com/woocommerce/woocommerce/pull/24050 , it will be fixed in WC 3.7.0. 
Since the fix is not complicated, you can try this patch before WC 3.7.0 is released. 

- https://github.com/woocommerce/woocommerce/pull/24050/files
