### ISSUE TITLE
Product Shortcodes Issue With Sortby Options

### ISSUE THREAD

**Issue by plxrisa** [woocommerce/woocommerce#24219]
**Describe the bug**
I published 10 products in my localhost with prices from 1 to 10. After this, I published a test page with shortcode [products limit="48" orderby="date" order="DESC" columns=3 paginate="true"]. The page displays as it should in frontend but the (sort by price: low to high) doesn't work. I also tried this shortcode [recent_products limit="48" columns=3 paginate=true] but the issue remains.

In customizer I have set (sort by the most recents), and in the categories I don't have this problem. The products are listed "by most recents" and I can sort by price without problem. The problem is only if I use shortcode to display products somewhere.

So the main issue is that the product shortcodes don't collaborate with sortby options in frontend.
I can't find another way to display most recents products in a page and still sort them by price in frontend.

**To Reproduce**
1. Use this shortcode [products limit="48" orderby="date" order="DESC" columns=3 paginate="true"] in a page and try to (sort by price: low to high) in frontend.
2. You will see the issue.

**Screenshots**
Check here for more details:
https://www.loom.com/share/6c9ee6baec514ce6bcfb0fb4f771ba33

**Expected behavior**
When we insert a product shortcode in a page, it must works well with sort by options in frontend like in categories.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost/woo
Site address (URL): http://localhost/woo
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Win64) PHP/7.2.18
PHP Version: 7.2.18
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.64.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
Total Database Size: 0.57MB
Database Data Size: 0.45MB
Database Index Size: 0.12MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.41MB + Index: 0.03MB
wp_postmeta: Data: 0.01MB + Index: 0.02MB
wp_posts: Data: 0.03MB + Index: 0.01MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1
customize_changeset: 1
page: 2
post: 2
product: 10
revision: 10

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.5

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by claudiosanches** [comment]
Fixed by #25180

**Comment by plxrisa** [comment]
Hi @claudiosanches, 

I updated to WC 3.9.2 but I still have the same issue. My site is live now so you can check the behavior to this url: https://www.mumlabs.com/νέα-προϊόντα

Try to sort by price (low to high) and you will see the issue.
