### ISSUE TITLE
With "Hide out of stock items from the catalog" checkbox ticked "Filter products by attribute" widget still shows out of stock products.

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#24331]
**Describe the bug**
With `Hide out of stock items from the catalog` checkbox ticked in WooCommerce >> Settings >> Products >> Inventory the `Filter products by attribute` widget still shows out of stock products.

**To Reproduce**
1. Go to WooCommerce >> Settings >> Products >> Inventory and make sure the `Hide out of stock items from the catalog` checkbox is ticked
2. Make sure you have products with certain attributes the widget can use and some of them have stock quantity of 0
3. Add a `Filter products by attribute` widget, filter products by certain attribute
4. Out of stock products will be displayed after filtering.

**Expected behavior**
With that checkbox ticked all out of stock products should be hidden from filtering results.

I also imagine similar behaviour can be replicated with other widgets, although I haven't tested.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by virik** [comment]
+1

**Comment by anant1811** [comment]
Hi @grigorijurasov 👋 , can you let me know which environment this was tested in? 

And if there were other plugins installed as well? In order to help narrow down the cause of the issue, I tried to replicate this on a WP org version, WP 5.2.2 running on a Digital Ocean server (with 3.7.0 RC 2), but this does not happen on my setup. I will try checking with your environment and with different themes as well..

Thank you!

**Comment by virik** [comment]
Any updated here?

**Comment by grigorijurasov** [comment]
Sorry for the delay @anant1811, I've been AFK.

Indeed I am no longer able to replicate this on my test site, perhaps this was fixed in WooCommerce 3.7?

@virik are you able to update WooCommerce to 3.7 and re-test? It's a good idea to make sure you have a site backup or better yet test the update on a staging site.

If you don't have a staging site - you can create one with WP Staging plugin: https://wordpress.org/plugins/wp-staging/

**Comment by virik** [comment]
@grigorijurasov @anant1811 - I can still reproduce this on WooCommerce 3.7. 

Have a look at the following page: https://www.probat.no/produkter/?filter_storrelse=62&query_type_storrelse=or.

The following product appears in the results, but as you can see from the following screenshot, size 62 is not available: https://cl.ly/3fbea9

Thanks.

**Comment by juliaamosova** [comment]
Hi @grigorijurasov,

Thank you for raising the issue. And apologies for the delayed response - we are now in the process of cleaning the repository and going over all the older bugs that have not been triaged by our team. 

With that said, I am not able to reproduce the issue described:

- I have an attribute `Brands` that has 2 options: `H&M` and `Zara`. `Zara` has 5 products assigned to it:

![zara1](https://user-images.githubusercontent.com/19143190/72636486-0fe7aa00-3957-11ea-959e-20302b253d4a.jpg)

- Out of 5 `Zara` attribute products, one of them is out of stock:

![zara2](https://user-images.githubusercontent.com/19143190/72636618-53daaf00-3957-11ea-8ad2-526578a79b80.jpg)

- I added `Filter products by attribute` widget and I filtered by `Zara` - I only see the 4 products that are in stock. The product which is out of stock is hidden as it should be:

![zara3](https://user-images.githubusercontent.com/19143190/72636669-740a6e00-3957-11ea-94d4-6e7919eb885a.jpg)

I tested this with the latest stable version of WooCommerce - 3.8.1. 

@virik are you still able to reproduce the issue? Please let us know. We'd keep this issue open for another 7 days. After that, we'd close it due to inactivity if we'd get no feedback. Thanks!

**Comment by virik** [comment]
Hello,

The problem is not products but product variations. Let’s say you have four products (t-shirt) where all of them comes in two variations (white and black). And let’s say one of them is no longer available in black.

When you filter by black, you should only get three results, but you actually get all four, because the product is still available in white. However if you filter by black, you’re not interested in white t-shirts.

Why we have been asking for is the option to hide out of stock products AND products with out of stock filtered variations when filtering.

I hope this made sense, and that we can find a solution. It’s been a while since we first raised this question.

Thank you!

Best regards
Morten Virik Daglig leder
morten@mementor.no / +47 489 59 593
	
Mementor AS
mementor.no

**Comment by virik** [comment]
Hi,

Did you get this email?

As you have an option to hide out of stock products, I think this option should also hide out of stock variations. When we filter by size 62, we still get products having that variation, even though it’s out of stock:

https://d.pr/i/odc8I5/6VwBWjAJtX
Best regards
Morten Virik CEO
morten@mementor.no <mailto:morten@mementor.no> / +47 489 59 593 <tel:%28%2B47%29%20489%2059%20593>
  <https://www.mementor.no/>	
Mementor AS
mementor.no <https://www.mementor.no/>

**Comment by dougaitken** [comment]
@juliaamosova what @grigorijurasov is reporting is the Variation filter that currently isn't possible in core with reasoning in #6574

This feature is available in the premium Product Filters extension:
`https://woocommerce.com/products/product-filters/`

```
2019-02-11 - version 1.1.10
* Added ability to filter by "stock status"
2019-02-04 - version 1.1.9
* Added ability to check variation products in stock
```

Discussed in 18116562-hc

**Comment by juliaamosova** [comment]
@dougaitken thanks for linking the issue with an explanation and providing details of the workaround. 

@grigorijurasov I am closing this issue since there is no action to be taken on the WooCommerce Core side of things.
