### ISSUE TITLE
Brexit - October 31 - November 1

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#24666]
As you all know, Brexit is scheduled to happen on October 31 and, taking in consideration the current negotiation status, on November 1 UK will most certainly be out of the EU and everything seems to point on a no-deal exit.

**Why is this important for WooCommerce?**
I think WooCommerce should schedule a release for November 1  removing 'GB' from the `WC_Countries::get_european_union_countries()` function.
Additionally, if we know for sure there will be no deal regarding VAT exemption, maybe a release should be made in advance with a condition inside this function that will remove 'GB' from November 1 onwards. This would help people be ready in advance.

**Why should we care?**
Several plugins use this function to detect if a country is on the EU VAT exemption zone for B2B, which will (most probably) change that day.

**Comment by webdados** [comment]
Let me just be clear that I'm not suggesting this is done right now.

Right now it should be decided that this release will be made **immediately** when there's no turning back on the Brexit date, be it October 31 or in the future.

**Comment by rodrigoprimo** [comment]
Thanks for bringing the implications of the Brexit to our attention, @webdados. I will discuss this with the rest of the team and share here what we plan to do.

I personally agree with your suggestion that we should release a new version of WooCommerce removing 'GB' from `WC_Countries::get_european_union_countries()` as soon as it is confirmed that Great Britain is out of the EU. I don't think we should schedule a release as right now it seems impossible to know for sure when this is happening.

**Comment by rodrigoprimo** [comment]
Just a quick update to confirm that our plan is what I suggested above. We will monitor the situation and, if needed, we will release a new version of WooCommerce once it is clear that the Brexit is happening and what are the implications.

PR #24741 adds a filter to `WC_Countries::get_european_union_countries()` which doesn't solve the issue described here but should help to accommodate edge cases if WooCommerce 3.8.0 is release before the Brexit.

**Comment by webdados** [comment]
Perfect!

**Comment by peterfabian** [comment]
I've added high priority as I assume it could affect a lot of customers in UK or in EU sending goods to UK customers. VAT issues are important to get right. Feel free to reevaluate.

**Comment by vedanshujain** [comment]
@peterfabian I am removing the high priority tag because we have just merged the PR that adds a filter. In case Brexit happens after 3.8, folks would be able to use a plugin as a workaround while we release a fix.

**Comment by webdados** [comment]
"folks would be able to use a plugin as a workaround while we release a fix"

A fix needs to be released on the Brexit day (or even before, when we are sure of the date, with a conditional output). There are no workarounds when dealing with taxes.

**Comment by vedanshujain** [comment]
@webdados just to be clear, we would still do a new release as soon as we get more concrete information regarding Brexit. I removed the priority label because there nothing actionable for us to do at the moment since we merged the filter PR. 
This will again go to high priority as soon as some new information about Brexit surfaces.

**Comment by webdados** [comment]
Heads up: https://twitter.com/BorisJohnson/status/1184764798107602944

Still not 100% certain it will be on October 31, thou.

**Comment by DavidAnderson684** [comment]
In WooCommerce core, the `get_european_union_countries()` method is used to decide whether sales taxes should be displayed in the UI as "tax" or "VAT". If/when Brexit happens, "VAT" will still be the correct label in the UK. It looks like core should have a new method to identify the label, rather than treating the question as identical to "in the EU or not?"

**Comment by GlennMartin1** [comment]
Brexit has been delayed until approx January 31.

**Comment by peterfabian** [comment]
Just to make it a little more complicated, I think it's called a 'flextension', so theoretically speaking, UK could leave also on Dec 1st or Jan 1st. 😀

**Comment by webdados** [comment]
Tic tac ⏱Tic tac ⏱

We're 8 days away and the PR still produces a fatal error and includes stuff that is not related to this issue. We just need to remove GB from `WC_Countries::get_european_union_countries()`, on the 31st of January, and that's it.

**Comment by DavidAnderson684** [comment]
@webdados It's already been pointed out that it's incorrect to say that the only thing that matters is the name of a single method (https://github.com/woocommerce/woocommerce/issues/24666#issuecomment-543983536) . We also now know (since the withdrawal agreement has gone through the UK parliament) that under the terms of that withdrawal agreement, the UK will remain part of the EU VAT area after Brexit - https://www.avalara.com/vatlive/en/vat-news/uk-to-leave-eu-vat-regime-31-dec-20200.html .

**Comment by webdados** [comment]
> under the terms of that withdrawal agreement, the UK will remain part of the EU VAT area after Brexit 

Thanks for the clarification!

**Comment by claudiosanches** [comment]
I have updated the code from our PR, now there's multiple filters to make easier to include VAT countries in the list without making those countries part of EU.

https://github.com/woocommerce/woocommerce/pull/24943

**Comment by claudiosanches** [comment]
Also based on the news from https://www.avalara.com/vatlive/en/vat-news/uk-to-leave-eu-vat-regime-31-dec-20200.html

> Under the terms of the WA, the UK will have an exit transition period until 31 December 2020. Until this time, the UK will remain within the EU VAT regime, Single Market and Customs Union. 

So there's nothing else that we need to do on WooCommerce for now.
I'll close this issue since there's also a PR that will helps change it by filters too, and because for now we don't need to take any action.

**Comment by tammullen** [comment]
And also directly from the UK Government's site
https://www.gov.uk/transition

> After 31 January 2020 there will be a transition period until the end of 2020, while the UK and EU negotiate additional arrangements.
The current rules on trade, travel, and business for the UK and EU will continue to apply during the transition period.
