### ISSUE TITLE
Two Orders at the same time (can) lead to a empty and a "merged" order

### ISSUE THREAD

**Issue by mrohnstock** [woocommerce/woocommerce#25623]
**Describe the bug**
First: Issue #17660 do look like the same issue, but as the issue is closed I will open a new issue with further descriptions.

If two customers orders something in our store at the same time, some (all?) products ordered from customer A get moved to customer B.

This happened now the second time, with a gap of about 6 month (?). PayPal and Amazon Pay got used as Payment Method. The older orders (~6 month ago) did use "Klarna" and PayPal.

We don't use any kind of caching (even WP-Optimize is activated as plugin, the "caching" feature got disabled, same for "Redis Object Cache" - plugin is enabled, but caching feature is disabled). We don't use load balancing and are only using a single database and server.

**To Reproduce**
1. Order something in your store two time at the same time
2. See, that some (all?) products of your first order gets included to the second order (or vice-versa).

**Screenshots**

here is the first order

![first-order](https://user-images.githubusercontent.com/823072/74136438-534bd600-4bee-11ea-8d91-9719bef02509.png)

here is the second order, where all ordered products got appended (the first two products belong to the first order, the third product should really be part of the order).

![second-order](https://user-images.githubusercontent.com/823072/74136503-6f4f7780-4bee-11ea-8f6f-a7148b1c439c.png)

**Expected behavior**

Order of customer A should only include products ordered from customer A and the order of customer B should only include products ordered from customer B.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://auto4style.com
Site address (URL): https://auto4style.com
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.4.1
PHP Post Max Size: 50 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.11-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 791.55MB
Datenbank-Datengröße: 429.02MB
Datenbank-Indexgröße: 362.53MB
wp_woocommerce_sessions: Daten: 9.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 5.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 80.61MB + Index: 143.30MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_creatives: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referralmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referrals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 21.55MB + Index: 16.88MB + Engine InnoDB
wp_icl_content_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Daten: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_icl_locale_map: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Daten: 7.52MB + Index: 11.09MB + Engine InnoDB
wp_icl_string_packages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Daten: 44.56MB + Index: 43.09MB + Engine InnoDB
wp_icl_string_positions: Daten: 0.34MB + Index: 0.11MB + Engine InnoDB
wp_icl_string_status: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Daten: 9.52MB + Index: 4.03MB + Engine InnoDB
wp_icl_string_urls: Daten: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_icl_translate: Daten: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_icl_translate_job: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Daten: 4.52MB + Index: 10.06MB + Engine InnoDB
wp_icl_translation_batches: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Daten: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 6.20MB + Index: 0.39MB + Engine InnoDB
wp_postmeta: Daten: 164.70MB + Index: 97.22MB + Engine InnoDB
wp_posts: Daten: 38.14MB + Index: 18.02MB + Engine InnoDB
wp_redirection_404: Daten: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_smush_dir_images: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.48MB + Index: 0.28MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 2.52MB + Index: 1.77MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 3.52MB + Index: 1.91MB + Engine InnoDB
wp_wc_order_stats: Daten: 2.52MB + Index: 1.23MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.13MB + Index: 0.38MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 1.52MB + Index: 0.94MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_links: Daten: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_yoast_seo_meta: Daten: 5.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 62246
fpf_fields: 1
invoice: 17868
jetpack_migration: 2
jp_sitemap: 1
jp_sitemap_master: 1
ml-slide: 605
ml-slider: 71
nav_menu_item: 66
page: 336
post: 2
product: 110
product_variation: 1394
revision: 23
scheduled-action: 6239
shop_coupon: 25
shop_order: 19847
shop_order_refund: 38
site-review: 78
wc_reminder_email: 6
wpcf7_contact_form: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

WPML Multilingual CMS: von OnTheGoSystems – 4.3.6
AffiliateWP: von Sandhills Development
LLC – 2.4.4

Classic Editor: von WordPress-Mitwirkende – 1.5
Contact Form 7: von Takayuki Miyoshi – 5.1.6
Klarna Order Management for WooCommerce: von klarna
krokedil – 1.5.0 – Nicht getestest mit der aktiven WooCommerce-Version

Klarna Payments for WooCommerce: von krokedil
klarna
automattic – 2.0.5 – Nicht getestest mit der aktiven WooCommerce-Version

MetaSlider: von Team Updraft – 3.15.3
PixelYourSite Pinterest: von PixelYourSite – 2.0.10
PixelYourSite: von PixelYourSite – 7.1.4 – Nicht getestest mit der aktiven WooCommerce-Version
Redis Object Cache: von Till Krüss – 1.5.6
Site Reviews: von Paul Ryley – 4.3.8
Storefront Mega Menus: von WooCommerce – 1.6.2 – Nicht getestest mit der aktiven WooCommerce-Version
Storefront Powerpack: von WooCommerce – 1.5.0
Products: von Mathias Rohnstock – 1.0.0
User Role Editor: von Vladimir Garagulya – 4.53
Vendidero Helper: von Vendidero – 1.3.0
WooCommerce Smart Reminder Emails: von Ewout Fernhout – 1.4.2 – Nicht getestest mit der aktiven WooCommerce-Version
WC Variations Radio Buttons: von 8manos – 2.0.2 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Admin: von WooCommerce – 0.25.1
WooCommerce Amazon Pay: von WooCommerce – 1.11.0 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.19
Sofort payment gateway: von Sven Wagener – 1.4.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Stripe-Gateway: von WooCommerce – 4.3.1 – Nicht getestest mit der aktiven WooCommerce-Version
Germanized für WooCommerce Pro: von Vendidero – 2.0.12
Germanized für WooCommerce: von Vendidero – 3.1.2
WooCommerce Multilingual: von OnTheGoSystems – 4.7.7 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce: von Automattic – 3.9.1
Yoast SEO Premium: von Team Yoast – 12.5
WP Mail SMTP: von WPForms – 1.8.1
WP-Optimize - Clean, Compress, Cache: von David Anderson
Ruhani Rabin
Team Updraft – 3.0.16

Smush: von WPMU DEV – 3.4.2
WP Desk Helper: von WP Desk – 1.7.0 – Nicht getestest mit der aktiven WooCommerce-Version
WPML Media: von OnTheGoSystems – 2.5.5
WPML String Translation: von OnTheGoSystems – 3.0.6
WPML Translation Management: von OnTheGoSystems – 2.9.4

### Inactive Plugins (4) ###

Flexible Product Fields: von WP Desk – 1.2.11
Flexible Product Fields Pro: von WP Desk – 1.2.1 – Nicht getestest mit der aktiven WooCommerce-Version
Redirection: von John Godley – 4.6.2
WooCommerce Services: von Automattic – 1.22.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: ❌ Seite nicht festgelegt
Warenkorb: #6 - /cart/
Kasse: #7 - /checkout/
Mein Konto: #8 - /mein-konto/
Allgemeine Geschäftsbedingungen: #194 - /allgemeine-geschaeftsbedingungen/

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: /srv/http/auto4style/wp-content/plugins/theme-customisations/custom/templates/woocommerce/cart/cart-item-data.php

### Action Scheduler ###

Abgeschlossen: 5.613
Oldest: 2020-01-10 10:16:04 +0100
Newest: 2020-02-10 10:15:03 +0100

Ausstehend: 352
Oldest: 2020-02-10 10:17:27 +0100
Newest: 2020-03-11 01:41:14 +0100

Abgebrochen: 274
Oldest: 2020-02-04 13:42:33 +0100
Newest: 2020-03-07 23:32:59 +0100

In Bearbeitung: 0
Oldest: –
Newest: –

Fehlgeschlagen: 0
Oldest: –
Newest: –
</details>

Thanks

**Comment by darrenwhittingslow** [comment]
We are also experiencing this problem on our wordpress site. If we can push this up the bug fix list it would be appreciated

**Comment by claudiosanches** [comment]
Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end.

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by mrohnstock** [comment]
Well this issue do only occur if two orders get proceeded at exactly the same time (in the same second). I don't know how anyone should be able to reproduce this? I wasn't able, too. I do only see these kind of orders in the shop and they all do have the exact same order time.

There have to be some kind of concurrency in a rare timespan between clicking on "Place order", proceeding with the payment process of the selected payment service and display the "Thank you"-page.

**Comment by claudiosanches** [comment]
> Well this issue do only occur if two orders get proceeded at exactly the same time (in the same second). I don't know how anyone should be able to reproduce this? 

We have tools to simulate it, yet I can't reproduce this issue, so just it isn't enough.

**Comment by juliaamosova** [comment]
Hi @mrohnstock,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Comment by YuriCoelho197** [comment]
Hi @juliaamosova, @claudiosanches , @mrohnstock 

I had the same problem on a site.
I identified that the problem came from a plugin. This plugin used the "woocommerce_checkout_create_order_line_item" hook, and inside the function it performed a $item-> save().

By removing this hook, the problem was solved.

I also reproduced it on a blank site, all updated (woocommerce 4.4.1), without cache, adding this to functions.php:

```
add_action( 'woocommerce_checkout_create_order_line_item', 'testitems', 10, 4 );

function testitems( $item, $cart_item_key, $values, $order ) {
    $item->save();
}
```

apparently the problem occurs because &item->save () is executed before saving the order ($order->save(), in woocommerce/includes/class-wc-checkout.php, line 389), maybe losing the information that separates the items into different orders.

**Comment by seldimi** [comment]
Hey,
Have you informed the plugin author of Redis Object Cache about it ?

**Comment by tillkruss** [comment]
@seldimi: It looks like @mrohnstock disabled object caching and is still expiring the issue. It also sounds like @YuriCoelho197 narrowed this down to another plugin causing the problem.

**Comment by seldimi** [comment]
Which was it?
Maybe it's core issue?

**Comment by seldimi** [comment]
Hello.
We are still experiencing same issue. 

The website is using latest WC version and is connected to a third party API which creates order on the WC platform via CRUD methods. The problem is that when someone orders something from website and the API sends an order in the same second, two orders are created, one is empty and one has merged.

I believe that the issue is made by $oder_item_id=$order->add_product() which might mess up the order IDs...

I ll try to update if I find something more

**Comment by 970DesignUser** [comment]
We're noticing this happening periodically on a high traffic woo commerce site as well - WooCommerce 6.1.1

**Comment by cristacheda** [comment]
I'm noticing this issue from time to time when there's high traffic. How should I go about debugging this issue?

**Comment by seldimi** [comment]
You can schedule remotely to add two different orders with two different products via WooCommerce REST on certain minute, but it should trigger same second.

**Comment by cristacheda** [comment]
Could this function be the cause?

```
add_action('woocommerce_checkout_create_order', 'save_regular_price_in_order', 10, 2 );
function save_regular_price_in_order( $order, $data ) {
    foreach( $order->get_items() as $item_id => $item ){
        $product = $item->get_product();
        $regular_price = $product->get_regular_price();
        $sale_price = $product->get_sale_price();
        $item->update_meta_data( '_regular_price', $regular_price );
        $item->update_meta_data( '_sale_price', $sale_price );
        $item->save();
    }
}
```

I saw a few mentions about the $item->save() line - is there any available replacement?

**Comment by seldimi** [comment]
From what [YuriCoelho197](https://github.com/YuriCoelho197) said, this is the cause
_apparently the problem occurs because &item->save () is executed before saving the order ($order->save(), in woocommerce/includes/class-wc-checkout.php, line 389), maybe losing the information that separates the items into different orders._

**Comment by cristacheda** [comment]
I think I fixed it. Instead of saving each item in the loop, I save the order and since making this change I couldn't reproduce the bug anymore.

```
add_action('woocommerce_checkout_create_order', 'save_regular_price_in_order', 10, 2 );
function save_regular_price_in_order( $order, $data ) {
    foreach( $order->get_items() as $item_id => $item ){
        $product = $item->get_product();
        $regular_price = $product->get_regular_price();
        $sale_price = $product->get_sale_price();
        $item->update_meta_data( '_regular_price', $regular_price );
        $item->update_meta_data( '_sale_price', $sale_price );
        // $item->save();
    }

    $order->save();
}
```

**Comment by seldimi** [comment]
Really? Hopefully if can be tested and released that would fix a bug since 2020

**Comment by SuperSambat** [comment]
March 11th, 2024.  still an issue when there's an order at almost exact time, happening on high traffic website

**Comment by spitnale** [comment]
Two Orders at the same time on a high traffic website lead to a empty and a "merged" order. This is still happening constantly for us.

**Comment by jkohlbach** [comment]
Ok, this is a super tricky issue. But, after some investigating it seems the issue is around calling $item->save() when using hooks in the class-wc-checkout.php file or, if you like, during the "checkout" process context.

When you save the item, which is not yet assigned to the order, WC will try to create a blank order or item. This effectively means you're creating an orphaned item.

The issue is that WC doesn't know about the context and happily does what it's told and tries to save :)

In our case, we are using "woocommerce_checkout_create_order_line_item" hook to modify the item and add some meta data. The solution is to not call ->save() at all on either the item OR the order object. WooCommerce itself will call ->save() after the "woocommerce_checkout_create_order" hook fires.

**Comment by vedanshujain** [comment]
Reopening based on above comments.

**Comment by seldimi** [comment]
Its not always like that, we do a 
$order->add_item( $item );
and still the issue exists..

if we have 2 orders on the same second, from an external source and create a WC_Order with its items, it happens.

**Comment by vedanshujain** [comment]
bot no!

**Comment by vedanshujain** [comment]
We have added a possible fix for this in #46161, but given that there's no stack trace, there's a chance that the issue is different. The fix will be available in WC 8.9, but if someone is highly impacted and comfortable with editing plugin code, these are the relevant lines from the fix: https://github.com/woocommerce/woocommerce/pull/46161/files#diff-3bb9bce13a75a81b0fb3401e2655a63fb8fc9d9318cfdf01fb2412d37275b326R518-R520.

**Comment by dabesa** [comment]
We were able to replicate this issue in staging, and the fix seems to work. 
We applied the fix in the live environment.

**Comment by spitnale** [comment]
This did not fix our merge order issues. We continue to have orders with different cart hashes combine.

**Comment by faraz110** [comment]
this is still not fixed even after a long time, it's happening when 2 or more users placing order on the very same time, how hard it is for woocommerce team to understand?

this is such a frustrating situation for all of us that one of the most popular ecommerce solution is unable to resolve this issue.

but my hopes are with individual like us who can get it to the bottom of this stupid bug and able to find a solution

**Comment by albertorrent** [comment]
Hello, any updates on this? We are also experiencing this problem on our wordpress site.
