### ISSUE TITLE
WooCommerce Admin Dashboard not translating all German Translations

### ISSUE THREAD

**Issue by jesscga** [woocommerce/woocommerce#25920]
**Describe the bug**
When the site language is set to German, some of the text in the dashboard (`WooCommerce > Dashboard`) appears in English.

**To Reproduce**
1. Set language at **Settings > General** to **Deutsch**
2. Go to **WooCommerce > Dashboard**

**Screenshots**
![WooDeutchDashboard](https://user-images.githubusercontent.com/19862549/76663306-f62da200-6556-11ea-8d55-f812904a3ee6.png)

**Expected behavior**
All text should be in German, including **Performance**, **Charts**, **Total Sales**, etc.

When I checked the translation files for the untranslated strings, the strings do show valid translations:

![totalsales](https://user-images.githubusercontent.com/19862549/76663748-68eb4d00-6558-11ea-8f4a-d5801460d1e0.png)

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://jesscga.com
Site address (URL): https://jesscga.com
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.15
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.68.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 3.74MB
Datenbank-Datengröße: 2.33MB
Datenbank-Indexgröße: 1.41MB
wp_woocommerce_sessions: Daten: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 0.36MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 6
post: 1
product: 1
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: von Automattic – 4.0.0

### Inactive Plugins (7) ###

Akismet Anti-Spam: von Automattic – 4.1.3
Jetpack by WordPress.com: von Automattic – 8.3
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.20 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Services: von Automattic – 1.22.4
WooCommerce Square: von WooCommerce – 2.1.0 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Stripe Gateway: von WooCommerce – 4.3.2 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce USPS Shipping: von WooCommerce – 4.4.38

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #7 - /shop/
Warenkorb: #8 - /cart/
Kasse: #9 - /checkout/
Mein Konto: #10 - /my-account/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 239
Oldest: 2020-02-29 21:35:08 +0000
Newest: 2020-03-13 22:19:09 +0000

Ausstehend: 2
Oldest: 2020-03-13 23:04:57 +0000
Newest: 2020-03-14 22:42:36 +0000

`
```
</details>

**Comment by marcochiesi** [comment]
I confirm the same bug for Italian as well.

**Comment by rrennick** [comment]
For translations downloaded via the plugin repository, the translation files are from https://translate.wordpress.org. Are you using your own translation files or downloaded the translated version?

**Comment by marcochiesi** [comment]
I am using the translation files downloaded automatically from https://translate.wordpress.org. It seems that the plugin is not loading the translations properly, as the translated text appears to be in place inside the downloaded ".po" files. As far as I can see this issue only occurs in the new "WooCommerce Admin" interface, while all the other translations in the backend are fine.
P.s. By the way, I am a Global Project Translation Editor for the Italian language and I am one of the main maintainers of WooCommerce's Italian translation.

**Comment by rrennick** [comment]
> as the translated text appears to be in place inside the downloaded ".po" files.

I'm not clear on how the plugin installer installs translation files, but .po files are not used to deliver translations. In WP, PHP translations use `.mo` files & javascript uses `.json` files. 

I downloaded the Italian zip and it only has the .po file. In your install these files will be located in `wp-content/languages/plugins/`. The `.mo` file is probably `woocommerce-it_IT.mo` and the `.json` are the same except they have a MD5 hash before the .json. Can you provide the list of those files?

**Comment by rrennick** [comment]
After thinking about this I realized this is the same issue I addressed in WC Admin in https://github.com/woocommerce/woocommerce-admin/pull/3433.

**Comment by marcochiesi** [comment]
Here's the list of files I have in `wp-content/languages/plugins/`:

```
woocommerce-it_IT-02acd74879196411261af7576fdb4b93.json
woocommerce-it_IT-056e3f14efed538fde21950202add8dc.json
woocommerce-it_IT-05d09138941a659d44e69e36a6128b77.json
woocommerce-it_IT-07ab4692a994f127e1cd893f363cfa3e.json
woocommerce-it_IT-09c5919a18291dd26d6f52f9d1563a8e.json
woocommerce-it_IT-0a3b65850c50f16de824a40fa5ff0f0f.json
woocommerce-it_IT-0b8996a2cb219ae7e381f93b3be0b67d.json
woocommerce-it_IT-0cf7579f6fbc3a394bde81590518d79e.json
woocommerce-it_IT-0e3dcd4f3ff5aa786acbbd18de58d420.json
woocommerce-it_IT-0f41b2a348452c70c6481186c90ee539.json
woocommerce-it_IT-124cfb7a5d89d9c89c181e1d53e04227.json
woocommerce-it_IT-154eb5541053115f9cf2cc279decf649.json
woocommerce-it_IT-18a31075fa5f4596edaf76ec78921ff4.json
woocommerce-it_IT-18cb1508cf8b268459dfb0b7544a4a6f.json
woocommerce-it_IT-1ab3c5ff6a861a0bbc5e57811248de9b.json
woocommerce-it_IT-1b59d077cd5a766feef182aa33bfdeb6.json
woocommerce-it_IT-1c0b6556acc988893b0a5233ecc0a0cf.json
woocommerce-it_IT-1ecbf13afe7c7d7136c189b714bbb8ec.json
woocommerce-it_IT-1f453658d28cb7b0dbbf2fe5656a0e52.json
woocommerce-it_IT-1fd108afcd6b1150ccd257c03371fcf4.json
woocommerce-it_IT-206459d169f12b652a1dabe78a376826.json
woocommerce-it_IT-21fee52f2b4be704278bd81018c89b15.json
woocommerce-it_IT-264d96e187371a7fc19cfb0c0e17601f.json
woocommerce-it_IT-266b21f550f6c336217746f77332e8d9.json
woocommerce-it_IT-296a2578b2d8df6921f0d13a4fa83a63.json
woocommerce-it_IT-2a130218c40b2b37eedb3857f22c90a1.json
woocommerce-it_IT-2a4f5667ed4e81d44f6ccfb84523b904.json
woocommerce-it_IT-2a7eca80ba12897c21ffaa74974c8fef.json
woocommerce-it_IT-2cd54bc9eeab906cf0f6abb2399e9fb7.json
woocommerce-it_IT-2e5b773a600e6595bad14136c2d73f08.json
woocommerce-it_IT-30a76cbd1d834be53da07353ae9c04f6.json
woocommerce-it_IT-346e00957d00882d99868c46bad422f4.json
woocommerce-it_IT-36b6e0ecd8b0ca24f5b02a505afa04ad.json
woocommerce-it_IT-36e7818bfdfd4a6943db89e1565c4cc7.json
woocommerce-it_IT-376011c6441a11bdb03699ed8ce0becc.json
woocommerce-it_IT-398358f27f594f39ff10747d855fc068.json
woocommerce-it_IT-39de01d53e1a7555444d48e522e8dfa0.json
woocommerce-it_IT-40b17adf34449ee7e3e363a1c1c25b5d.json
woocommerce-it_IT-42bda93e026cec336f1afb5ad835ab7a.json
woocommerce-it_IT-4a74985a61168391319ab15c958cf984.json
woocommerce-it_IT-4c7c269e37d7cb4f326b016333ed89f8.json
woocommerce-it_IT-4e3234bb41d0851c150e919809099a0c.json
woocommerce-it_IT-571d84627e5bb3bf6dfe96cb83a16bff.json
woocommerce-it_IT-5732890af28c709ee103d63f5e400d73.json
woocommerce-it_IT-5a5292d4981044a0b7513bae8a1b295e.json
woocommerce-it_IT-5aebce178e3b807850cc26e942059a9b.json
woocommerce-it_IT-5b37725cbb6d468f2f7f24e4197c910f.json
woocommerce-it_IT-5ca9d7c1e762634623941efe4d5a2469.json
woocommerce-it_IT-5dbb887395521bca37d8989620c54fd0.json
woocommerce-it_IT-5e97339e0756e5bda516a3bcccc55291.json
woocommerce-it_IT-600a680df13366b0dff255bf450a774d.json
woocommerce-it_IT-62e815516fb81906c218cf351160c884.json
woocommerce-it_IT-63c86bee87d5e82df937a2c2dce16b08.json
woocommerce-it_IT-64d497c5d8b8575a28edb2fc5ff5b5a1.json
woocommerce-it_IT-6b540692fe4f3228bbf79cd1e559660a.json
woocommerce-it_IT-6b82d38e8ac7d8966cd8377aae33e5fd.json
woocommerce-it_IT-6cbf0d6770d52e8763d2ee282a94c30f.json
woocommerce-it_IT-724b9c3fa3633db8112718fc03c8079b.json
woocommerce-it_IT-73078688a92ac960cb12644c13b110b0.json
woocommerce-it_IT-745e871de011e6c267379c88172c4f84.json
woocommerce-it_IT-74d045bafa8cbebd4fe0f277010a5102.json
woocommerce-it_IT-75390e8f65306e29d19720d2ddda8e90.json
woocommerce-it_IT-759a1ecfc9e66ff8de9f9a98045ceb87.json
woocommerce-it_IT-75a7eaceda97b32841d31b557468c4ab.json
woocommerce-it_IT-75d33b4e15a83feea4a7a74e5b2207dd.json
woocommerce-it_IT-77b25a5ccb12a232ba73108568db40e0.json
woocommerce-it_IT-79d0b523871c2f1d9a119aa7bd14ac21.json
woocommerce-it_IT-79f91321ec3ca398900fee5735aa23a9.json
woocommerce-it_IT-7a0089e0f72f7726bb4920c2ee0e04e8.json
woocommerce-it_IT-7cbf48bcd2a87f95ec4eda44a0eb7258.json
woocommerce-it_IT-7ccc612d69e4b064526ea8bc1dac3a79.json
woocommerce-it_IT-7e5d2c9dbcb942e4c4e0f319104c16d0.json
woocommerce-it_IT-809b6b441475f60be6875318fedb118d.json
woocommerce-it_IT-811738b7af9095a276a319dfbe46bceb.json
woocommerce-it_IT-818de2a45ff7eb25cd76b75b402b5c04.json
woocommerce-it_IT-81fa76932399ec1b6d1c882dfe0f38b2.json
woocommerce-it_IT-83c12cf92f9b74ecc178cefa51d88dde.json
woocommerce-it_IT-84b8b958854766b6b4b4d21a482acf19.json
woocommerce-it_IT-85bc274b5e191417528a5d83a3e0df4c.json
woocommerce-it_IT-86f183bc49f007e059e226dec4e78466.json
woocommerce-it_IT-87c5431fc38ba348d837ebed0331c445.json
woocommerce-it_IT-8c74bc279a70f95ca5874f30b9a39965.json
woocommerce-it_IT-8ec38ff3b075251215c400d813522164.json
woocommerce-it_IT-90b863d65ec140f99ebc0855bade2d35.json
woocommerce-it_IT-90d7eeda62b9eba288367d299dab8304.json
woocommerce-it_IT-93691bbb61f9d37c583e85aab1e1d489.json
woocommerce-it_IT-97d11a05fccdd9ecef9e4fcb7c0a6a46.json
woocommerce-it_IT-987cb2ea425b511e6d4b374ca417189c.json
woocommerce-it_IT-9a73667f668670d494d233823a0e936f.json
woocommerce-it_IT-9b8014a68baafa4f1874783d1820cca7.json
woocommerce-it_IT-9b9fdaa6d7447798fbd2c0393d43cf8a.json
woocommerce-it_IT-9e193e1001d6d89ebfd1dc6040b524a1.json
woocommerce-it_IT-a11697bf8fcba5f513c6d982904407e4.json
woocommerce-it_IT-a239aacc1837e5b8b6968881fcefaf44.json
woocommerce-it_IT-a2ae79133a4c6da7ca0b4529c4aa6e7a.json
woocommerce-it_IT-a354d4299731b33e847e6eb5329b1a7e.json
woocommerce-it_IT-a3f7f18b58640a626fd1dfafe4b5ba63.json
woocommerce-it_IT-a3f9dc6e9d40e3a716d512c21559fe0b.json
woocommerce-it_IT-a46e2cdf66e3645fd11b123961dc9b40.json
woocommerce-it_IT-aa332e7383ce333ae0d4b6ed4d4c96fe.json
woocommerce-it_IT-af52ab8cb2e7713cf3037751dd593965.json
woocommerce-it_IT-b007baff76144318d6c33cd26f4bfdb9.json
woocommerce-it_IT-b0a592b6fe83588c5d1b8ed6850b6a74.json
woocommerce-it_IT-b155b7bf28890099b74a84417cbaafe9.json
woocommerce-it_IT-b1bb8fbd24d68a9c893faf1a6f7b493b.json
woocommerce-it_IT-b1bcbab1d6a7ca6b0433d67776f347f1.json
woocommerce-it_IT-b31f51fa0bb40ceb060aaa9f77ca1771.json
woocommerce-it_IT-b826befd7acca93e8e4c12b7cd2fc7f1.json
woocommerce-it_IT-ba8d2fb7c85928310d4f3a907b7d9bdd.json
woocommerce-it_IT-baa529102e65ee476d9a82ac1564e366.json
woocommerce-it_IT-c0faba84c7842505f8893c2c327a9f78.json
woocommerce-it_IT-c22945301f466e2d78d6e80404a22664.json
woocommerce-it_IT-c2435bc8dfd186b147aba658416d115e.json
woocommerce-it_IT-c2d9a34cf502bd5b5a80ca646a1420b3.json
woocommerce-it_IT-c2e7c011ee5dd15c730dad6f5e884539.json
woocommerce-it_IT-cc02e92f0af36b7c4f36de274b6e1ca3.json
woocommerce-it_IT-cc16013df9d4b0a0ba45297b90b06f20.json
woocommerce-it_IT-cc658045f5281864af07573751f8ff22.json
woocommerce-it_IT-cd9fc1d9fc46b55bb32d0fd471457690.json
woocommerce-it_IT-ce966b75625b434ab1259ce171c61293.json
woocommerce-it_IT-d2b4400b6de0e69404e0f7f61d16bc55.json
woocommerce-it_IT-d5ea33028f13b50f40bbcce807e37fc0.json
woocommerce-it_IT-ddb7f533a41db7e057e43bcf87270ece.json
woocommerce-it_IT-e0bde0ac58f55fc6b1426844e6697db3.json
woocommerce-it_IT-e46884f39517e74b7de819976d889acd.json
woocommerce-it_IT-e8faa9474808d756455fe69932b5fc8e.json
woocommerce-it_IT-e930ab0f3b2fd33635ed5033ec41fbd4.json
woocommerce-it_IT-ea6fb371f81c4d3584bbc795fa4ac09c.json
woocommerce-it_IT-ea967f41689ec1c0cda73a32439a5405.json
woocommerce-it_IT-ed2f62f6080e473f023f3b6641e4351d.json
woocommerce-it_IT-ef5798395d7601ab6fea0f1efd60f40a.json
woocommerce-it_IT-f2d5abd38e77f463761f5ce3181f73f1.json
woocommerce-it_IT-f31b0aa0c71dd74b7103120610ca6253.json
woocommerce-it_IT-f3f1cc4f5811d4bf8a04a58feca06858.json
woocommerce-it_IT-f60049653c419cfb1e3dc8876e7a8bdb.json
woocommerce-it_IT-fc1fe56fadfdeeb25d1bc441581d92b6.json
woocommerce-it_IT-fc4895b6508f32c16c4d8bc69f8162b6.json
woocommerce-it_IT-fccc2ef327a40a2d734aab3fb1b1a403.json
woocommerce-it_IT-fd20fc8ea1484781160e8ea0d229d5e9.json
woocommerce-it_IT-fde4427d32e8542cdde04dbd2b8676c2.json
woocommerce-it_IT-fffdec5db595ec0ca7d043c87bae79b8.json
woocommerce-it_IT.mo
woocommerce-it_IT.po
```

**Comment by fernandotellado** [comment]
Same Issue with es_ES translation. 

The WooCommerce Admin plugin is totally translated, and if you install and activate the plugin then WooCommerce appears fully translated, because the issue is related to the new admin interface

**Comment by callmejud** [comment]
Hello, I'm having the same issue with the French translation... Have you found a solution yet ? 
Thanks !

**Comment by yanisla35** [comment]
> Hello, I'm having the same issue with the French translation... Have you found a solution yet ?
> Thanks !

Hello,

For now, the only solution I found is to change your WordPress default language to Fr(CA) instead of FR.

Don't forget to update your language pack.

Thanks.
![exemple](https://user-images.githubusercontent.com/56609348/80480260-99444a80-8950-11ea-9f5b-0bbffb3fd54a.png)

**Comment by claudiosanches** [comment]
Fixed by #26339

**Comment by rambavd** [comment]
I still have this same problem on an Italian installation.
I tried everything, including clean install of localized wordpress.

**Comment by rambavd** [comment]
> Fixed by #26339

Still, as I commented a couple weeks ago, this issue is still present. What should I do? File a new bug report?

**Comment by nicomollet** [comment]
@claudiosanches Analytics screens still have many i18n strings missing. My locale fr_FR is 100% translated (woocommerce-admin is not fully translated though).
