### ISSUE TITLE
Widget filter products by attributes does not work correctly

### ISSUE THREAD

**Issue by choijun** [woocommerce/woocommerce#27419]
Hi dear,

Recently I updated WooCommerce to version 4.4.1 and I found the widget filter products does not work correctly

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I use Storefront theme and run on WordPress 5.5 and WooCommerce 4.4.1, I create an attribute "Color" with three options "Blue, Grey, Red" and I create variable product and setup the same price for all product variations

**Expected behavior**
The widget need to work correctly

**Actual behavior**

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'WooCommerce -> Attributes' and create the "Color" attributes with three options  "Blue, Grey, Red"
2. Create a new product variable with these options
3. And then setup the variation like as screenshot
4. Go to Appearance -> Widgets and drop a "Widget Filter Products by attribute" in "Sidebar" area
5. Go to Shop page and see 

**Screenshots**
![alt text](https://image.prntscr.com/image/eHUIDhZ5R2_39OFAOXucfg.png "Bug")
![alt text](https://image.prntscr.com/image/_2ad2O9GTMSLeyKhBAqRmA.png "Bug")
![alt text](https://image.prntscr.com/image/C-zTxGbwT4yIyh1Okszo1Q.png "Bug")
![alt text](https://image.prntscr.com/image/2RkY7xt4ToCMap80957SlQ.png "Bug")

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a [Storefront](https://woocommerce.com/storefront/) theme active 
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): http://localhost/theme-upgrade/payna
Site address (URL): http://localhost/theme-upgrade/payna
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.2
PHP Post Max Size: 128 MB
PHP Time Limit: 60
PHP Max Input Vars: 5000
cURL Version: 7.65.1
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 13.37MB
Database Data Size: 11.43MB
Database Index Size: 1.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 4.52MB + Index: 0.42MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.17MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 330
elementor_library: 39
nav_menu_item: 132
page: 38
post: 16
product: 123
product_variation: 1
revision: 10
shop_order: 1
wp_block: 2
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.4.1

### Inactive Plugins (11) ###

Akismet Anti-Spam: by Automattic – 4.1.5
Contact Form 7: by Takayuki Miyoshi – 5.2.1
Elementor: by Elementor.com – 2.9.14
Elementor Pro: by Elementor.com – 2.7.2
Envato Market: by Envato – 2.0.3
Hello Dolly: by Matt Mullenweg – 1.7.2
LA-Studio Core: by LA-Studio – 2.0.5
LA-Studio Header Builder: by LA-Studio – 1.0.5
LaStudio Elements For Elementor: by LaStudio – 1.0.4
Payna Package Demo Data: by LA Studio – 1.0.1
Slider Revolution: by ThemePunch – 6.2.19

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #3331 - /shop/
Cart: #3336 - /cart/
Checkout: #3343 - /checkout/
My account: ❌ Page does not contain the shortcode.
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 38
Oldest: 2020-08-14 08:54:40 +0000
Newest: 2020-08-20 05:19:00 +0000
</details>

**Comment by sjoerdstaal** [comment]
Having the same issue.

**Comment by antycamurcia** [comment]
Having the same issue.

**Comment by choijun** [comment]
Hi @sjoerdstaal @antycamurcia , My temporary solution for this is : Remove the line code 399 on the file **wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-layered-nav.php**
![alt text](https://image.prntscr.com/image/gDGHN_XsQLCnae4FvrKXLQ.png "Error")

**Comment by ntpixels** [comment]
Also seen and confirmed in 3242241-zen

**Comment by krona-prg** [comment]
Having same issue.  @choijun temp fix solved it. Thank you!

**Comment by choijun** [comment]
Hi @melindahelt 
You problem is exactly the same with the problem that I having while debugging. 
@Devon-Developer I agree with you, it seems that the sql snippet only finds data with specific attributes. My solution above is temporary solution. We need to confirm from WooCommerce Authors. I hope they will fix it soon

**Comment by Pab89** [comment]
Having same problem, thanks for the solution. Looking forward to a real fix! :)

**Comment by juliaamosova** [comment]
Hi @choijun,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end in WooCommerce 4.4 and 4.4.1. It works as expected in 4.3.3.  

My variable product setup:

![Screen Shot 2020-08-24 at 10 14 52 AM](https://user-images.githubusercontent.com/19143190/91055736-0e6c1780-e5f3-11ea-96f9-05e53d14e85a.png)

![Screen Shot 2020-08-24 at 10 15 00 AM](https://user-images.githubusercontent.com/19143190/91055746-12983500-e5f3-11ea-9ec1-ffb3dfd52940.png)

All the variations are set up the same way:

![Screen Shot 2020-08-24 at 10 15 15 AM](https://user-images.githubusercontent.com/19143190/91055760-175ce900-e5f3-11ea-8cc8-a46088fd648f.png)

`Filter by Attribute` widget appears in WC 4.3.3:

![widget_yes](https://user-images.githubusercontent.com/19143190/91056035-73277200-e5f3-11ea-8dec-dd8bfc78ef0b.jpg)

`Filter by Attribute` widget doesn't' appear in WC 4.4 and 4.4.1:

![widget_no](https://user-images.githubusercontent.com/19143190/91056055-77ec2600-e5f3-11ea-9b1e-a6a6f195154a.jpg)

We’re going to work on this bug as soon as possible.

**Comment by choijun** [comment]
@juliaamosova Thank you for your feedback, I really appreciate it . Please fix it soon because we have a lot of websites that need to fix

Thank you

**Comment by juliaamosova** [comment]
@choijun yes, we are making this a priority to work on. 

In the meantime, please note that the issue happens in one of the 2 cases:

- When one of the variations has no value assigned and instead uses `Any` option:

![any](https://user-images.githubusercontent.com/19143190/91071788-990a4200-e606-11ea-9465-ff5c02e1ae5f.jpg)

- When the attribute created within the product ([custom attribute](https://docs.woocommerce.com/document/managing-product-taxonomies/#add-custom-attributes)) as opposed to being a global attribute.

**Comment by Shiande** [comment]
I had the same issue and when i communicate the problem with support team they said they will fix it soon but now things are worst.
Today i noticed that all size attributions are removed from all products and customers cannot place orders.
Last picture after fixing the products attributes and variations as were before the issue.

![Picture1](https://user-images.githubusercontent.com/70254313/91263274-f8885f00-e778-11ea-8d4a-27a019571193.png)
![Picture2](https://user-images.githubusercontent.com/70254313/91263292-f920f580-e778-11ea-8583-5f260d6a90c5.png)
![Picture3](https://user-images.githubusercontent.com/70254313/91263306-f9b98c00-e778-11ea-82fe-a063a27c7857.png)
![Picture4](https://user-images.githubusercontent.com/70254313/91263335-fc1be600-e778-11ea-8a2d-098f12b0c553.png)

**Comment by michaelh83** [comment]
Having the same issue. Can confirm that temporary fix from @choijun works for now.

**Comment by jmancooldude** [comment]
Have the same issue. Filtering is fundamental to ecommerce user experience so hopefully it is fixed soon. Can I ask does Woo have a time frame for resolvement?

**Comment by MC-Rider** [comment]
Same/similar issue here. After updating to WP 5.5 (and then WooCommerce 4.4) any products imported in to my store do not display in attributes filters. Their attributes exist in the database and the products display in their category and on their product page just fine, but they are missing for all Woocommerce attribute filter widgets. (Brand, Color, Size...)

Products imported prior to these updates continue to display and function normally. FWIW my last correctly functioning products were imported prior to Aug 4, 2020.

(Hate that this is happening but SO relieved to find out it is not just me!)

**Comment by atikullamerchant** [comment]
Have a similar issue, temporary fix from @choijun works for now.
Having said that, has anything broken for anyone after implementing this temporary fix? My site looks good so far but its good to have a heads up!

**Comment by zhollenbeak** [comment]
Another report in 3251398-zen - that workaround was to roll back to v4.3.2.

**Comment by rosimannus** [comment]
same issue here.. updated to latest version and only old products have correct filters.

**Comment by vinnykaur** [comment]
One more report here 3277108-zen.

**Comment by midi9x** [comment]
> Hi @sjoerdstaal @antycamurcia , My temporary solution for this is : Remove the line code 399 on the file **wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-layered-nav.php**
> ![alt text](https://camo.githubusercontent.com/604b5a5f3528dec84eca3d7c0aa674ae127c6283/68747470733a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f674447484e5f5873514c436e6165344676724b584c512e706e67)

Same issue. Confirm temp fix from @choijun work.

**Comment by MC-Rider** [comment]
Reverting to WooCommerce v4.3.3 appears to have fixed the problem for me. I tried removing code line 399 in v4.4.1 as mentioned above and that did not solve my problem (that I described above). 

Question: Not sure if this is a related issue or not — I just noticed today that pagination on my main Shop page only is not working correctly. From the main Shop page, Page 2 and onward show no products but do show Categories as normal. Pagination from Category pages is working as normal, the issue exists only on the main Shop page.

Has anyone else noticed this? Or is this an issue of my own? Wondered if perhaps there was some sort of common error behind both the Shop page pagination missing products issue and the attribute filters missing products issue. Thx.

**Comment by juliaamosova** [comment]
Hi everyone who is experiencing the issue in this thread 👋 . Today we released [WooCommerce 4.5 RC3](https://developer.woocommerce.com/2020/09/03/woocommerce-4-5-release-candidate-3/) which contains the fix for the widget issue. If as many of you could test the fix and let us know how it goes for you, it will be very helpful. 

Please note that we always recommend testing on the staging (copy of your live site) environment and never on the production site. 

If you want to set up a staging site quickly, you can use [WP Staging](https://wordpress.org/plugins/wp-staging/) plugin or contact your hosting company to learn how you can create one. 

The easiest way to get the WooCommerce 4.5 RC3 release is by using [WooCommerce Beta Tester](https://wordpress.org/plugins/woocommerce-beta-tester/) plugin. Once installed, you'd see an option to switch to WC 4.5 rc3. 

If you'd test, please report your findings here. Thanks in advance!

**Comment by sjoerdstaal** [comment]
Unfortunately still not working as expected, the count of the filters (attributes) is off, with a total of 1856 products, it is weird that there are over 3000 '2ch' products available. 

![image](https://user-images.githubusercontent.com/215978/92106464-b9938280-ede4-11ea-9f60-5011b278931a.png)
 
Also after selecting a filter, for example Jazz in Genres, all other attribute filters disappear.  

![image](https://user-images.githubusercontent.com/215978/92106358-9072f200-ede4-11ea-9a38-9c96bd5753b8.png)

**Comment by juliaamosova** [comment]
Thanks for testing and reporting back here @sjoerdstaal! We are working on the follow-up fix.

**Comment by kylemcph** [comment]
Another report here: 3266408-zen

**Comment by MC-Rider** [comment]
Sorry to report no change for me. I have screen shots of the following if you would like me to post them. 

1) Products added to the shop while running v4.4.x do not appear in attribute filters. Products added under v4.3.3 and earlier do.
2) Where there is a mix of products (on the main shop page or in a category), pre-v4.4.x product attributes appear, post-v4.4.x do not.
3) Where all products are post-v4.4.x the attribute widgets hide as appropriate when no attributes exist. (Even though the products do have attributes so widgets should be active.)
4) All product attributes are present in the database.
5) All products can be found via search.
6) All product pages are normal.
7) Reverting to v4.3.3 resolves the problem. All products appear in attribute filters as expected.
8) No change when deactivating all plugins except WooCommerce and Wordpress.

----
One other bug I'm experiencing that I am not sure is related to this issue or if is just something local to me (I am still testing here) but both involve products not appearing — pagination on the main Shop page is normal on Page 1 and shows the correct number of additional pages in the navigation at the bottom of the page, but Pages 2, 3, 4, etc... return no products, only categories (if set to show categories and products), and show a blank page if set to show products only.

Pagination is 100% normal on category pages. This is only an issue on the main Shop page.

Not sure if this might provide some sort of clue to those of you who know more about WooCommerce coding than I do.

Hope this helps.

**Comment by B-Anders** [comment]
Stumbled on the filter issue with some differences and also **found a workaround** for my situation:
I need one attribute that will be used for filtering (with the attribute filter widget) and another attribute used for variations.

The problem is that, I can only pass one of the attributes to variations, the other is not allowed to generate any variation option. But the attribute missing from variations won't show in the filter widget at all - if it's the only one, the whole widget won't show!

I tested with a second product having that "missing" attribute and now the widget shows again and has the attribute as expected. It even filters correctly showing both products.

**The workaround:** I check the boxes on both attributes for variations, generate all the variation combinations, and as expected, the filter shows my attribute and the variation options on the product single page have that attribute that I don't need. Now I go and uncheck the 'use for variations' box for that attribute that shodn't generate variations and the result is as expected. Variations are only from the right attribute and the now unchecked attribute is showing just fine in the filter widget.

This is odd, just check the box, make variations and then uncheck the box and the filter works...

I hope someone has a better workaround then mine, because I can't pass that to my client and the shop is due next week.

**Comment by vedanshujain** [comment]
reopening based on recent comments

**Comment by midi9x** [comment]
On shop page it working fine, but on product category not working, product filter not show :(

**Comment by rosimannus** [comment]
Just updated to 4.5 and still same issue. I have 3 different filters (brand, color, size). Only color seems to work correctly. Brands are shown but after selecting 1 of them then other filters will disappear and only some of the products are shown. Size filters show just one size nr 38 and thats it :D.

**Comment by mixalisen** [comment]
Hi guys, 
same here. Just installed the new version 4.5.0 and the problem still exists. I use a temporary fix like Florent mention:

QUICK FIX :
plugins/woocommerce/includes/widgets/class-wc-widget-layered-nav.php

Line 362, Replace :
$exclude_variable_products_tax_query_sql = $this->get_extra_tax_query_sql( 'product_type', array( 'variable' ), 'NOT IN' );

By :
$exclude_variable_products_tax_query_sql = $this->get_extra_tax_query_sql( 'product_type', array(), 'NOT IN' );

**Comment by grigorijurasov** [comment]
@juliaamosova hi, I've got a question.

The changelog says this for WooCommerce 4.4:

* The filtering widget now works as expected with variable products, displaying those products for which visible variations are available. #26260

In this older report though, we decided not to fix that:

https://github.com/woocommerce/woocommerce/issues/24331#issuecomment-577662456

Am I right to assume the out-of-stock variations will not be shown in the Filter Products by Attribute widget once this is addressed?

I'd assume it is supposed to hide out of stock variations already in Woo 4.5.0 but I can't test since the widget doesn't show up as well with new products.

I could revert to older Woo, add a variable product, update and test if that is necessary.

**Comment by Konamiman** [comment]
Hi all,

I'm sorry for all the inconveniences caused. At this point it's clear that I didn't implement [the improvement for filtering out of stock variations](https://github.com/woocommerce/woocommerce/pull/26260) properly.

Given all the trouble this is causing, we're going to publish as soon as possible a fix release for WooCommerce 4.5 that reverts the feature, so the widget will work as it was in 4.3; restoring the old functionality of the filtering widget is going to be way easier than trying to apply fix after fix to an implementation that is already quite complex.

After that revert is in place we'll think of a different approach to re-implement the feature in a future version of WooCommerce, but this time taking in account all the things that can go wrong as you all have pointed out. Thank you very much everybody for your feedback.

**Comment by B-Anders** [comment]
Hey @Konamiman ,
only those who don't do the work can't make mistakes.

For myself - and those with a similar problem - I found that the WOOF filter plugin does it's own counting and therefore works ok.

Thank you for your time.

**Comment by websyflex** [comment]
Same here on several coocommerce shops. Hope there will be a fix very quickly as customers can't filter on color, material etc etc.

**Comment by AzhulCobalto** [comment]
Same problem here, the filter by attribbute not showing after updating woocommerce to the latest version, everything was working fine before the update, I had categories and attributes configured and both were ok, now I can only see the categories filter, my clients can't filter clothing by "size" :( 
<img width="362" alt="Screen Shot 2020-09-08 at 11 56 03 PM" src="https://user-images.githubusercontent.com/71108861/92837912-2510bd80-f3ac-11ea-9089-0e4c54e5843c.png">
<img width="341" alt="Screen Shot 2020-09-08 at 11 55 13 PM" src="https://user-images.githubusercontent.com/71108861/92837956-33f77000-f3ac-11ea-9f12-be1e10bd505c.png">

**Comment by stevetested** [comment]
Another report here: 3302992-zen

**Comment by rosimannus** [comment]
Updated to 4.5.1 and still same issue :(

**Comment by anant1811** [comment]
Another report in 3313994-zen

**Comment by juliaamosova** [comment]
Hi everyone! 

We released [WooCommerce 4.5.2](https://developer.woocommerce.com/2020/09/14/woocommerce-4-5-2-fix-release/) just now - it contains the fix for the issue with the `Filter by Attribute` widget. Essentially, we rolled back to the way it used to work in WooCommerce 4.3. 

Please update to WooCommerce 4.5.2 and let us know if you are still experiencing any issues. Thanks for testing and for your patience everyone!

**Comment by krona-prg** [comment]
It works fine in my dev. site with 4.5.2. 
Thank you!

**Comment by mixalisen** [comment]
Hi Julia,
everything works as it should. Thanks for the fix.

**Comment by juliaamosova** [comment]
Thanks for testing and reporting that the issue had been resolved for you @krona-prg and @mixalisen! At this point, I am closing this thread. However, please continue leaving comments in case anyone experienced any issues.

**Comment by MC-Rider** [comment]
Hi everyone — v4.5.2 appears to have fixed the attributes filters issue for me. Thank you to everyone on the WC development team for all the hard work! Much appreciated.

However, in other news... 

The issue I am having with pagination on the main Shop page persists (this is only the main Shop page pagination. Pagination on Category pages works just fine) — On the main Shop page, all 17 additional pages appear as they should in the pagination navigation at the bottom of the page, but visiting Page 2 or any of the other 17 pages show no products, only sub-categories. — Is anyone else experiencing this or is this my own special problem?

This is happening on two separate installations of the same website. I have turned off all plugins except WooCommerce, tried using the 2020 theme, all other standard debugging steps, and the problem persists regardless of what I do. 

I am at a loss... Thx.

**Comment by juliaamosova** [comment]
Hi @MC-Rider,

>Hi everyone — v4.5.2 appears to have fixed the attributes filters issue for me. Thank you to everyone on the WC development team for all the hard work! Much appreciated.

Thanks! Glad to know the attributes filter widget issue had been resolved for you. 

>However, in other news...

>The issue I am having with pagination on the main Shop page persists (this is only the main Shop page pagination. Pagination on Category pages works just fine) — On the main Shop page, all 17 additional pages appear as they should in the pagination navigation at the bottom of the page, but visiting Page 2 or any of the other 17 pages show no products, only sub-categories. — Is anyone else experiencing this or is this my own special problem?

Please open a new issue for this so we could investigate it further.

**Comment by agl99** [comment]
Hi @juliaamosova,

I'm using WordPress 5.5.1 and WooCommerce 4.5.2. Others in this thread says it's resolved in 4.5.2 but I couldn't make it work. What am I missing here?

![Widgets](https://user-images.githubusercontent.com/72689233/95677670-d774b400-0be8-11eb-80c5-827b0c92e7fe.png)

![Attributes](https://user-images.githubusercontent.com/72689233/95677663-c4fa7a80-0be8-11eb-9127-fb48e8059eae.png)

![Variations](https://user-images.githubusercontent.com/72689233/95677672-df345880-0be8-11eb-8e2b-f4972508826d.png)

**Comment by choijun** [comment]
Hello @agl99 

This is because you are using the custom attributes, If you want the attribute display on the widget, you need to create global attribute on Products -> Attributes . You can read more [here](https://docs.woocommerce.com/document/managing-product-taxonomies/#section-6)

Hope this help you

**Comment by MC-Rider** [comment]
The missing attribute problem (in my case the brand attribute) seems to have returned in v4.6.0... I reverted to 4.5.2 and all is well again. Anyone else having this issue?

**Comment by bergmans23** [comment]
hello there,
I'm running 4.6.1 and I'm still having this problem. Filter by attribute: colour no problem but Filter by attribute: size does not work. All variable products, all global attributes, tested with Storefront theme and all plugins deactivated, but I don't get any closer to a solution!

**Comment by Tahoooe** [comment]
Having the problem here too with 4.6.2.

**Comment by juliaamosova** [comment]
Reopening this thread to take a look further since we've got more feedback.

**Comment by MC-Rider** [comment]
Thank you Julia.

Since we are taking a fresh look at this, here is a more detailed description of what I am experiencing. Most all of it is covered earlier in this discussion.

BASELINE: 
Everything has been working perfectly for me in v4.5.2 — with the one exception of pagination on the main shop page: products display correctly on page  1, no products display on pages 2, 3, 4 etc., however categories do. (This has been the case for me before and after v4.5.2. I haven't had time to submit it as it's own bug. I mention it here for full info and because I don't know if it might be a related issue or not.)

RETURNING ISSUES (from prior to the v4.5.2 fix):
1.) Products (and their attributes) entered or imported using the earlier correctly functioning version of WooCommerce (prior to v4.6.0 in this case) continue to behave and display as they should.

2.) New products (and their attributes) entered or imported using v4.6.0 do not display in the front end — they are in the database, they appear in the back end, their attributes are entered correctly, they can be found in a search, but the products and their attributes do not appear in the front end.

ie. For a new product with a new brand — everything appears as it should in the backend. But the Product does not appear on the front end shop pages and the Brand does not appear in the Brand Attribute Filter's list of brands.

That's all I've got for now. In the next few days I need to start adding numerous products to my store. If I notice any other oddities I will report them here.

If I can provide any additional info please let me know.

Thanks again!

**Comment by John1128** [comment]
Hi juliaamosova. 
How are you? These days I am developing ecommerce website using woocommerce v4.6.1. But if I add Filter Products by Attribute section to the sidebar, unfortunately, I can't see that, and I checked html using Inspect on web browser, but Attribute section is not added. Of course, you got too many message regarding this problem, so did you fix this problem or not? If not, when can you fix it and how to fix it? I am waiting for your reply.
Thank you, Shang.

**Comment by MC-Rider** [comment]
Happy to report that for me this appears to be fixed in v4.6.2.

Created new simple products, variable products, and brands. All are appearing in the front end and behaving as expected.

The other issue I mentioned (products appearing on first "shop" page but not appearing on shop pages 2, 3, 4... etc) remains. Pagination index and bottom of page is correct it's just pages 2, 3, 4, etc are not populating with products. I have tested this using other themes and with only Wordpress and WooCommerce active with no change.

Hope others are having a similar experience.

**Comment by roykho** [comment]
Seems the consensus is that this issue is fixed. I will close this issue now. @MC-Rider as for your pagination, that doesn't seem to be related so I suggest you open a new issue for that.

@John1128 - please update to the latest WooCommerce version.

**Comment by TheGranadilla** [comment]
Hi,
No, it's definitly unfixed.

The widget will still return out of stock variations......

Common, Woocommerce is a leading solution, we need the widget to return only Instock products!
Can't believe I still can't perform a simple action like : Filter and return T-shirts in size : Small.

#26260

**Comment by Pinners27** [comment]
I still have the same problem... selling wood sheets cut to size and can't filter by thickness. all of my products have thickness attributes so not sure why it's not.

**Comment by alchemizt** [comment]
I'm having this issue on the latest version (4.8.0). The woocommerce_product_filter_category filter works fine. The woocommerce_product_filter_attribute doesn't work, it displays nothing. I have globally setup attributes such as color and background. I really need to let users filter by these attributes because that's what makes the website useful

**Comment by AzhulCobalto** [comment]
so sad woocommerce keeps having this same issue almost on every update, I'm seriously thinking changing to shopify and forget about this issues.

**Comment by juliaamosova** [comment]
Reopening this issue due to the recent feedback in order for us to take a look further.

**Comment by alchemizt** [comment]
When I use the plugin Themify – WooCommerce Product Filter, the attributes filter works fine

**Comment by MC-Rider** [comment]
Hi all — I just updated to v4.9 and tested it by creating a new Simple Product, a new Variable Product (with color and size variations), plus a new v4.9 Test Brand attribute. Everything seems to be working as expected for me. Attributes are appearing on store pages and in filters and from what I can tell are functioning as expected. If anything unusual happens I will follow up here. Cheers.

**Comment by TheGranadilla** [comment]
@MC-Rider Set one of your variation as out of stock. Then, go front and filter products : You'll have your out of stock variation returned.

**Comment by MC-Rider** [comment]
> @MC-Rider Set one of your variation as out of stock. Then, go front and filter products : You'll have your out of stock variation returned.

Hey TheGranadilla  — I think what you are referencing is a different issue from what has been discussed in this thread, but I will let others chime in on that. The problem that I was experiencing and that we were trying to fix here was products and attributes missing from the front end entirely. 

Nonetheless, I tried to replicate what you mentioned and was not able to do it in my store. My out-of-stock product variation did not appear. Have you double checked your WC settings in the Products > Inventory > Out Of Stock Visibility " Hide out of stock items from the catalog" is selected? 

That said... I have had other instances where occasionally a variation is out of stock and does not hide as it should, but in my case I would have to look at that behavior much more in-depth to be certain it is not stemming from a different plugin (which in my case I think it is).

Hope this helps.

**Comment by the0rist** [comment]
The issue is still present in 4.9.2

**Comment by justanotherco** [comment]
Also still happening for me...... The widget doesn't appear even though everything is set up properly... Come on WooCommerce, issue was opened about 6 months ago!

**Comment by Pab89** [comment]
Still also a major problem here, I now have multiple clients complaining about the functionality.

I really think this needs attention ASAP, you really feel like a lousy developer when you have to tell clients something as essential as this can't be fixed within 6 months. I get that Woocommerce is free, but together with it, we have bought multiple of your paid products for multiple clients.

**Comment by brendamm** [comment]
It's still not fixed in Woocommerce 5.0 ... the product attributes filter still does not show up. Can someone please provide some help?

**Comment by eoinkennedy** [comment]
So, I managed to fix it after hours of uploading and deleting products.

Here are my steps:
1. Export all products to CSV, and create two new ones for the parents and the children, but make sure to set Attribute 1 Global to 1 for all. 
2. Delete all existing products.
3. Import the Parent CSV.
4. Go into wp_postmeta table and using HeidiSQL or similar, find and replace all instances of this substring '%is_variation";i:0;s:11:%' with '%is_variation";i:1;s:11:%'.
5. Upload the Variations CSV file with the link to the parent SKU and Attribute 1 Global set to 1.

**Comment by JustineCrenier** [comment]
Still not fixed in woocommerce 5.1, and temporary fix doesn't work anymore. Does anyone have a solution ? I don't want to reupload all the product

**Comment by awesome1128** [comment]
It's sucks

**Comment by friendorfoley** [comment]
I am also having this issue, it was working before the latest update.

**Comment by ccobuzziOV** [comment]
I was just notified that we are having the same issue.  Cannot select colors on the shop page.   Colors show but cannot click on them or add to cart.  Tried all the suggested fixes and work arounds and nothing.  Please issue a fix ASAP.

**Comment by MC-Rider** [comment]
In the latest WC version (5.1.0), I noticed that when I create a new Variable Product it does not appear in the front end initially (but is normal in the backend)... HOWEVER... I found that if I refresh the product's variables (click Save Changes and then update the product), it then appears in the front end and functions as normal.

I am running the latest versions of Wordpress, WooCommerce, and the Flatsome theme.

Hope this helps.

**Comment by ccobuzziOV** [comment]
@MC-Rider - Thank you for the suggestion.  This is happening on products we had for a couple of years and have not changed.  Just tried refreshing the variables and did not work for me.  Running latest version of Wordpress, WooCommerse and Astra Theme.

**Comment by ahmad-ali14** [comment]
still not working v5.3

**Comment by deb1122** [comment]
is this high priority? still waiting for it to be fixed!!

**Comment by Ys-sudo** [comment]
Same problem here > woocommerce 5.4.2, wordpress 5.7.2, storefront 3.5.1 :/

**Comment by tiendungdev** [comment]
still not working v5.6

**Comment by vedanshujain** [comment]
cc @konamiman to see if this can be addressed by our recent feature for the attribute filtering table.

**Comment by awesome1128** [comment]
Okay

**Comment by myko83** [comment]
I suspect that woocommerce has blocked it and wants us to buy their own widget as there is an option to filter product by attribute from woocommerces and it does come up on the filter area, however it is not active further on they're asking to install it.
![Screenshot 2021-09-18 at 15 52 19](https://user-images.githubusercontent.com/7107291/133893843-6fb86d0b-39b2-4a32-b5fb-309734772dcc.png)

**Comment by jbrogaard** [comment]
How so very unprofessional WC :(

**Comment by Konamiman** [comment]
Hi @choijun and everyone, I'm unable to reproduce this with the provided testing instructions on a brand new shop with WooCommerce 5.8, see screenshots below.

This is not to say that the problem doesn't exist, but clearly I'm missing something in my testing context. It would be great if someone could provide me with either a product export or admin credentials for a testing site where the issue manifests. Please contact me at nestor.soriano@automattic.com for that.

![image](https://user-images.githubusercontent.com/937723/140706756-5c03c4ac-944d-4da0-8f57-a9981c817862.png)

![image](https://user-images.githubusercontent.com/937723/140706814-9be3abeb-5537-4e09-bfd1-0b41a0b6be21.png)

![image](https://user-images.githubusercontent.com/937723/140706856-3f4781e4-7a6a-4afb-9baf-5fb56eb04322.png)

![image](https://user-images.githubusercontent.com/937723/140706966-2c77b4fe-df20-44f8-bc10-638370cc3ef6.png)

**Comment by choijun** [comment]
Hi @Konamiman and everyone

I am sorry for late response because I haven't been online for a long time, currently I haven't using the new block filter yet. But I get many bugs when installing the WooCommerce 5.9 and most especially the problem related to Block API . I also opened a new ticket on WordPress.org https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-undefined-method-wp_errorget_data-4/ and I hope someone will take a look at this.

Also, for the main filter issue. I will test the conditions again and let you know soon.

Have a nice day and best regards,
Jun.

**Comment by pedlima** [comment]
Any news on this? Because unbelievably it seems that the issue still persists!

**Comment by ccobuzziOV** [comment]
I am still having issues as well though they closed this.

**Comment by peterfabian** [comment]
Hello folks, unless we can reproduce the issue, it's very difficult for us to fix. If you can reliably reproduce this on a new install, please include the steps, or contact @konamiman as he detailed in the comment above. Thanks.

**Comment by wootangcommerce** [comment]
im on a fresh version of wordpress for a new website and my shop page or any page actually doesnt display the filter by attribute widget, it shows up as blank. categories work ut not attriutes

**Comment by Aar0naut** [comment]
I'll add another to the "does not appear" tally, it's just a blank box. I'm honestly not experienced enough to be able to follow all the code editing work-arounds or properly troubleshoot. Just need this to work, and it's discouraging seeing this problem has been around for so long.

**Comment by Yasen** [comment]
I also have this issue. The widget Filter Products By Attribute does not show on the front end. WooCommerce version 6.3.1. WP version 5.9.2.

**Comment by xaviercshp** [comment]
I dont know why I was having the same issue. I added a var dump on top of the html output filter and that somehow fixed things its bizarre. I removed the var_dump and things remained fixed.

**Comment by Yasen** [comment]
I also did some dumps and things worked out. But noticed that on change of attribute name, it does not change in some tables and this is confusing.

**Comment by razorfrog** [comment]
Also seeing this. We're using the widget through the Classic Widgets / older system. Did the move to Blocks break this functionality?

**Comment by MFsmart** [comment]
I had the same problem today, after updating woocommerce to 6.3.1. Iv made a roll back to 6.2.2 and the filter attributes in the widget appear again in the frontend Why is this not fixed yet?

**Comment by xaviercshp** [comment]
I believe the issue is in the `Automattic\WooCommerce\Internal\ProductAttributesLookup\Filterer->get_filtered_term_product_counts` function that grabs the counts. throwing some dumps I notice that function returns the wrong counts which causes the terms not to display. for me this is is how the query ends up running. it does have the complete number of term ids and they all have products attached to them so they all should display. I obfuscated the prefix in this query just in case.

`SELECT COUNT(DISTINCT product_or_parent_id) as term_count, term_id as term_count_id
FROM prefix_wc_product_attributes_lookup 
INNER JOIN prefix_posts
ON prefix_posts.ID = prefix_wc_product_attributes_lookup.product_or_parent_id 
WHERE prefix_posts.post_type IN ( 'product' ) 
AND prefix_posts.post_status = 'publish' 
AND ( prefix_wc_product_attributes_lookup.product_or_parent_id NOT IN ( 
SELECT object_id 
FROM prefix_term_relationships 
WHERE term_taxonomy_id IN (342) ) ) 
AND prefix_wc_product_attributes_lookup.taxonomy='pa_subject' 
AND prefix_wc_product_attributes_lookup.term_id IN (400,100,99,101,102,103,415) 
GROUP BY prefix_wc_product_attributes_lookup.term_id`

**Comment by xaviercshp** [comment]
alright I was able to fix this issue base on my comment above I figured maybe the issue is the data in the lookup table( this became more apparent when I forced some terms to show and tried to filter by them and no products would show even when they should the lookup table shows again on the store main query when filtering ) so I went to see if I could update the database or somehow regenerate its data and thankfully I realize woo has just the tool for that here wp-admin/admin.php?page=wc-status&tab=tools. in there my suggestion is to at least run the "Regenerate the product attributes lookup table" and the "WooCommerce transients". the counts get saved on a transient so thats why you should clear those after regenerating the attribute lookup table. Other possible ones you might need to recreate to but cant confirm are the "Product lookup tables" and "Term counts". hope this helps others having this exact issue. Kind of surprise that wasn't suggested in this thread already.

**Comment by razorfrog** [comment]
> alright I was able to fix this issue base on my comment above I figured maybe the issue is the data in the lookup table so I went to see if I could update the database or somehow regenerate its data and thankfully I realize woo has just the tool for that here: "Regenerate the product attributes lookup table" 

@xaviercshp Works! That seems really obvious in hindsight. Thanks for pointing it out!

**Comment by MFsmart** [comment]
Yes it works! Thanks!

**Comment by DenverTK** [comment]
I fixed it by unchecking the **Enable table usage** in Woo Settings->Products->Advanced

**Comment by dizzyza** [comment]
> I fixed it by unchecking the **Enable table usage** in Woo Settings->Products->Advanced
This worked for me too!

**Comment by TawabG** [comment]
> I fixed it by unchecking the **Enable table usage** in Woo Settings->Products->Advanced

As of 01/04/2022, this worked for my webshop as well!

**Comment by coos-max** [comment]
> I fixed it by unchecking the **Enable table usage** in Woo Settings->Products->Advanced

Thanks! This worked for me! 
After hours searching for the problem and solutions ;-(

**Comment by vietvuong139** [comment]
I just updated to WooCommerce 6.4.0, and none of the solutions above works. The only way that the filters show up again is to manually delete the attributes and insert again on each product. I have tried exporting the products and change the global attribute from 0 to 1 and import again. But it doesn't work. Anyone has a solution? 

Thanks!

**Comment by MC-Rider** [comment]
I just updated a website to the new Flatsome v3.15.5 (from the previous version of Flatsome where everything was working perfectly) and encountered this exact problem - all product attributes disappeared from the sidebar filters and where the attribute count was now read as zero the filters did not display. Gone. Happy to say the "uncheck Enable Table Usage" fix reported above worked in a second. Thank you!!! 

As so many people use Flatsome I have reported this to the Flatsome team.

**Comment by Solarbotics** [comment]
Confirmed that coos-max's comment fixed a similar error I had after updating plugins on May 12 2022 (Woo version 6.5.1 / WP version 5.9.3) 

Deleting my cache, then selecting a category would set the filter list for ALL subsequent product navigations. Then again deleting the cache would fix it _for one navigation click_. I was using the filters mainly to display subcategories.

Disabling the "enable table usage" totally corrected this issue. The [table ](https://developer.woocommerce.com/2022/02/02/new-product-filtering-by-attributes-rolling-out-in-woocommerce-6-3/)sounds like a great feature; can't wait to try it again when it's debugged!

**Comment by Robbbbbbbbb** [comment]
> I fixed it by unchecking the **Enable table usage** in Woo Settings->Products->Advanced

I did not expect this to fix a two year old issue, but it totally did. Thanks!!

**Comment by peterfabian** [comment]
> I fixed it by unchecking the Enable table usage in Woo Settings->Products->Advanced

Just please note this disables the lookup table for products, so you might experience slower responses for some queries. Still better than no results or incorrect results, though.

**Comment by razorfrog** [comment]
> I fixed it by unchecking the Enable table usage in Woo Settings->Products->Advanced

This has worked for me, but the checkbox somehow becomes re-checked after a month or two and the issue returns. Anyone else seeing that?

**Comment by peterfabian** [comment]
Just a note for the people arriving here later. 

There was a bug that caused the product attribute lookup table to be left empty after updating WC, but that has been fixed with https://github.com/woocommerce/woocommerce/pull/32893 and it was released in WC 6.6.0.

If you are experiencing similar problems, we suggest you first try to 
1. Verify you have all the db tables created properly via WC > Status > Tools
2. Regenerate product attribute lookup table, again via WC > Status > Tools

![Screenshot 2022-06-23 at 10 57 39](https://user-images.githubusercontent.com/2207451/175260539-1e34c480-cef2-44e5-a1f6-d786ceea8358.png)

This should fix your problems and if it doesn't please let us know. Thanks!

**Comment by evilgodhedgehog** [comment]
Same error WC 6.7.0. Does not display filters in the sitebar. Your suggestions didn't solve the problem.

**Comment by evilgodhedgehog** [comment]
> Just a note for the people arriving here later.
> 
> There was a bug that caused the product attribute lookup table to be left empty after updating WC, but that has been fixed with #32893 and it was released in WC 6.6.0.
> 
> If you are experiencing similar problems, we suggest you first try to
> 
> 1. Verify you have all the db tables created properly via WC > Status > Tools
> 2. Regenerate product attribute lookup table, again via WC > Status > Tools
> 
> ![Screenshot 2022-06-23 at 10 57 39](https://user-images.githubusercontent.com/2207451/175260539-1e34c480-cef2-44e5-a1f6-d786ceea8358.png)
> 
> This should fix your problems and if it doesn't please let us know. Thanks!

Same error WC 6.7.0. Does not display filters in the sitebar. Your suggestions didn't solve the problem.

**Comment by Pinners27** [comment]
Yeah - same, done all of the above, and still nothing on this page

https://cnccreations.co.uk/other-services/cutting-services/melamine-cut-to-size/

**Comment by peterfabian** [comment]
If you still experience the problem with the widget not showing up, I suggest creating a new issue where you describe your product/attribute setup. Since we can't reproduce this in our dev environment, we can't really help much until we do. Thanks for understanding!

**Comment by Mgiannig** [comment]
Hello, I'm having the same issue.
got this product with attributes 
![image](https://user-images.githubusercontent.com/27159992/188681146-2ca6b130-a2aa-438c-83a3-06e646b5139d.png)

On my customizer I add Filter products by Attribute widget

![image](https://user-images.githubusercontent.com/27159992/188681351-51310ce8-8732-4bfb-a585-cecad5d4a5ef.png)


Only filter by price is showing. No console errors tho 

![image](https://user-images.githubusercontent.com/27159992/188681592-a8ab28d1-3a5d-4fa0-9747-7209ab67d57e.png)

**Comment by midrocketdev** [comment]
Hi, this issue is happening again. In the main shop the filters show correctly but when entering a category the filters don't show up. Any ideas?

**Comment by jdoles** [comment]
The issue is still present on default WC installations with no plugins.  While customizing the theme, you can see that the block does not appear.  
![theme-editor](https://user-images.githubusercontent.com/5995756/197395787-27b262d9-fec7-4ae8-b88a-7da601cd0f44.png)

When loading the shop page, you can see the block starts to load but disappears.  I have a case open in which support stated they could not reproduce the issue in their lab.

**Comment by midrocketdev** [comment]
@woocommercebot @peterfabian any ideas why attribute filters (widgets, left sidebar) show up in the shop page but not in category pages?

Example:

Shop -> https://www.rugstk.com/shop/
Product category -> https://www.rugstk.com/category/rugs/indoor-outdoor/

Thank you

**Comment by poof86** [comment]
For me the filters disappear when I use the Products for Category Block. The filters only show up when I place a All Products Block...

**Comment by AlanEGrant** [comment]
The Filter By Attribute Block does not work with the Products By Category block for me either. Are these blocks intended to function together? Or are the filter blocks limited for use on only the shop page? 

Edit: When I append the filters in the query string to the page with Products By Category by hand, I can see that the block does not honour them either. If neither the Products By Category accepts filters and the Filter By Attribute block is inoperable with it, I would think this is an intentional design decision for how these blocks are intended to be used on the page. 

That would be seriously unfortunate, as I would like to present customers with a list of products already trimmed down to the category relevant to the page they are on that they can then apply additional filters to. 

Edit: The Filter By Attributes block also works as expected on the category template, which at least covers the functionality described above. However, I was hoping to provide that functionality on landing pages with diverse layouts in accordance to what some of these categories describe, as they appeal to different demographics. 

I can see while exploring the files that `has_filterable_products` gets passed into the the asset data registry for `AllProducts`, but not for `AbstractProductGrid` (the class that the Products By X blocks all inherit). Adding this line to the latter file will allow the filter blocks to render, but they will not work, which I'm taking to suggest means this line is there to hide it for that very reason. Are there plans for these Products By X blocks to use filters in the future?

**Comment by GeorgeFR21** [comment]
Hello there! WC 7.6 version and the issue still persists. How is this possible?

The widgets get back to normal only when unchecking the Enable table usage in Woo Settings->Products->Advanced. However, is this what WC team wants to happen here?

**Comment by charamirror** [comment]
Same here, I had the same issue. Unfortunately, none of the above method works for me. Help me..... 

[https://.flotanar.com](https://.flotanar.com)

**Comment by betayazilim** [comment]
That is weird. Old classic widgets are working great. Counting correct number of products under certain category.
I add new block widget and they all show wrong figures.

**Comment by cerxun** [comment]
> Подтверждаю, что комментарий coos-max исправил аналогичную ошибку, которая была у меня после обновления плагинов 12 мая 2022 года (Woo версии 6.5.1 / WP версии 5.9.3)
> 
> Удаление моего кэша с последующим выбором категории установило бы список фильтров для ВСЕХ последующих переходов по товарам. Затем повторное удаление кэша исправило бы это _за один клик навигации_. Я использовал фильтры в основном для отображения подкатегорий.
> 
> Отключение "включить использование таблиц" полностью исправило эту проблему. [Таблица ](https://developer.woocommerce.com/2022/02/02/new-product-filtering-by-attributes-rolling-out-in-woocommerce-6-3/) кажется отличной функцией; не могу дождаться, чтобы попробовать ее снова, когда она будет отлажена!

Its right.

**Comment by Hazmosis** [comment]
@GeorgeFR21 this worked for me!

> Hello there! WC 7.6 version and the issue still persists. How is this possible?
> 
> The widgets get back to normal only when unchecking the Enable table usage in Woo Settings->Products->Advanced. However, is this what WC team wants to happen here?
