### ISSUE TITLE
meta-boxes-product-variation.js file get_variations_fields function issue

### ISSUE THREAD

**Issue by marke123** [woocommerce/woocommerce#27442]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Variation settings do not save when editing a variation a field name that represents an array. For example something like this:

name="var_min_max_rules[0][max][1]"

This results in a JS error when clicking the Save Changes or Update buttons: 

Uncaught Error: Syntax error, unrecognized expression: [name="var_min_max_rules[0][max][1]""]

**Expected behavior**
There should not be an error thrown

**Actual behavior**
Uncaught Error: Syntax error, unrecognized expression: [name="var_min_max_rules[0][max][1]""]

get_variations_fields() in meta-boxes-product-variation.js causes this problem. 

Variations do not save.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Edit variation
2. Ensure you have a plugin or custom code that adds a HTML field with a name that represents an array. 
3. Enter a value into the field 
4. Try to save changes. 

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WP 5.5
WC 4.4.1
</details>

**Comment by juliaamosova** [comment]
Hi @marke123,

Thanks for reporting the issue. However, I am missing a few steps to reproduce it. 

>Ensure you have a plugin or custom code that adds a HTML field with a name that represents an array.

Would you please either provide the name of the plugin or the exact code that you use to replicate the issue further?

Thanks!

**Comment by juliaamosova** [comment]
Hi @marke123,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Comment by SevenAcreFarm** [comment]
This issue is still not resolved, and has persisted for over two months at this point. Reading @marke123 's comments above it seems clear what needs to be tested. The plugin is "WooCommerce Min Max Totals and Quantities" Version 2.1.12 | By IgniteWoo. 

From my understanding the issue resides on the WooCommerce side and is not something that can be resolved from the plugin vendor side.

When adjusting the min/max/increment quantities (an array) on a per product level within the variations of a product, WooCommerce freezes up and fails to save or reload as expected, and I receive the following NGINX errors (below).

@juliaamosova What can we do to get this moving in a direction toward resolution? As a customer of WooCommerce I have gone from version 4.4.1 to 4.6.0, and am now up to WordPress 5.5.1. As a customer of IgniteWoo I have updated to the latest available 2.1.12.

The vendor states "Apparently this bug was reported back in March and fixed in WC 4.0.1, however the same bug is now back again and it has been reported to the WC devs already - again. Hopefully they can get that fixed in v4.4.2."

I could not find the git issue for that, but have to assume the comment is correct. I can only surmise that this issue (#27442) is in response to the problem and is not currently being addressed.

As a customer of WordPress, WooCommerce, and IgniteWoo -- I need a resolution to this issue. 

Please advise.


**Errors:**
> 2020/10/20 17:44:50 [error] 24254#0: *15972 FastCGI sent in stderr: "PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.p
> 2020/10/20 17:44:50 [error] 24254#0: *15972 FastCGI sent in stderr: "ordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852" while reading response header from upstream, client: X.X.X.X, server: sevenacre.farm, request: "POST /wp-admin/admin-ajax.php?_fs_blog_admin=true HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "sevenacre.farm", referrer: "https://sevenacre.farm/wp-admin/post.php?post=871&action=edit"
> 2020/10/20 17:52:53 [error] 24254#0: *16106 FastCGI sent in stderr: "PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.p
> 2020/10/20 17:52:53 [error] 24254#0: *16106 FastCGI sent in stderr: "ordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852" while reading response header from upstream, client: X.X.X.X, server: sevenacre.farm, request: "POST /wp-admin/admin-ajax.php?_fs_blog_admin=true HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "sevenacre.farm", referrer: "https://sevenacre.farm/wp-admin/post.php?post=871&action=edit"

**Comment by marke123** [comment]
We've updated code on our end to avoid this issue. You can close the ticket.

**Comment by tammullen** [comment]
Thanks @marke123 for your update.

I am reopening due to the extra information from @SevenAcreFarm

**Comment by SevenAcreFarm** [comment]
I can attest that the vendor was able to resolve this from their end, and that the updated code works as expected. 

I realize this doesn't solve the issue ultimately plaguing WooCommerce, especially if a prior bug that's been reintroduced is the culprit, but for now our specific issues seem to be addressed. We will continue to update this ticket if/as we discover further issues related to this.

Thank you for looking into this as it's unknown if the reported issue is plaguing other WooCommerce Add-ons, official or otherwise.

**Comment by marke123** [comment]
I'd say close the ticket, it was probably an edge case that other people won't experience.

**Comment by Konamiman** [comment]
I'm closing the issue for now, we can reopen it in the future if appropriate.
