### ISSUE TITLE
Product Type dropdown gone? wp.5.5 woocomerce 4.4.1

### ISSUE THREAD

**Issue by b3gund4L** [woocommerce/woocommerce#27593]
![Screenshot_2](https://user-images.githubusercontent.com/47254852/92271675-6c153380-ef12-11ea-9995-b69d901ef463.png)

can anyone help me
I have tried various methods on Github
even this I created a new domain and database,
I only installed wp and woocomerce with the default storefront theme ...

**Comment by b3gund4L** [comment]
`
### WordPress Environment ###

WordPress address (URL): https://dev.bacot.in
Site address (URL): https://dev.bacot.in
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.9
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-cll-lve
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wpkc_
Total Database Size: 3.70MB
Database Data Size: 2.32MB
Database Index Size: 1.38MB
wpkc_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpkc_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpkc_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkc_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkc_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpkc_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpkc_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_options: Data: 1.48MB + Index: 0.03MB + Engine InnoDB
wpkc_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpkc_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpkc_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkc_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkc_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpkc_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpkc_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpkc_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpkc_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpkc_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpkc_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 4.4.1
WP Database Reset: by WebFactory Ltd – 3.16

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Enable jQuery Migrate Helper: by The WordPress Team – 1.0.1
WordPress Reset: by Aristeides Stathopoulos
Matt Martz – 1.4.2


### Settings ###

API Enabled: –
Force SSL: –
Currency: IDR (Rp)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2020-09-04 17:32:37 +0000
Newest: 2020-09-04 17:34:51 +0000

`

**Comment by biuroreklama** [comment]
Try update wordpress to 5.5.1. I had this problem, but after I update WP,  default woo filters don't display.

**Comment by b3gund4L** [comment]
> Try update wordpress to 5.5.1. I had this problem, but after I update WP, default woo filters don't display.

web is already on wp 5.5.1

**Comment by juliaamosova** [comment]
Hi @b3gund4L,

Thanks for raising the issue. We fixed it in WooCommerce 4.4.2 release. Please update WooCommerce to at least 4.4.2 to get it fixed.

**Comment by juliaamosova** [comment]
Hi @b3gund4L,

My apologies! It appears that I made a mistake in my previous reply. 

We have fixed this issue on the WooCommerce side of things in version 4.3.2 (https://github.com/woocommerce/woocommerce/pull/27170). However, this issue is present on sites using WC 4.3.2+ where the issue is caused by 3rd party plugins. Which seems to be your case. 

WordPress 5.5 removed a javascript file called `jquery-migrate` that some of the plugins might still rely on. Until they update, the workaround is to use [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin to include the javascript files in the meantime.

Note that you may need to clear your browser’s cache and cookies in order for the Enable jQuery Migrate Helper plugin to take effect.

It is further recommended that you test your site for theme and plugins conflict to identify what plugin needs updating and contact that plugin author further for the issue to be fixed on that 3rd party plugin side.

To test your site for theme and plugins conflict, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by biuroreklama** [comment]
Filters still don't appear after updating Woocommerce to 4.5 version.

**Comment by b3gund4L** [comment]
> Hi @b3gund4L,
> 
> My apologies! It appears that I made a mistake in my previous reply.
> 
> We have fixed this issue on the WooCommerce side of things in version 4.3.2 (#27170). However, this issue is present on sites using WC 4.3.2+ where the issue is caused by 3rd party plugins. Which seems to be your case.
> 
> WordPress 5.5 removed a javascript file called `jquery-migrate` that some of the plugins might still rely on. Until they update, the workaround is to use [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin to include the javascript files in the meantime.
> 
> Note that you may need to clear your browser’s cache and cookies in order for the Enable jQuery Migrate Helper plugin to take effect.
> 
> It is further recommended that you test your site for theme and plugins conflict to identify what plugin needs updating and contact that plugin author further for the issue to be fixed on that 3rd party plugin side.
> 
> To test your site for theme and plugins conflict, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
> 
> If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Don't you see my woocommerce status
which only installs woocomerce and storefronts
and I don't use any plugins other than woocomerce and jquery helper
I've also tried several versions of PHP
I even reset my database and cache.

**Comment by juliaamosova** [comment]
Hi @b3gund4L, @biuroreklama,

Thanks for the additional feedback. 

Would you be able to re-apply the update to WooCommerce 4.5, either by uploading [the zip package](https://downloads.wordpress.org/plugin/woocommerce.4.5.0.zip) [through the WP admin](https://wordpress.org/support/article/managing-plugins/#manual-upload-via-wordpress-admin) manually or [via FTP](https://wordpress.org/support/article/managing-plugins/#manual-plugin-installation) and see if it fixes the issue? Thanks!

**Comment by b3gund4L** [comment]
Hi julias  @juliaamosova 
I created a new database on localhost
using wp 5.5.1 and woocomerce 4.5.0

and the problem is still the same, I don't get the product data & type dropdown menu


`
### WordPress Environment ###

WordPress address (URL): http://localhost/staging
Site address (URL): http://localhost/staging
WC Version: 4.5.0
REST API Version: ✔ 4.5.0
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.2.31
PHP Version: 7.2.31
PHP Post Max Size: 50 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.13-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.0
WC Database Prefix: wp_staging
Total Database Size: 3.78MB
Database Data Size: 2.32MB
Database Index Size: 1.46MB
wp_stagingwoocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_stagingwoocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingwoocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_stagingwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stagingwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stagingwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingwoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingactionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_stagingactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingactionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingcommentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingcomments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_staginglinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingoptions: Data: 1.48MB + Index: 0.03MB + Engine InnoDB
wp_stagingpostmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingposts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_stagingtermmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingterms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingterm_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingterm_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingusermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingusers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_stagingwc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stagingwc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingwc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stagingwc_customer_lookup: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_stagingwc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingwc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingwc_order_product_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_stagingwc_order_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_stagingwc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stagingwc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_stagingwc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stagingwc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stagingwc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 6
post: 2
product: 1

### Security ###


Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.5.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: IDR (Rp)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /index.php/shop/
Cart: #9 - /index.php/cart/
Checkout: #10 - /index.php/checkout/
My account: #11 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2020-09-09 14:00:47 +0000
Newest: 2020-09-09 14:00:47 +0000

Complete: 2
Oldest: 2020-09-09 14:00:49 +0000
Newest: 2020-09-09 14:05:45 +0000

`

**Comment by b3gund4L** [comment]
@juliaamosova 
The problem is in the chrome browser
Google Chrome is up to date
Version 85.0.4183.102 (Official Build) (64-bit)

they don't work for wp 5.5
thanks for all your help

for the future, every update pay attention on all sides ...
this is very caos
