### ISSUE TITLE
Bug - coupon usage count twice if order created by Rest-API & from backend

### ISSUE THREAD

**Issue by Abdalsalaam** [woocommerce/woocommerce#27686]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When I create order by WooCommerce Rest API, with status : pending and coupon_lines, the coupon usage will increase once, then if I change the order status to processing, the coupon usage will increase one more time!

**Expected behavior**
Coupon usage should increase once per order

**Actual behavior**
Coupon usage should increase twice per order

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1.Create new coupon.
2.Create order using WooCommerce REST API ( wc/v3/orders ). make sure that "set_paid": false and put the coupon code on coupon_lines .
3.Go to dashboard > WooCommerce coupons, you will see the new coupon usage became 1.
4.Go to WooCommerce orders list and change the order status from pending to processing.
5.Go to dashboard > WooCommerce coupons, you will see the new coupon usage became 2!.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://lacosmetic.lvendr.com
Site address (URL): https://lacosmetic.lvendr.com
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.21
PHP Post Max Size: 2 GB
PHP Time Limit: 1800
PHP Max Input Vars: 40000
cURL Version: 7.72.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.31
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 4.74MB
Database Data Size: 3.25MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.27MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acoplw_badges: 1
acoplw_prod_list: 1
attachment: 6
lacosmetic_ads: 4
lacosmetic_sliders: 4
nav_menu_item: 5
page: 7
post: 3
product: 5
product_variation: 2
revision: 2
shop_coupon: 2
shop_order: 16

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Lacosmetic custom API: by Abdalsalaam Halawa – 1.0.0
WooCommerce: by Automattic – 4.5.2
YITH WooCommerce Wishlist: by YITH – 3.0.13 – Installed version not tested with active version of WooCommerce 4.5.2

### Inactive Plugins (1) ###

WooCommerce client side REST API: by Abdalsalaam Halawa – 1.0.0 – Installed version not tested with active version of WooCommerce 4.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 37
Oldest: 2020-09-03 11:54:02 +0000
Newest: 2020-09-16 11:43:36 +0000

`
```
</details>

**Comment by tgglv** [comment]
zd-3514158

**Comment by tgglv** [comment]
3514158-zen

**Comment by dphyled** [comment]
I saw the same behavior with double coupon usage on an order created via backend as well (not from REST API).

1. Created coupon for 100% off with a usage limit of 10:

![Screenshot](https://d.pr/i/gNCfrC+)
Screenshot direct link: https://d.pr/i/gNCfrC

2. Created order, and applied coupon
![Screenshot](https://d.pr/i/CyEsfV+)
Screenshot direct link: https://d.pr/i/CyEsfV

3. Saw that coupon usage changed to 1:
![Screenshot](https://d.pr/i/VYWNtH+)
Screenshot direct link: https://d.pr/i/VYWNtH

4. Changed order status to Processing, and saw usage increased to 2:
![Screenshot](https://d.pr/i/vAdHuH+)
Screenshot direct link: https://d.pr/i/vAdHuH

@peterfabian -- not sure if this affects `priority`?

**Comment by peterfabian** [comment]
Yup, it might if we manage to reproduce it. Have you checked this with only the WooCommerce plugin active (i.e. other plugins were inactive)?

**Comment by Abdalsalaam** [comment]
@peterfabian 
@dphyled
I tested it with clean environment just WordPress and WooCommerce 
Result : the same

since this issue appear, I fixed it with temporary code to reduce usage count after rest-api order created!! 
![image](https://user-images.githubusercontent.com/19236737/112360226-228c0a80-8ce3-11eb-8628-6c56f785b87b.png)

**Comment by peterfabian** [comment]
Thanks for reporting back!

cc @vedanshujain

**Comment by bernattorras** [comment]
4075014-zen

**Comment by thuautp** [comment]
Hi @vedanshujain @peterfabian , user in #4075014-zen is asking for an update on this issue. Have you had a chance to test and replicate the issue?

**Comment by jenthakkar** [comment]
I'm still facing the same issue and I found something to like,

if I create an order via postman then it reduces the usage count by one but when I do it with the application, it reduces by two.

**Comment by luanluta** [comment]
The customer returned to ask about a fix. Can we have an update on this? 

They also reported that the code @Abdalsalaam posted works fine with the API, but stops the usage counter from increasing when using coupons on the web, and they're asking for a solution in chat.

31188308-hc
4075014-zen

**Comment by jenthakkar** [comment]
I got the issue, not the solution.

When we create an order with rest API, at that time coupon usage limit increase two times.

1st increase when the order goes in pending[payment remaining] status and 2nd time when the order goes in processing[order placed with payment] state.

Let me know if anyone can help with it.

**Comment by nixiack** [comment]
@vedanshujain @peterfabian let us know if you are able to find the solution on this issue :)

**Comment by jacoswan** [comment]
Referenced in 32157969-hc

cc @peterfabian @vedanshujain

**Comment by peterfabian** [comment]
I think this is related to a pretty important UX flow, so bumping priority, also as we're getting more reports.

**Comment by peterfabian** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Proton-Sprints-601bf65b30b069000e1c7782/issues/woocommerce/woocommerce/27686?planning-poker) with ZenHub @vedanshujain @Konamiman @barryhughes @claudiosanches @jeffstieler

**Comment by peterfabian** [comment]
We need to add a testcase for this for sure.

**Comment by jenthakkar** [comment]
We are waiting for this issue to resolve, as we are working with coupons functionality and this gives us many problems, we actually hassle with this issue, can you guys help me with this?

**Comment by peterfabian** [comment]
Hi, I believe @vedanshujain is already working on it. It will probably be fixed in the next release (6.0).

**Comment by jenthakkar** [comment]
Issue not resolved yet.

I updated Woocomrce and all plugins still issue is there.

**Comment by vedanshujain** [comment]
Hi @jenthakkar , this change will be available in WC 6.0, which should be released on second week of December.

If you need the fix more urgently, and are comfortable with editing code, taking a backup of the site, and restoring from the backup (even if site is down), then you can also apply the changes manually. Please only do this if you are comfortable with editing plugin code on the site and have done it before, as we won't be able to provide support if something goes wrong. I would really recommend waiting till WC 6.0 is released. If you still want to do it:
1. Go to file `includes/abstracts/abstract-wc-order.php ` in woocommerce folder.
2. Go to line number 1169, it should say `$coupon->increase_usage_count( $used_by );`.
3. Delete the line, and replace it with the following snippet:
```
$order_data_store = $this->get_data_store();
if ( $order_data_store->get_recorded_coupon_usage_counts( $this ) ) {
	$coupon->increase_usage_count( $used_by );
}

wc_update_coupon_usage_counts( $this->get_id() );
```
4. Save the file.

It should fix the issue while WC 6.0 is released.

**Comment by jenthakkar** [comment]
Thanks! it's solved the issue.

**Comment by devanrome1** [comment]
Seeing this issue again for the first time in a long time. Updated to WooCommerce 6.2.0 recently and am currently running that.
