### ISSUE TITLE
Bug report for: woocommerce-subscriptions/includes/class-wcs-query.php

### ISSUE THREAD

**Issue by VasilSlavchev** [woocommerce/woocommerce#28234]
Bug report for: woocommerce-subscriptions/includes/class-wcs-query.php

** I have tested it, and it works now as expected. **
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

** WCS_Query::get_endpoint_title($endpoint) should be compatible with WC_Query::get_endpoint_title($endpoint, $action = '')  **
Get endpoint title expects two parameters. One given on version 2.0.

**Expected behavior**
Take the second parameter 'áction'.

**Actual behavior**
Doesnt have second parameter 'action'.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'woocommerce-subscriptions/includes/class-wcs-query.php'

**WordPress Environment**
<details>
WooCommerce - Version 4.7.0
WooCommerce Subscriptions - Version 3.0.5
</details>

https://gist.github.com/VasilSlavchev/54301e0bf2e7266db8a4d42efe1c2816

**Comment by alexplayer** [comment]
Amazing, thanks so much @VasilSlavchev

**Comment by ahsanlt** [comment]
Having the same issue

**Comment by ahsanlt** [comment]
@VasilSlavchev fix worked.

**Comment by zdenys** [comment]
A user in 25561235-hc also reported this and was able to use the above fix.

**Comment by zdenys** [comment]
Just to close the loop, this should be fixed in version 3.0.10 of WooCommerce Subscriptions.

**Comment by juliaamosova** [comment]
Hi @VasilSlavchev,

Thanks for reporting the issue. It had been fixed in WooCommerce Subscriptions 3.0.10 as mentioned by @zdenys above. I am closing this thread.

**Comment by dchan168** [comment]
@juliaamosova This is still an issue in WooCommerce Subscription 3.0.3.  The get_endpoint_title method still missing the action = '' argument.

**Comment by vaishalijasoliya** [comment]
@VasilSlavchev Thank you so much, it was fixed,
