### ISSUE TITLE
Product gallery: Side borders caused by the image in the gallery

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce#29753]
**Describe the bug**

There are cases when the product gallery, shown in singular product views, displays a border/line on the side. Based the investigation, this line/border is a part of the previous image in the gallery, meaning that the left and/or right picture is bleeding onto main picture in view just 1 or 2px (just very noticeable on something that has a white background against other pics either side that are darker).

First, I've thought that the issue is caused by the current theme. So, I've activated official WooCommerce theme ("Storefront") but it did not resolve the problem.

**Expected behavior**
The gallery should shown only the main picture in the gallery.

**Actual behavior**
The gallery shows a part of the previous image (1px-2px) in the main gallery.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a new product
2. Set featured image
3. Add image to the gallery
4. Publish the product
5. See error

**Screencast**

https://cloudup.com/cMoGMuImqGK

**Screenshots**

Originally, the issue was spotted on [this site](https://davidperryglassceramics.uk/product/4x4cm-chequered-magnets/). The same issue using an official WooCommerce theme:

![Gallery issue](https://snipboard.io/HNovaO.jpg)

**Environment**

WordPress: 5.7.1
WooCoomerce: 5.2.2
Storefront: 3.5.1

**Comment by zhongruige** [comment]
Hi @dashkevych,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I tested on the following:

* WordPress 5.7.1
* WooCommerce 5.2.2
* Storefront theme
* Firefox and Chrome browsers

Replication Steps

* I created a new product and added a product image with another image to the gallery:

<img width="311" alt="Screen Shot 2021-04-28 at 3 54 09 PM" src="https://user-images.githubusercontent.com/71906536/116477538-ff9ccb00-a839-11eb-8a51-7678cb0121d8.png">

* I then loaded the product and scrolled through the gallery, noting the bleed-over on the edges from the previous image:

https://user-images.githubusercontent.com/71906536/116477818-5d311780-a83a-11eb-9ac9-05802106961f.mov

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by anastas10s-afk** [comment]
5716621-zen

**Comment by zaderade** [comment]
I'm guessing this has something to do with how browsers handle pixels on retina displays. Here's how I fixed it:

```
.flex-viewport .woocommerce-product-gallery__image:not(.flex-active-slide):before {
	content: '';
	background: #fff;
	position: absolute;
	right: 0;
	height: 100%;
	width: 1px;
}
```

Change #fff to your website's background color. Keep the ".flex-viewport" part so the main image isn't chopped on product pages without a product gallery (i.e., products with only one image).

Regardless of whether you apply the fix above, the right edge of the main image is slightly chopped, presumably also due to retina fudging. This is only noticeable if your image uses a dark color that fills the width and you apply a large border-radius. Here's how I fixed that:

```
.flex-viewport .woocommerce-product-gallery__image > a > img {
	width: 99.8%;
}
```

These images demonstrate before and after applying the 99.8% fix:

![before](https://github.com/user-attachments/assets/0f12e58e-113c-4710-880f-ea3934e06580)
![after](https://github.com/user-attachments/assets/cf7065c7-5ef4-463a-92c9-7aaea7ac7752)

**Comment by kmanijak** [comment]
I checked and issue can still be reproduced in both classic and block theme (Product Image Gallery block).

The image width is calculated manually and may get pixel fractions width which leads to previous and next image artefacts showing up in the gallery viewport.

The issue should be tackled in upcoming weeks 🙌

**Comment by joyryde456** [comment]
We are still seeing this on our site, we've been reporting this for about 6 years. If it helps to see it happening on a live website, here's a link: https://nomadicsupply.com/sandy-vans-rear-door-spare-tire-cargo-rack-for-2019-mercedes-sprinter-vans/

**Comment by pmcpinto** [comment]
It looks like this is still relevant. I've marked it as ready for engineering triage.

Current evidence: Trunk still contains the same product-gallery rendering paths, and a WooCommerce maintainer confirmed on 2025-03-03 that the bleed reproduces in both classic and block theme galleries. No matching open PR was found in the current PR metadata.
