### ISSUE TITLE
Attached images not showing as attached in media library (reopen)

### ISSUE THREAD

**Issue by ntindicator** [woocommerce/woocommerce#55774]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This issue was previously raised in #36811, but hasn't been fixed. The images still show as unattached, but from my testing most of the images are attached by importing a CSV file to update existing products. The images have also been manually attached to the products from the edit product screen, and are not showing as attached. When importing via CSV the results are inconsistent. In one upload the main image was showing as attached and all the gallery images were not showing as attached. In a smaller upload to correct some incorrect images, 2 out of 3 gallery images showed as attached and 1 was not. They are all attached to the products. The status of the products was set to draft. Published products may be different, and haven't been tested.

Here is a copy of the original issue:<br>When an image is attached to a Woocommerce product as either the main image or a gallery image it doesn't show as attached in the media library. The reason appears to be that the post_parent of the attachment post is not set when the image is attached to the product. To view this in the media library the list view needs to be selected, as it doesn't show in the thumbnail view. There is a column "Uploaded To" that shows whether or not the image is attached. If an image is attached to a standard Wordpress post it will show as attached, but if it's attached to a product it doesn't show as attached. It would make managing of large media libraries easier if the post_parent is set for the attachment post, as it would be possible to filter and delete unattached images more easily.

### Expected behavior

The image should show as attached in the "Uploaded To" column of the list view of the media library.

### Actual behavior

The image shows as "(Unattached)" in the media library.

### Steps to reproduce

Create simple products, and set status to draft. For CSV upload a decent number of products should be created, at least 100.

Via manual attachment:

1. 

```
Add images from the media library to a Woocommerce product and save
```

2. 

```
View the images in the media library using the list view
```

3. 

```
Locate the attached images in the library and check the status in the "Uploaded To" column
```

Via CSV upload:

1. Export csv of product IDs and names so you can identify them
2. Upload images to be attached to the products
3. Add a column named "Images: to CSV
4. Enter file names separated by commas of the images to be attached in the Images column
5. Import the CSV using the import button
6. Select update existing products
7. View the images in the media library using the list view
8. Locate the attached images in the library and check the status in the "Uploaded To" column

### WordPress Environment

System Status Report

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Ubuntu)
PHP Version: 8.3.16
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.41-0ubuntu0.22.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 2173
custom_css: 1
ebayitem: 294
elementor_library: 2
frm_form_actions: 1
frm_styles: 1
mailpoet_page: 1
nav_menu_item: 9
oembed_cache: 5
page: 20
post: 9
product: 393
revision: 763
shop_coupon: 1
shop_order: 70
shop_order_refund: 2
vcv_templates: 1
wp_global_styles: 4
wpcf7_contact_form: 1
wpephpcompat_jobs: 22
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.6.2

### Inactive Plugins (21) ###

Advanced Custom Fields: by WP Engine – 6.3.12
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.7
Classic Editor: by WordPress Contributors – 1.6.7
Classic Widgets: by WordPress Contributors – 0.3
Contact Form 7: by Takayuki Miyoshi – 6.0.4
Copytext: by The WordPress Contributors – 0.1.0
Ebay API: by Infobooks – 1.5.2
Elementor: by Elementor.com – 3.27.6
Hello Dolly: by Matt Mullenweg – 1.7.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Image Mockup Creator: by Watercolourart – 1.0.3
Matomo Analytics - Ethical Stats. Powerful Insights.: by Matomo – 5.2.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Smart Variation Swatches and Attribute Filters for WooCommerce: by aThemeArt – 1.4.0
WooCommerce Modal Fly Cart + Ajax Add to cart: by aThemeArt – 1.5.7
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PDF Invoices, Packing Slips, Delivery Notes and Shipping Labels: by WebToffee – 4.7.4
WooCommerce Stripe Gateway: by Stripe – 9.2.0
WordPress Media Javascript Guide: by Eric Andrew Lewis – 0.1
WP Instagram Widget: by Scott Evans – 2.0.3
WP Subtitle: by Ben Huson
Husani Oakley – 3.4.1


### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 5 KB

### WC Pages ###

Shop base: #58 - /shop/
Cart: #59 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #60 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #61 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Five
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2023-04-05 05:10:06 +10:00
Options: ✔
Notes: 129
Onboarding: completed

### Action Scheduler ###

Complete: 15
Oldest: 2025-02-24 13:17:58 +1100
Newest: 2025-02-24 13:17:59 +1100

Failed: 26
Oldest: 2023-02-16 14:08:35 +1100
Newest: 2025-02-19 10:43:05 +1100

Pending: 4
Oldest: 2025-02-24 13:18:21 +1100
Newest: 2025-02-26 10:43:05 +1100


### Status report information ###

Generated at: 2025-02-24 13:22:14 +11:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](<https://woocommerce.com/products/storefront/>).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samrat-biswas-git** [comment]
Hi @ntindicator — thanks for the detailed follow-up, and apologies it sat a while. The CSV-import specifics were helpful.

Context first: the original #36811 was closed as addressed by #40076, which set attachment (post_parent) for product images — but as you found, it was applied inconsistently (featured image attaches, gallery images often don't, CSV imports are mixed). So this was partially implemented rather than fully resolved.

How this should work:

1. Attach product images consistently. Set post_parent for the featured image, all gallery images, and the CSV-import path — so product images show as "Uploaded to [product]" in the Media Library. This fixes the inconsistency you're seeing.
2. Single parent for shared images. WordPress's "Uploaded to" is a single-owner concept meaning uploaded to, not exclusively used by. So an image is attached to the first product it's associated with, and if it's later used by other products we leave that parent as-is — we won't try to represent multiple parents. "Uploaded to Product A" stays accurate even when other products reuse the image.
3. Deletion safety (key requirement). Because images are now parented, deleting a product must never delete an image still used by another product — only images referenced by no other product may be cleaned up. This is the critical guardrail.

Optionally, a one-time backfill can attach existing single-owner product images that are currently unattached (skipping any already shared).

Marking this for engineering with the above as the spec.

**Comment by vladolaru** [comment]
Hey @ntindicator, I rechecked this against the current local checkout and the partial-fix pattern still reproduces.

In a local WC env (`WP 7.0`, `WC 11.0.0-dev`) I created draft products and initially unattached image attachments, then exercised several relevant existing-media write paths:

- direct product CRUD save with `set_image_id()` / `set_gallery_image_ids()` saved the product image IDs but left both attachment parents at `0`;
- CSV importer image handling parented the featured image to the product, but left both gallery images at `post_parent = 0`;
- classic product gallery metabox save saved the gallery IDs but left both gallery attachment parents at `0`;
- REST v3 product image handling parented image index `0`, but left the gallery image at `post_parent = 0`;
- REST v4 has the same first-image-only result;
- a shared-image check confirmed the existing helper does not overwrite a non-zero parent, so an image first attached to Product A stays parented to Product A when reused by Product B.

That lines up with what you saw in CSV imports: main images are more likely to show as attached, while gallery images can still show `(Unattached)` in the Media Library list view.

The current root cause is that #40076 added `wc_product_attach_featured_image()`, but that helper both sets the product featured image and parents the attachment. Because of that, current code only calls it in featured/first-image paths. Gallery paths generally only update `_product_image_gallery`, which makes the product use the image but does not update the attachment post's `post_parent`, so WordPress has nothing to show in the Media Library `Uploaded To` column.

My recommended fix would be to add a neutral helper, separate from the featured-image helper, that only parents an image to a product when the attachment is currently unattached. Then call that helper from the CSV importer, REST v3/v4 product image loops, and the classic product gallery metabox for gallery IDs as well as featured IDs. REST v2/v1 parity is worth checking if we still support product image writes there.

The main guardrail is shared/deletion safety. `post_parent` is a single-owner field, while WooCommerce product images can be reused by multiple products. So the helper should keep the current "do not overwrite an existing parent" behavior, and tests should cover that deleting one product does not delete an image still referenced by another product. I would treat any one-time backfill for existing unattached images as a separate optional step, limited to images referenced by exactly one product.

**Comment by dinhtungdu** [comment]
Thanks for the report.

I don't think that setting the first product as the parrent is the correct way to solve this issue as an image can be used by multiple products. And WordPress parent is only 1-1. I see this as the limitation of WordPress which lack of a reliable way to represent image usage, not WooCommerce issue. Because of that, I'm closing this issue as not planned.
